// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_Autocorrelation_Pipeline_VITIS_LOOP_74_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_8_address0,
        s_8_ce0,
        s_8_we0,
        s_8_d0,
        s_8_address1,
        s_8_ce1,
        s_8_q1,
        s_7_address0,
        s_7_ce0,
        s_7_we0,
        s_7_d0,
        s_7_address1,
        s_7_ce1,
        s_7_q1,
        s_6_address0,
        s_6_ce0,
        s_6_we0,
        s_6_d0,
        s_6_address1,
        s_6_ce1,
        s_6_q1,
        s_5_address0,
        s_5_ce0,
        s_5_we0,
        s_5_d0,
        s_5_address1,
        s_5_ce1,
        s_5_q1,
        s_4_address0,
        s_4_ce0,
        s_4_we0,
        s_4_d0,
        s_4_address1,
        s_4_ce1,
        s_4_q1,
        s_3_address0,
        s_3_ce0,
        s_3_we0,
        s_3_d0,
        s_3_address1,
        s_3_ce1,
        s_3_q1,
        s_2_address0,
        s_2_ce0,
        s_2_we0,
        s_2_d0,
        s_2_address1,
        s_2_ce1,
        s_2_q1,
        s_1_address0,
        s_1_ce0,
        s_1_we0,
        s_1_d0,
        s_1_address1,
        s_1_ce1,
        s_1_q1,
        s_0_address0,
        s_0_ce0,
        s_0_we0,
        s_0_d0,
        s_0_address1,
        s_0_ce1,
        s_0_q1,
        zext_ln74
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] s_8_address0;
output   s_8_ce0;
output   s_8_we0;
output  [15:0] s_8_d0;
output  [4:0] s_8_address1;
output   s_8_ce1;
input  [15:0] s_8_q1;
output  [4:0] s_7_address0;
output   s_7_ce0;
output   s_7_we0;
output  [15:0] s_7_d0;
output  [4:0] s_7_address1;
output   s_7_ce1;
input  [15:0] s_7_q1;
output  [4:0] s_6_address0;
output   s_6_ce0;
output   s_6_we0;
output  [15:0] s_6_d0;
output  [4:0] s_6_address1;
output   s_6_ce1;
input  [15:0] s_6_q1;
output  [4:0] s_5_address0;
output   s_5_ce0;
output   s_5_we0;
output  [15:0] s_5_d0;
output  [4:0] s_5_address1;
output   s_5_ce1;
input  [15:0] s_5_q1;
output  [4:0] s_4_address0;
output   s_4_ce0;
output   s_4_we0;
output  [15:0] s_4_d0;
output  [4:0] s_4_address1;
output   s_4_ce1;
input  [15:0] s_4_q1;
output  [4:0] s_3_address0;
output   s_3_ce0;
output   s_3_we0;
output  [15:0] s_3_d0;
output  [4:0] s_3_address1;
output   s_3_ce1;
input  [15:0] s_3_q1;
output  [4:0] s_2_address0;
output   s_2_ce0;
output   s_2_we0;
output  [15:0] s_2_d0;
output  [4:0] s_2_address1;
output   s_2_ce1;
input  [15:0] s_2_q1;
output  [4:0] s_1_address0;
output   s_1_ce0;
output   s_1_we0;
output  [15:0] s_1_d0;
output  [4:0] s_1_address1;
output   s_1_ce1;
input  [15:0] s_1_q1;
output  [4:0] s_0_address0;
output   s_0_ce0;
output   s_0_we0;
output  [15:0] s_0_d0;
output  [4:0] s_0_address1;
output   s_0_ce1;
input  [15:0] s_0_q1;
input  [14:0] zext_ln74;

reg ap_idle;
reg s_8_ce0;
reg s_8_we0;
reg s_8_ce1;
reg s_7_ce0;
reg s_7_we0;
reg s_7_ce1;
reg s_6_ce0;
reg s_6_we0;
reg s_6_ce1;
reg s_5_ce0;
reg s_5_we0;
reg s_5_ce1;
reg s_4_ce0;
reg s_4_we0;
reg s_4_ce1;
reg s_3_ce0;
reg s_3_we0;
reg s_3_ce1;
reg s_2_ce0;
reg s_2_we0;
reg s_2_ce1;
reg s_1_ce0;
reg s_1_we0;
reg s_1_ce1;
reg s_0_ce0;
reg s_0_we0;
reg s_0_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln74_fu_283_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [30:0] zext_ln74_cast_fu_261_p1;
reg   [30:0] zext_ln74_cast_reg_464;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln74_reg_469;
reg   [4:0] s_0_addr_reg_473;
reg   [4:0] s_0_addr_reg_473_pp0_iter1_reg;
reg   [4:0] s_0_addr_reg_473_pp0_iter2_reg;
reg   [4:0] s_0_addr_reg_473_pp0_iter3_reg;
reg   [4:0] s_1_addr_reg_479;
reg   [4:0] s_1_addr_reg_479_pp0_iter1_reg;
reg   [4:0] s_1_addr_reg_479_pp0_iter2_reg;
reg   [4:0] s_1_addr_reg_479_pp0_iter3_reg;
reg   [4:0] s_2_addr_reg_485;
reg   [4:0] s_2_addr_reg_485_pp0_iter1_reg;
reg   [4:0] s_2_addr_reg_485_pp0_iter2_reg;
reg   [4:0] s_2_addr_reg_485_pp0_iter3_reg;
reg   [4:0] s_3_addr_reg_491;
reg   [4:0] s_3_addr_reg_491_pp0_iter1_reg;
reg   [4:0] s_3_addr_reg_491_pp0_iter2_reg;
reg   [4:0] s_3_addr_reg_491_pp0_iter3_reg;
reg   [4:0] s_4_addr_reg_497;
reg   [4:0] s_4_addr_reg_497_pp0_iter1_reg;
reg   [4:0] s_4_addr_reg_497_pp0_iter2_reg;
reg   [4:0] s_4_addr_reg_497_pp0_iter3_reg;
reg   [4:0] s_5_addr_reg_503;
reg   [4:0] s_5_addr_reg_503_pp0_iter1_reg;
reg   [4:0] s_5_addr_reg_503_pp0_iter2_reg;
reg   [4:0] s_5_addr_reg_503_pp0_iter3_reg;
reg   [4:0] s_6_addr_reg_509;
reg   [4:0] s_6_addr_reg_509_pp0_iter1_reg;
reg   [4:0] s_6_addr_reg_509_pp0_iter2_reg;
reg   [4:0] s_6_addr_reg_509_pp0_iter3_reg;
reg   [4:0] s_7_addr_reg_515;
reg   [4:0] s_7_addr_reg_515_pp0_iter1_reg;
reg   [4:0] s_7_addr_reg_515_pp0_iter2_reg;
reg   [4:0] s_7_addr_reg_515_pp0_iter3_reg;
reg   [4:0] s_8_addr_reg_521;
reg   [4:0] s_8_addr_reg_521_pp0_iter1_reg;
reg   [4:0] s_8_addr_reg_521_pp0_iter2_reg;
reg   [4:0] s_8_addr_reg_521_pp0_iter3_reg;
wire   [3:0] trunc_ln46_fu_340_p1;
reg   [3:0] trunc_ln46_reg_527;
reg   [3:0] trunc_ln46_reg_527_pp0_iter2_reg;
reg   [3:0] trunc_ln46_reg_527_pp0_iter3_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln46_fu_314_p1;
wire    ap_block_pp0_stage0;
reg   [7:0] phi_urem41_fu_90;
wire   [7:0] select_ln74_fu_404_p3;
wire    ap_loop_init;
reg   [16:0] phi_mul39_fu_94;
wire   [16:0] add_ln46_fu_298_p2;
reg   [16:0] ap_sig_allocacmp_phi_mul39_load;
reg   [7:0] k_2_fu_98;
wire   [7:0] add_ln74_fu_289_p2;
reg   [7:0] ap_sig_allocacmp_k;
wire   [4:0] tmp_fu_304_p4;
wire   [15:0] a_assign_1_fu_344_p19;
wire   [3:0] a_assign_1_fu_344_p20;
wire  signed [15:0] a_assign_1_fu_344_p21;
wire   [7:0] add_ln74_1_fu_392_p2;
wire   [0:0] icmp_ln74_1_fu_398_p2;
wire  signed [30:0] trunc_ln_fu_417_p1;
wire   [30:0] grp_fu_435_p3;
wire   [14:0] grp_fu_435_p1;
wire   [14:0] grp_fu_435_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [3:0] a_assign_1_fu_344_p1;
wire   [3:0] a_assign_1_fu_344_p3;
wire   [3:0] a_assign_1_fu_344_p5;
wire   [3:0] a_assign_1_fu_344_p7;
wire   [3:0] a_assign_1_fu_344_p9;
wire   [3:0] a_assign_1_fu_344_p11;
wire   [3:0] a_assign_1_fu_344_p13;
wire   [3:0] a_assign_1_fu_344_p15;
wire  signed [3:0] a_assign_1_fu_344_p17;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 phi_urem41_fu_90 = 8'd0;
#0 phi_mul39_fu_94 = 17'd0;
#0 k_2_fu_98 = 8'd0;
#0 ap_done_reg = 1'b0;
end

main_sparsemux_19_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_U23(
    .din0(s_0_q1),
    .din1(s_1_q1),
    .din2(s_2_q1),
    .din3(s_3_q1),
    .din4(s_4_q1),
    .din5(s_5_q1),
    .din6(s_6_q1),
    .din7(s_7_q1),
    .din8(s_8_q1),
    .def(a_assign_1_fu_344_p19),
    .sel(a_assign_1_fu_344_p20),
    .dout(a_assign_1_fu_344_p21)
);

main_mac_muladd_16s_15ns_15ns_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_15ns_31_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_assign_1_fu_344_p21),
    .din1(grp_fu_435_p1),
    .din2(grp_fu_435_p2),
    .ce(1'b1),
    .dout(grp_fu_435_p3)
);

main_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln74_fu_283_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_2_fu_98 <= add_ln74_fu_289_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_2_fu_98 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln74_fu_283_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_mul39_fu_94 <= add_ln46_fu_298_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul39_fu_94 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_urem41_fu_90 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln74_reg_469 == 1'd0))) begin
            phi_urem41_fu_90 <= select_ln74_fu_404_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln74_reg_469 <= icmp_ln74_fu_283_p2;
        s_0_addr_reg_473 <= zext_ln46_fu_314_p1;
        s_0_addr_reg_473_pp0_iter1_reg <= s_0_addr_reg_473;
        s_1_addr_reg_479 <= zext_ln46_fu_314_p1;
        s_1_addr_reg_479_pp0_iter1_reg <= s_1_addr_reg_479;
        s_2_addr_reg_485 <= zext_ln46_fu_314_p1;
        s_2_addr_reg_485_pp0_iter1_reg <= s_2_addr_reg_485;
        s_3_addr_reg_491 <= zext_ln46_fu_314_p1;
        s_3_addr_reg_491_pp0_iter1_reg <= s_3_addr_reg_491;
        s_4_addr_reg_497 <= zext_ln46_fu_314_p1;
        s_4_addr_reg_497_pp0_iter1_reg <= s_4_addr_reg_497;
        s_5_addr_reg_503 <= zext_ln46_fu_314_p1;
        s_5_addr_reg_503_pp0_iter1_reg <= s_5_addr_reg_503;
        s_6_addr_reg_509 <= zext_ln46_fu_314_p1;
        s_6_addr_reg_509_pp0_iter1_reg <= s_6_addr_reg_509;
        s_7_addr_reg_515 <= zext_ln46_fu_314_p1;
        s_7_addr_reg_515_pp0_iter1_reg <= s_7_addr_reg_515;
        s_8_addr_reg_521 <= zext_ln46_fu_314_p1;
        s_8_addr_reg_521_pp0_iter1_reg <= s_8_addr_reg_521;
        trunc_ln46_reg_527 <= trunc_ln46_fu_340_p1;
        zext_ln74_cast_reg_464[14 : 0] <= zext_ln74_cast_fu_261_p1[14 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        s_0_addr_reg_473_pp0_iter2_reg <= s_0_addr_reg_473_pp0_iter1_reg;
        s_0_addr_reg_473_pp0_iter3_reg <= s_0_addr_reg_473_pp0_iter2_reg;
        s_1_addr_reg_479_pp0_iter2_reg <= s_1_addr_reg_479_pp0_iter1_reg;
        s_1_addr_reg_479_pp0_iter3_reg <= s_1_addr_reg_479_pp0_iter2_reg;
        s_2_addr_reg_485_pp0_iter2_reg <= s_2_addr_reg_485_pp0_iter1_reg;
        s_2_addr_reg_485_pp0_iter3_reg <= s_2_addr_reg_485_pp0_iter2_reg;
        s_3_addr_reg_491_pp0_iter2_reg <= s_3_addr_reg_491_pp0_iter1_reg;
        s_3_addr_reg_491_pp0_iter3_reg <= s_3_addr_reg_491_pp0_iter2_reg;
        s_4_addr_reg_497_pp0_iter2_reg <= s_4_addr_reg_497_pp0_iter1_reg;
        s_4_addr_reg_497_pp0_iter3_reg <= s_4_addr_reg_497_pp0_iter2_reg;
        s_5_addr_reg_503_pp0_iter2_reg <= s_5_addr_reg_503_pp0_iter1_reg;
        s_5_addr_reg_503_pp0_iter3_reg <= s_5_addr_reg_503_pp0_iter2_reg;
        s_6_addr_reg_509_pp0_iter2_reg <= s_6_addr_reg_509_pp0_iter1_reg;
        s_6_addr_reg_509_pp0_iter3_reg <= s_6_addr_reg_509_pp0_iter2_reg;
        s_7_addr_reg_515_pp0_iter2_reg <= s_7_addr_reg_515_pp0_iter1_reg;
        s_7_addr_reg_515_pp0_iter3_reg <= s_7_addr_reg_515_pp0_iter2_reg;
        s_8_addr_reg_521_pp0_iter2_reg <= s_8_addr_reg_521_pp0_iter1_reg;
        s_8_addr_reg_521_pp0_iter3_reg <= s_8_addr_reg_521_pp0_iter2_reg;
        trunc_ln46_reg_527_pp0_iter2_reg <= trunc_ln46_reg_527;
        trunc_ln46_reg_527_pp0_iter3_reg <= trunc_ln46_reg_527_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((icmp_ln74_fu_283_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln74_reg_469 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k = 8'd0;
    end else begin
        ap_sig_allocacmp_k = k_2_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_mul39_load = 17'd0;
    end else begin
        ap_sig_allocacmp_phi_mul39_load = phi_mul39_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_0_ce0 = 1'b1;
    end else begin
        s_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_0_ce1 = 1'b1;
    end else begin
        s_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd0))) begin
        s_0_we0 = 1'b1;
    end else begin
        s_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_1_ce0 = 1'b1;
    end else begin
        s_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_1_ce1 = 1'b1;
    end else begin
        s_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd1))) begin
        s_1_we0 = 1'b1;
    end else begin
        s_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_2_ce0 = 1'b1;
    end else begin
        s_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_2_ce1 = 1'b1;
    end else begin
        s_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd2))) begin
        s_2_we0 = 1'b1;
    end else begin
        s_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_3_ce0 = 1'b1;
    end else begin
        s_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_3_ce1 = 1'b1;
    end else begin
        s_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd3))) begin
        s_3_we0 = 1'b1;
    end else begin
        s_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_4_ce0 = 1'b1;
    end else begin
        s_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_4_ce1 = 1'b1;
    end else begin
        s_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd4))) begin
        s_4_we0 = 1'b1;
    end else begin
        s_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_5_ce0 = 1'b1;
    end else begin
        s_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_5_ce1 = 1'b1;
    end else begin
        s_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd5))) begin
        s_5_we0 = 1'b1;
    end else begin
        s_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_6_ce0 = 1'b1;
    end else begin
        s_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_6_ce1 = 1'b1;
    end else begin
        s_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd6))) begin
        s_6_we0 = 1'b1;
    end else begin
        s_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_7_ce0 = 1'b1;
    end else begin
        s_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_7_ce1 = 1'b1;
    end else begin
        s_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln46_reg_527_pp0_iter3_reg == 4'd7))) begin
        s_7_we0 = 1'b1;
    end else begin
        s_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_8_ce0 = 1'b1;
    end else begin
        s_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_8_ce1 = 1'b1;
    end else begin
        s_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd7) & ~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd6) & ~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd5) & ~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd4) & ~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd3) & ~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd2) & ~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd1) & ~(trunc_ln46_reg_527_pp0_iter3_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_8_we0 = 1'b1;
    end else begin
        s_8_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_assign_1_fu_344_p19 = 'bx;

assign a_assign_1_fu_344_p20 = phi_urem41_fu_90[3:0];

assign add_ln46_fu_298_p2 = (ap_sig_allocacmp_phi_mul39_load + 17'd456);

assign add_ln74_1_fu_392_p2 = (phi_urem41_fu_90 + 8'd1);

assign add_ln74_fu_289_p2 = (ap_sig_allocacmp_k + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_435_p1 = zext_ln74_cast_reg_464;

assign grp_fu_435_p2 = 31'd16384;

assign icmp_ln74_1_fu_398_p2 = ((add_ln74_1_fu_392_p2 < 8'd9) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_283_p2 = ((ap_sig_allocacmp_k == 8'd160) ? 1'b1 : 1'b0);

assign s_0_address0 = s_0_addr_reg_473_pp0_iter3_reg;

assign s_0_address1 = zext_ln46_fu_314_p1;

assign s_0_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_1_address0 = s_1_addr_reg_479_pp0_iter3_reg;

assign s_1_address1 = zext_ln46_fu_314_p1;

assign s_1_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_2_address0 = s_2_addr_reg_485_pp0_iter3_reg;

assign s_2_address1 = zext_ln46_fu_314_p1;

assign s_2_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_3_address0 = s_3_addr_reg_491_pp0_iter3_reg;

assign s_3_address1 = zext_ln46_fu_314_p1;

assign s_3_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_4_address0 = s_4_addr_reg_497_pp0_iter3_reg;

assign s_4_address1 = zext_ln46_fu_314_p1;

assign s_4_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_5_address0 = s_5_addr_reg_503_pp0_iter3_reg;

assign s_5_address1 = zext_ln46_fu_314_p1;

assign s_5_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_6_address0 = s_6_addr_reg_509_pp0_iter3_reg;

assign s_6_address1 = zext_ln46_fu_314_p1;

assign s_6_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_7_address0 = s_7_addr_reg_515_pp0_iter3_reg;

assign s_7_address1 = zext_ln46_fu_314_p1;

assign s_7_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign s_8_address0 = s_8_addr_reg_521_pp0_iter3_reg;

assign s_8_address1 = zext_ln46_fu_314_p1;

assign s_8_d0 = {{trunc_ln_fu_417_p1[30:15]}};

assign select_ln74_fu_404_p3 = ((icmp_ln74_1_fu_398_p2[0:0] == 1'b1) ? add_ln74_1_fu_392_p2 : 8'd0);

assign tmp_fu_304_p4 = {{ap_sig_allocacmp_phi_mul39_load[16:12]}};

assign trunc_ln46_fu_340_p1 = phi_urem41_fu_90[3:0];

assign trunc_ln_fu_417_p1 = grp_fu_435_p3;

assign zext_ln46_fu_314_p1 = tmp_fu_304_p4;

assign zext_ln74_cast_fu_261_p1 = zext_ln74;

always @ (posedge ap_clk) begin
    zext_ln74_cast_reg_464[30:15] <= 16'b0000000000000000;
end

endmodule //main_Autocorrelation_Pipeline_VITIS_LOOP_74_2
