// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_Quantization_and_coding (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        LAR_address0,
        LAR_ce0,
        LAR_we0,
        LAR_d0,
        LAR_q0,
        LAR_address1,
        LAR_ce1,
        LAR_we1,
        LAR_d1,
        LAR_q1
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] LAR_address0;
output   LAR_ce0;
output   LAR_we0;
output  [15:0] LAR_d0;
input  [15:0] LAR_q0;
output  [2:0] LAR_address1;
output   LAR_ce1;
output   LAR_we1;
output  [15:0] LAR_d1;
input  [15:0] LAR_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] LAR_address0;
reg LAR_ce0;
reg LAR_we0;
reg[15:0] LAR_d0;
reg[2:0] LAR_address1;
reg LAR_ce1;
reg LAR_we1;
reg[15:0] LAR_d1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] LAR_addr_reg_1425;
wire   [2:0] LAR_addr_1_reg_1430;
wire   [6:0] select_ln300_1_fu_329_p3;
reg   [6:0] select_ln300_1_reg_1435;
wire    ap_CS_fsm_state2;
wire   [6:0] select_ln301_1_fu_463_p3;
reg   [6:0] select_ln301_1_reg_1440;
wire   [2:0] LAR_addr_2_reg_1445;
wire   [2:0] LAR_addr_3_reg_1450;
wire   [6:0] select_ln302_1_fu_635_p3;
reg   [6:0] select_ln302_1_reg_1455;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln39_9_fu_731_p2;
reg   [0:0] icmp_ln39_9_reg_1460;
reg   [6:0] tmp_4_reg_1465;
wire   [2:0] LAR_addr_4_reg_1470;
wire   [2:0] LAR_addr_5_reg_1475;
wire   [6:0] select_ln303_1_fu_795_p3;
reg   [6:0] select_ln303_1_reg_1480;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln39_11_fu_881_p2;
reg   [0:0] icmp_ln39_11_reg_1485;
reg   [6:0] tmp_5_reg_1490;
wire   [0:0] icmp_ln39_13_fu_985_p2;
reg   [0:0] icmp_ln39_13_reg_1495;
reg   [6:0] tmp_6_reg_1500;
wire   [2:0] LAR_addr_6_reg_1505;
wire   [2:0] LAR_addr_7_reg_1510;
wire   [6:0] select_ln305_1_fu_1057_p3;
reg   [6:0] select_ln305_1_reg_1515;
wire    ap_CS_fsm_state5;
wire   [6:0] select_ln306_1_fu_1113_p3;
reg   [6:0] select_ln306_1_reg_1520;
wire   [0:0] icmp_ln39_15_fu_1189_p2;
reg   [0:0] icmp_ln39_15_reg_1525;
reg   [6:0] tmp_7_reg_1530;
wire   [0:0] icmp_ln39_17_fu_1273_p2;
reg   [0:0] icmp_ln39_17_reg_1535;
reg   [6:0] tmp_8_reg_1540;
wire   [6:0] select_ln307_1_fu_1345_p3;
reg   [6:0] select_ln307_1_reg_1545;
wire    ap_CS_fsm_state6;
wire   [6:0] select_ln308_1_fu_1401_p3;
reg   [6:0] select_ln308_1_reg_1550;
wire   [15:0] zext_ln300_fu_1001_p1;
wire   [15:0] zext_ln301_fu_1005_p1;
wire   [15:0] zext_ln302_fu_1289_p1;
wire   [15:0] zext_ln303_fu_1293_p1;
wire    ap_CS_fsm_state7;
wire   [15:0] zext_ln305_fu_1409_p1;
wire   [15:0] zext_ln306_fu_1413_p1;
wire    ap_CS_fsm_state8;
wire   [15:0] zext_ln307_fu_1417_p1;
wire   [15:0] zext_ln308_fu_1421_p1;
wire   [29:0] shl_ln_fu_203_p3;
wire   [27:0] shl_ln48_1_fu_215_p3;
wire  signed [30:0] sext_ln48_fu_211_p1;
wire  signed [30:0] sext_ln48_1_fu_223_p1;
wire   [30:0] add_ln48_fu_227_p2;
wire   [15:0] temp_fu_233_p4;
wire  signed [16:0] sext_ln38_fu_243_p1;
wire   [16:0] sum_fu_247_p2;
wire   [1:0] tmp_9_fu_253_p4;
wire   [0:0] icmp_ln39_fu_263_p2;
wire   [6:0] tmp_fu_269_p4;
wire   [6:0] temp_13_fu_279_p3;
wire   [1:0] tmp_10_fu_287_p4;
wire   [0:0] icmp_ln300_fu_297_p2;
wire   [0:0] icmp_ln300_1_fu_303_p2;
wire   [0:0] or_ln300_fu_323_p2;
wire   [6:0] select_ln300_fu_315_p3;
wire   [6:0] add_ln300_fu_309_p2;
wire   [29:0] shl_ln48_2_fu_337_p3;
wire   [27:0] shl_ln48_3_fu_349_p3;
wire  signed [30:0] sext_ln48_2_fu_345_p1;
wire  signed [30:0] sext_ln48_3_fu_357_p1;
wire   [30:0] add_ln48_1_fu_361_p2;
wire   [15:0] temp_14_fu_367_p4;
wire  signed [16:0] sext_ln38_3_fu_377_p1;
wire   [16:0] sum_2_fu_381_p2;
wire   [1:0] tmp_11_fu_387_p4;
wire   [0:0] icmp_ln39_5_fu_397_p2;
wire   [6:0] tmp_2_fu_403_p4;
wire   [6:0] temp_15_fu_413_p3;
wire   [1:0] tmp_12_fu_421_p4;
wire   [0:0] icmp_ln301_fu_431_p2;
wire   [0:0] icmp_ln301_1_fu_437_p2;
wire   [0:0] or_ln301_fu_457_p2;
wire   [6:0] select_ln301_fu_449_p3;
wire   [6:0] add_ln301_fu_443_p2;
wire   [29:0] shl_ln48_4_fu_471_p3;
wire   [27:0] shl_ln48_5_fu_483_p3;
wire  signed [30:0] sext_ln48_4_fu_479_p1;
wire  signed [30:0] sext_ln48_5_fu_491_p1;
wire   [30:0] add_ln48_2_fu_495_p2;
wire   [15:0] temp_16_fu_501_p4;
wire  signed [16:0] sext_ln38_4_fu_511_p1;
wire   [16:0] sum_3_fu_515_p2;
wire   [1:0] tmp_13_fu_521_p4;
wire   [0:0] icmp_ln39_6_fu_531_p2;
wire   [15:0] trunc_ln39_fu_537_p1;
wire   [15:0] temp_17_fu_541_p3;
wire  signed [16:0] sext_ln38_5_fu_549_p1;
wire   [16:0] sum_4_fu_553_p2;
wire   [1:0] tmp_14_fu_559_p4;
wire   [0:0] icmp_ln39_7_fu_569_p2;
wire   [6:0] tmp_3_fu_575_p4;
wire   [6:0] temp_18_fu_585_p3;
wire   [2:0] tmp_15_fu_593_p4;
wire   [0:0] icmp_ln302_fu_603_p2;
wire   [0:0] icmp_ln302_1_fu_609_p2;
wire   [0:0] or_ln302_fu_629_p2;
wire   [6:0] select_ln302_fu_621_p3;
wire   [6:0] add_ln302_fu_615_p2;
wire   [29:0] shl_ln48_6_fu_643_p3;
wire   [27:0] shl_ln48_7_fu_655_p3;
wire  signed [30:0] sext_ln48_6_fu_651_p1;
wire  signed [30:0] sext_ln48_7_fu_663_p1;
wire   [30:0] add_ln48_3_fu_667_p2;
wire   [15:0] temp_19_fu_673_p4;
wire  signed [16:0] sext_ln38_6_fu_683_p1;
wire   [16:0] sum_5_fu_687_p2;
wire   [0:0] icmp_ln39_8_fu_693_p2;
wire   [15:0] trunc_ln39_1_fu_699_p1;
wire   [15:0] temp_20_fu_703_p3;
wire  signed [16:0] sext_ln38_7_fu_711_p1;
wire   [16:0] sum_6_fu_715_p2;
wire   [1:0] tmp_16_fu_721_p4;
wire   [6:0] temp_21_fu_747_p3;
wire   [2:0] tmp_17_fu_753_p4;
wire   [0:0] icmp_ln303_fu_763_p2;
wire   [0:0] icmp_ln303_1_fu_769_p2;
wire   [0:0] or_ln303_fu_789_p2;
wire   [6:0] select_ln303_fu_781_p3;
wire   [6:0] add_ln303_fu_775_p2;
wire   [14:0] mul_ln48_fu_807_p1;
wire   [30:0] mul_ln48_fu_807_p2;
wire   [15:0] temp_22_fu_813_p4;
wire  signed [16:0] sext_ln38_8_fu_823_p1;
wire   [16:0] sum_7_fu_827_p2;
wire   [1:0] tmp_18_fu_833_p4;
wire   [0:0] icmp_ln39_10_fu_843_p2;
wire   [15:0] trunc_ln39_2_fu_849_p1;
wire   [15:0] temp_23_fu_853_p3;
wire  signed [16:0] sext_ln38_9_fu_861_p1;
wire   [16:0] sum_8_fu_865_p2;
wire   [1:0] tmp_19_fu_871_p4;
wire   [29:0] shl_ln48_8_fu_897_p3;
wire   [25:0] shl_ln48_9_fu_909_p3;
wire  signed [30:0] sext_ln48_9_fu_905_p1;
wire  signed [30:0] sext_ln48_10_fu_917_p1;
wire   [30:0] sub_ln48_fu_921_p2;
wire   [15:0] temp_25_fu_927_p4;
wire  signed [16:0] sext_ln38_10_fu_937_p1;
wire   [16:0] sum_9_fu_941_p2;
wire   [0:0] icmp_ln39_12_fu_947_p2;
wire   [15:0] trunc_ln39_3_fu_953_p1;
wire   [15:0] temp_26_fu_957_p3;
wire  signed [16:0] sext_ln38_11_fu_965_p1;
wire   [16:0] sum_10_fu_969_p2;
wire   [1:0] tmp_21_fu_975_p4;
wire   [6:0] temp_24_fu_1009_p3;
wire   [3:0] tmp_20_fu_1015_p4;
wire   [0:0] icmp_ln305_fu_1025_p2;
wire   [0:0] icmp_ln305_1_fu_1031_p2;
wire   [0:0] or_ln305_fu_1051_p2;
wire   [6:0] select_ln305_fu_1043_p3;
wire   [6:0] add_ln305_fu_1037_p2;
wire   [6:0] temp_27_fu_1065_p3;
wire   [3:0] tmp_22_fu_1071_p4;
wire   [0:0] icmp_ln306_fu_1081_p2;
wire   [0:0] icmp_ln306_1_fu_1087_p2;
wire   [0:0] or_ln306_fu_1107_p2;
wire   [6:0] select_ln306_fu_1099_p3;
wire   [6:0] add_ln306_fu_1093_p2;
wire   [14:0] mul_ln48_1_fu_1125_p1;
wire   [30:0] mul_ln48_1_fu_1125_p2;
wire   [15:0] temp_28_fu_1131_p4;
wire  signed [16:0] sext_ln38_12_fu_1141_p1;
wire   [16:0] sum_11_fu_1145_p2;
wire   [0:0] icmp_ln39_14_fu_1151_p2;
wire   [15:0] trunc_ln39_4_fu_1157_p1;
wire   [15:0] temp_29_fu_1161_p3;
wire  signed [16:0] sext_ln38_13_fu_1169_p1;
wire   [16:0] sum_12_fu_1173_p2;
wire   [1:0] tmp_23_fu_1179_p4;
wire   [14:0] mul_ln48_2_fu_1209_p1;
wire   [30:0] mul_ln48_2_fu_1209_p2;
wire   [15:0] temp_31_fu_1215_p4;
wire  signed [16:0] sext_ln38_14_fu_1225_p1;
wire   [16:0] sum_13_fu_1229_p2;
wire   [0:0] icmp_ln39_16_fu_1235_p2;
wire   [15:0] trunc_ln39_5_fu_1241_p1;
wire   [15:0] temp_32_fu_1245_p3;
wire  signed [16:0] sext_ln38_15_fu_1253_p1;
wire   [16:0] sum_14_fu_1257_p2;
wire   [1:0] tmp_25_fu_1263_p4;
wire   [6:0] temp_30_fu_1297_p3;
wire   [4:0] tmp_24_fu_1303_p4;
wire   [0:0] icmp_ln307_fu_1313_p2;
wire   [0:0] icmp_ln307_1_fu_1319_p2;
wire   [0:0] or_ln307_fu_1339_p2;
wire   [6:0] select_ln307_fu_1331_p3;
wire   [6:0] add_ln307_fu_1325_p2;
wire   [6:0] temp_33_fu_1353_p3;
wire   [4:0] tmp_26_fu_1359_p4;
wire   [0:0] icmp_ln308_fu_1369_p2;
wire   [0:0] icmp_ln308_1_fu_1375_p2;
wire   [0:0] or_ln308_fu_1395_p2;
wire   [6:0] select_ln308_fu_1387_p3;
wire   [6:0] add_ln308_fu_1381_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

main_mul_16s_15ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 31 ))
mul_16s_15ns_31_1_1_U189(
    .din0(LAR_q1),
    .din1(mul_ln48_fu_807_p1),
    .dout(mul_ln48_fu_807_p2)
);

main_mul_16s_15ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 31 ))
mul_16s_15ns_31_1_1_U190(
    .din0(LAR_q1),
    .din1(mul_ln48_1_fu_1125_p1),
    .dout(mul_ln48_1_fu_1125_p2)
);

main_mul_16s_15ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 31 ))
mul_16s_15ns_31_1_1_U191(
    .din0(LAR_q0),
    .din1(mul_ln48_2_fu_1209_p1),
    .dout(mul_ln48_2_fu_1209_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln39_11_reg_1485 <= icmp_ln39_11_fu_881_p2;
        icmp_ln39_13_reg_1495 <= icmp_ln39_13_fu_985_p2;
        select_ln303_1_reg_1480 <= select_ln303_1_fu_795_p3;
        tmp_5_reg_1490 <= {{sum_8_fu_865_p2[15:9]}};
        tmp_6_reg_1500 <= {{sum_10_fu_969_p2[15:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln39_15_reg_1525 <= icmp_ln39_15_fu_1189_p2;
        icmp_ln39_17_reg_1535 <= icmp_ln39_17_fu_1273_p2;
        select_ln305_1_reg_1515 <= select_ln305_1_fu_1057_p3;
        select_ln306_1_reg_1520 <= select_ln306_1_fu_1113_p3;
        tmp_7_reg_1530 <= {{sum_12_fu_1173_p2[15:9]}};
        tmp_8_reg_1540 <= {{sum_14_fu_1257_p2[15:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln39_9_reg_1460 <= icmp_ln39_9_fu_731_p2;
        select_ln302_1_reg_1455 <= select_ln302_1_fu_635_p3;
        tmp_4_reg_1465 <= {{sum_6_fu_715_p2[15:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln300_1_reg_1435 <= select_ln300_1_fu_329_p3;
        select_ln301_1_reg_1440 <= select_ln301_1_fu_463_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        select_ln307_1_reg_1545 <= select_ln307_1_fu_1345_p3;
        select_ln308_1_reg_1550 <= select_ln308_1_fu_1401_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        LAR_address0 = LAR_addr_7_reg_1510;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        LAR_address0 = LAR_addr_5_reg_1475;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        LAR_address0 = LAR_addr_3_reg_1450;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        LAR_address0 = LAR_addr_1_reg_1430;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        LAR_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LAR_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        LAR_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        LAR_address0 = 64'd1;
    end else begin
        LAR_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        LAR_address1 = LAR_addr_6_reg_1505;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        LAR_address1 = LAR_addr_4_reg_1470;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        LAR_address1 = LAR_addr_2_reg_1445;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        LAR_address1 = LAR_addr_reg_1425;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        LAR_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LAR_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        LAR_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        LAR_address1 = 64'd0;
    end else begin
        LAR_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        LAR_ce0 = 1'b1;
    end else begin
        LAR_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        LAR_ce1 = 1'b1;
    end else begin
        LAR_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        LAR_d0 = zext_ln308_fu_1421_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        LAR_d0 = zext_ln306_fu_1413_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        LAR_d0 = zext_ln303_fu_1293_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        LAR_d0 = zext_ln301_fu_1005_p1;
    end else begin
        LAR_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        LAR_d1 = zext_ln307_fu_1417_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        LAR_d1 = zext_ln305_fu_1409_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        LAR_d1 = zext_ln302_fu_1289_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        LAR_d1 = zext_ln300_fu_1001_p1;
    end else begin
        LAR_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        LAR_we0 = 1'b1;
    end else begin
        LAR_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        LAR_we1 = 1'b1;
    end else begin
        LAR_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LAR_addr_1_reg_1430 = 64'd1;

assign LAR_addr_2_reg_1445 = 64'd2;

assign LAR_addr_3_reg_1450 = 64'd3;

assign LAR_addr_4_reg_1470 = 64'd4;

assign LAR_addr_5_reg_1475 = 64'd5;

assign LAR_addr_6_reg_1505 = 64'd6;

assign LAR_addr_7_reg_1510 = 64'd7;

assign LAR_addr_reg_1425 = 64'd0;

assign add_ln300_fu_309_p2 = (temp_13_fu_279_p3 + 7'd32);

assign add_ln301_fu_443_p2 = (temp_15_fu_413_p3 + 7'd32);

assign add_ln302_fu_615_p2 = (temp_18_fu_585_p3 + 7'd16);

assign add_ln303_fu_775_p2 = (temp_21_fu_747_p3 + 7'd16);

assign add_ln305_fu_1037_p2 = (temp_24_fu_1009_p3 + 7'd8);

assign add_ln306_fu_1093_p2 = (temp_27_fu_1065_p3 + 7'd8);

assign add_ln307_fu_1325_p2 = (temp_30_fu_1297_p3 + 7'd4);

assign add_ln308_fu_1381_p2 = (temp_33_fu_1353_p3 + 7'd4);

assign add_ln48_1_fu_361_p2 = ($signed(sext_ln48_2_fu_345_p1) + $signed(sext_ln48_3_fu_357_p1));

assign add_ln48_2_fu_495_p2 = ($signed(sext_ln48_4_fu_479_p1) + $signed(sext_ln48_5_fu_491_p1));

assign add_ln48_3_fu_667_p2 = ($signed(sext_ln48_6_fu_651_p1) + $signed(sext_ln48_7_fu_663_p1));

assign add_ln48_fu_227_p2 = ($signed(sext_ln48_fu_211_p1) + $signed(sext_ln48_1_fu_223_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign icmp_ln300_1_fu_303_p2 = (($signed(temp_13_fu_279_p3) < $signed(7'd96)) ? 1'b1 : 1'b0);

assign icmp_ln300_fu_297_p2 = ((tmp_10_fu_287_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln301_1_fu_437_p2 = (($signed(temp_15_fu_413_p3) < $signed(7'd96)) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_431_p2 = ((tmp_12_fu_421_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln302_1_fu_609_p2 = (($signed(temp_18_fu_585_p3) < $signed(7'd112)) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_603_p2 = (($signed(tmp_15_fu_593_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln303_1_fu_769_p2 = (($signed(temp_21_fu_747_p3) < $signed(7'd112)) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_763_p2 = (($signed(tmp_17_fu_753_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln305_1_fu_1031_p2 = (($signed(temp_24_fu_1009_p3) < $signed(7'd120)) ? 1'b1 : 1'b0);

assign icmp_ln305_fu_1025_p2 = (($signed(tmp_20_fu_1015_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln306_1_fu_1087_p2 = (($signed(temp_27_fu_1065_p3) < $signed(7'd120)) ? 1'b1 : 1'b0);

assign icmp_ln306_fu_1081_p2 = (($signed(tmp_22_fu_1071_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln307_1_fu_1319_p2 = (($signed(temp_30_fu_1297_p3) < $signed(7'd124)) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_1313_p2 = (($signed(tmp_24_fu_1303_p4) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln308_1_fu_1375_p2 = (($signed(temp_33_fu_1353_p3) < $signed(7'd124)) ? 1'b1 : 1'b0);

assign icmp_ln308_fu_1369_p2 = (($signed(tmp_26_fu_1359_p4) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln39_10_fu_843_p2 = ((tmp_18_fu_833_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_11_fu_881_p2 = ((tmp_19_fu_871_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_12_fu_947_p2 = (($signed(sum_9_fu_941_p2) < $signed(17'd98304)) ? 1'b1 : 1'b0);

assign icmp_ln39_13_fu_985_p2 = ((tmp_21_fu_975_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_14_fu_1151_p2 = (($signed(sum_11_fu_1145_p2) < $signed(17'd98304)) ? 1'b1 : 1'b0);

assign icmp_ln39_15_fu_1189_p2 = ((tmp_23_fu_1179_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_16_fu_1235_p2 = (($signed(sum_13_fu_1229_p2) < $signed(17'd98304)) ? 1'b1 : 1'b0);

assign icmp_ln39_17_fu_1273_p2 = ((tmp_25_fu_1263_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_5_fu_397_p2 = ((tmp_11_fu_387_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_6_fu_531_p2 = ((tmp_13_fu_521_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_7_fu_569_p2 = ((tmp_14_fu_559_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_8_fu_693_p2 = (($signed(sum_5_fu_687_p2) < $signed(17'd98304)) ? 1'b1 : 1'b0);

assign icmp_ln39_9_fu_731_p2 = ((tmp_16_fu_721_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_263_p2 = ((tmp_9_fu_253_p4 == 2'd1) ? 1'b1 : 1'b0);

assign mul_ln48_1_fu_1125_p1 = 31'd8534;

assign mul_ln48_2_fu_1209_p1 = 31'd9036;

assign mul_ln48_fu_807_p1 = 31'd13964;

assign or_ln300_fu_323_p2 = (icmp_ln300_fu_297_p2 | icmp_ln300_1_fu_303_p2);

assign or_ln301_fu_457_p2 = (icmp_ln301_fu_431_p2 | icmp_ln301_1_fu_437_p2);

assign or_ln302_fu_629_p2 = (icmp_ln302_fu_603_p2 | icmp_ln302_1_fu_609_p2);

assign or_ln303_fu_789_p2 = (icmp_ln303_fu_763_p2 | icmp_ln303_1_fu_769_p2);

assign or_ln305_fu_1051_p2 = (icmp_ln305_fu_1025_p2 | icmp_ln305_1_fu_1031_p2);

assign or_ln306_fu_1107_p2 = (icmp_ln306_fu_1081_p2 | icmp_ln306_1_fu_1087_p2);

assign or_ln307_fu_1339_p2 = (icmp_ln307_fu_1313_p2 | icmp_ln307_1_fu_1319_p2);

assign or_ln308_fu_1395_p2 = (icmp_ln308_fu_1369_p2 | icmp_ln308_1_fu_1375_p2);

assign select_ln300_1_fu_329_p3 = ((or_ln300_fu_323_p2[0:0] == 1'b1) ? select_ln300_fu_315_p3 : add_ln300_fu_309_p2);

assign select_ln300_fu_315_p3 = ((icmp_ln300_fu_297_p2[0:0] == 1'b1) ? 7'd63 : 7'd0);

assign select_ln301_1_fu_463_p3 = ((or_ln301_fu_457_p2[0:0] == 1'b1) ? select_ln301_fu_449_p3 : add_ln301_fu_443_p2);

assign select_ln301_fu_449_p3 = ((icmp_ln301_fu_431_p2[0:0] == 1'b1) ? 7'd63 : 7'd0);

assign select_ln302_1_fu_635_p3 = ((or_ln302_fu_629_p2[0:0] == 1'b1) ? select_ln302_fu_621_p3 : add_ln302_fu_615_p2);

assign select_ln302_fu_621_p3 = ((icmp_ln302_fu_603_p2[0:0] == 1'b1) ? 7'd31 : 7'd0);

assign select_ln303_1_fu_795_p3 = ((or_ln303_fu_789_p2[0:0] == 1'b1) ? select_ln303_fu_781_p3 : add_ln303_fu_775_p2);

assign select_ln303_fu_781_p3 = ((icmp_ln303_fu_763_p2[0:0] == 1'b1) ? 7'd31 : 7'd0);

assign select_ln305_1_fu_1057_p3 = ((or_ln305_fu_1051_p2[0:0] == 1'b1) ? select_ln305_fu_1043_p3 : add_ln305_fu_1037_p2);

assign select_ln305_fu_1043_p3 = ((icmp_ln305_fu_1025_p2[0:0] == 1'b1) ? 7'd15 : 7'd0);

assign select_ln306_1_fu_1113_p3 = ((or_ln306_fu_1107_p2[0:0] == 1'b1) ? select_ln306_fu_1099_p3 : add_ln306_fu_1093_p2);

assign select_ln306_fu_1099_p3 = ((icmp_ln306_fu_1081_p2[0:0] == 1'b1) ? 7'd15 : 7'd0);

assign select_ln307_1_fu_1345_p3 = ((or_ln307_fu_1339_p2[0:0] == 1'b1) ? select_ln307_fu_1331_p3 : add_ln307_fu_1325_p2);

assign select_ln307_fu_1331_p3 = ((icmp_ln307_fu_1313_p2[0:0] == 1'b1) ? 7'd7 : 7'd0);

assign select_ln308_1_fu_1401_p3 = ((or_ln308_fu_1395_p2[0:0] == 1'b1) ? select_ln308_fu_1387_p3 : add_ln308_fu_1381_p2);

assign select_ln308_fu_1387_p3 = ((icmp_ln308_fu_1369_p2[0:0] == 1'b1) ? 7'd7 : 7'd0);

assign sext_ln38_10_fu_937_p1 = $signed(temp_25_fu_927_p4);

assign sext_ln38_11_fu_965_p1 = $signed(temp_26_fu_957_p3);

assign sext_ln38_12_fu_1141_p1 = $signed(temp_28_fu_1131_p4);

assign sext_ln38_13_fu_1169_p1 = $signed(temp_29_fu_1161_p3);

assign sext_ln38_14_fu_1225_p1 = $signed(temp_31_fu_1215_p4);

assign sext_ln38_15_fu_1253_p1 = $signed(temp_32_fu_1245_p3);

assign sext_ln38_3_fu_377_p1 = $signed(temp_14_fu_367_p4);

assign sext_ln38_4_fu_511_p1 = $signed(temp_16_fu_501_p4);

assign sext_ln38_5_fu_549_p1 = $signed(temp_17_fu_541_p3);

assign sext_ln38_6_fu_683_p1 = $signed(temp_19_fu_673_p4);

assign sext_ln38_7_fu_711_p1 = $signed(temp_20_fu_703_p3);

assign sext_ln38_8_fu_823_p1 = $signed(temp_22_fu_813_p4);

assign sext_ln38_9_fu_861_p1 = $signed(temp_23_fu_853_p3);

assign sext_ln38_fu_243_p1 = $signed(temp_fu_233_p4);

assign sext_ln48_10_fu_917_p1 = $signed(shl_ln48_9_fu_909_p3);

assign sext_ln48_1_fu_223_p1 = $signed(shl_ln48_1_fu_215_p3);

assign sext_ln48_2_fu_345_p1 = $signed(shl_ln48_2_fu_337_p3);

assign sext_ln48_3_fu_357_p1 = $signed(shl_ln48_3_fu_349_p3);

assign sext_ln48_4_fu_479_p1 = $signed(shl_ln48_4_fu_471_p3);

assign sext_ln48_5_fu_491_p1 = $signed(shl_ln48_5_fu_483_p3);

assign sext_ln48_6_fu_651_p1 = $signed(shl_ln48_6_fu_643_p3);

assign sext_ln48_7_fu_663_p1 = $signed(shl_ln48_7_fu_655_p3);

assign sext_ln48_9_fu_905_p1 = $signed(shl_ln48_8_fu_897_p3);

assign sext_ln48_fu_211_p1 = $signed(shl_ln_fu_203_p3);

assign shl_ln48_1_fu_215_p3 = {{LAR_q1}, {12'd0}};

assign shl_ln48_2_fu_337_p3 = {{LAR_q0}, {14'd0}};

assign shl_ln48_3_fu_349_p3 = {{LAR_q0}, {12'd0}};

assign shl_ln48_4_fu_471_p3 = {{LAR_q1}, {14'd0}};

assign shl_ln48_5_fu_483_p3 = {{LAR_q1}, {12'd0}};

assign shl_ln48_6_fu_643_p3 = {{LAR_q0}, {14'd0}};

assign shl_ln48_7_fu_655_p3 = {{LAR_q0}, {12'd0}};

assign shl_ln48_8_fu_897_p3 = {{LAR_q0}, {14'd0}};

assign shl_ln48_9_fu_909_p3 = {{LAR_q0}, {10'd0}};

assign shl_ln_fu_203_p3 = {{LAR_q1}, {14'd0}};

assign sub_ln48_fu_921_p2 = ($signed(sext_ln48_9_fu_905_p1) - $signed(sext_ln48_10_fu_917_p1));

assign sum_10_fu_969_p2 = ($signed(sext_ln38_11_fu_965_p1) + $signed(17'd256));

assign sum_11_fu_1145_p2 = ($signed(sext_ln38_12_fu_1141_p1) + $signed(17'd130731));

assign sum_12_fu_1173_p2 = ($signed(sext_ln38_13_fu_1169_p1) + $signed(17'd256));

assign sum_13_fu_1229_p2 = ($signed(sext_ln38_14_fu_1225_p1) + $signed(17'd129928));

assign sum_14_fu_1257_p2 = ($signed(sext_ln38_15_fu_1253_p1) + $signed(17'd256));

assign sum_2_fu_381_p2 = ($signed(sext_ln38_3_fu_377_p1) + $signed(17'd256));

assign sum_3_fu_515_p2 = ($signed(sext_ln38_4_fu_511_p1) + $signed(17'd2048));

assign sum_4_fu_553_p2 = ($signed(sext_ln38_5_fu_549_p1) + $signed(17'd256));

assign sum_5_fu_687_p2 = ($signed(sext_ln38_6_fu_683_p1) + $signed(17'd128512));

assign sum_6_fu_715_p2 = ($signed(sext_ln38_7_fu_711_p1) + $signed(17'd256));

assign sum_7_fu_827_p2 = ($signed(sext_ln38_8_fu_823_p1) + $signed(17'd94));

assign sum_8_fu_865_p2 = ($signed(sext_ln38_9_fu_861_p1) + $signed(17'd256));

assign sum_9_fu_941_p2 = ($signed(sext_ln38_10_fu_937_p1) + $signed(17'd129280));

assign sum_fu_247_p2 = ($signed(sext_ln38_fu_243_p1) + $signed(17'd256));

assign temp_13_fu_279_p3 = ((icmp_ln39_fu_263_p2[0:0] == 1'b1) ? 7'd63 : tmp_fu_269_p4);

assign temp_14_fu_367_p4 = {{add_ln48_1_fu_361_p2[30:15]}};

assign temp_15_fu_413_p3 = ((icmp_ln39_5_fu_397_p2[0:0] == 1'b1) ? 7'd63 : tmp_2_fu_403_p4);

assign temp_16_fu_501_p4 = {{add_ln48_2_fu_495_p2[30:15]}};

assign temp_17_fu_541_p3 = ((icmp_ln39_6_fu_531_p2[0:0] == 1'b1) ? 16'd32767 : trunc_ln39_fu_537_p1);

assign temp_18_fu_585_p3 = ((icmp_ln39_7_fu_569_p2[0:0] == 1'b1) ? 7'd63 : tmp_3_fu_575_p4);

assign temp_19_fu_673_p4 = {{add_ln48_3_fu_667_p2[30:15]}};

assign temp_20_fu_703_p3 = ((icmp_ln39_8_fu_693_p2[0:0] == 1'b1) ? 16'd32768 : trunc_ln39_1_fu_699_p1);

assign temp_21_fu_747_p3 = ((icmp_ln39_9_reg_1460[0:0] == 1'b1) ? 7'd63 : tmp_4_reg_1465);

assign temp_22_fu_813_p4 = {{mul_ln48_fu_807_p2[30:15]}};

assign temp_23_fu_853_p3 = ((icmp_ln39_10_fu_843_p2[0:0] == 1'b1) ? 16'd32767 : trunc_ln39_2_fu_849_p1);

assign temp_24_fu_1009_p3 = ((icmp_ln39_11_reg_1485[0:0] == 1'b1) ? 7'd63 : tmp_5_reg_1490);

assign temp_25_fu_927_p4 = {{sub_ln48_fu_921_p2[30:15]}};

assign temp_26_fu_957_p3 = ((icmp_ln39_12_fu_947_p2[0:0] == 1'b1) ? 16'd32768 : trunc_ln39_3_fu_953_p1);

assign temp_27_fu_1065_p3 = ((icmp_ln39_13_reg_1495[0:0] == 1'b1) ? 7'd63 : tmp_6_reg_1500);

assign temp_28_fu_1131_p4 = {{mul_ln48_1_fu_1125_p2[30:15]}};

assign temp_29_fu_1161_p3 = ((icmp_ln39_14_fu_1151_p2[0:0] == 1'b1) ? 16'd32768 : trunc_ln39_4_fu_1157_p1);

assign temp_30_fu_1297_p3 = ((icmp_ln39_15_reg_1525[0:0] == 1'b1) ? 7'd63 : tmp_7_reg_1530);

assign temp_31_fu_1215_p4 = {{mul_ln48_2_fu_1209_p2[30:15]}};

assign temp_32_fu_1245_p3 = ((icmp_ln39_16_fu_1235_p2[0:0] == 1'b1) ? 16'd32768 : trunc_ln39_5_fu_1241_p1);

assign temp_33_fu_1353_p3 = ((icmp_ln39_17_reg_1535[0:0] == 1'b1) ? 7'd63 : tmp_8_reg_1540);

assign temp_fu_233_p4 = {{add_ln48_fu_227_p2[30:15]}};

assign tmp_10_fu_287_p4 = {{temp_13_fu_279_p3[6:5]}};

assign tmp_11_fu_387_p4 = {{sum_2_fu_381_p2[16:15]}};

assign tmp_12_fu_421_p4 = {{temp_15_fu_413_p3[6:5]}};

assign tmp_13_fu_521_p4 = {{sum_3_fu_515_p2[16:15]}};

assign tmp_14_fu_559_p4 = {{sum_4_fu_553_p2[16:15]}};

assign tmp_15_fu_593_p4 = {{temp_18_fu_585_p3[6:4]}};

assign tmp_16_fu_721_p4 = {{sum_6_fu_715_p2[16:15]}};

assign tmp_17_fu_753_p4 = {{temp_21_fu_747_p3[6:4]}};

assign tmp_18_fu_833_p4 = {{sum_7_fu_827_p2[16:15]}};

assign tmp_19_fu_871_p4 = {{sum_8_fu_865_p2[16:15]}};

assign tmp_20_fu_1015_p4 = {{temp_24_fu_1009_p3[6:3]}};

assign tmp_21_fu_975_p4 = {{sum_10_fu_969_p2[16:15]}};

assign tmp_22_fu_1071_p4 = {{temp_27_fu_1065_p3[6:3]}};

assign tmp_23_fu_1179_p4 = {{sum_12_fu_1173_p2[16:15]}};

assign tmp_24_fu_1303_p4 = {{temp_30_fu_1297_p3[6:2]}};

assign tmp_25_fu_1263_p4 = {{sum_14_fu_1257_p2[16:15]}};

assign tmp_26_fu_1359_p4 = {{temp_33_fu_1353_p3[6:2]}};

assign tmp_2_fu_403_p4 = {{sum_2_fu_381_p2[15:9]}};

assign tmp_3_fu_575_p4 = {{sum_4_fu_553_p2[15:9]}};

assign tmp_9_fu_253_p4 = {{sum_fu_247_p2[16:15]}};

assign tmp_fu_269_p4 = {{sum_fu_247_p2[15:9]}};

assign trunc_ln39_1_fu_699_p1 = sum_5_fu_687_p2[15:0];

assign trunc_ln39_2_fu_849_p1 = sum_7_fu_827_p2[15:0];

assign trunc_ln39_3_fu_953_p1 = sum_9_fu_941_p2[15:0];

assign trunc_ln39_4_fu_1157_p1 = sum_11_fu_1145_p2[15:0];

assign trunc_ln39_5_fu_1241_p1 = sum_13_fu_1229_p2[15:0];

assign trunc_ln39_fu_537_p1 = sum_3_fu_515_p2[15:0];

assign zext_ln300_fu_1001_p1 = select_ln300_1_reg_1435;

assign zext_ln301_fu_1005_p1 = select_ln301_1_reg_1440;

assign zext_ln302_fu_1289_p1 = select_ln302_1_reg_1455;

assign zext_ln303_fu_1293_p1 = select_ln303_1_reg_1480;

assign zext_ln305_fu_1409_p1 = select_ln305_1_reg_1515;

assign zext_ln306_fu_1413_p1 = select_ln306_1_reg_1520;

assign zext_ln307_fu_1417_p1 = select_ln307_1_reg_1545;

assign zext_ln308_fu_1421_p1 = select_ln308_1_reg_1550;

endmodule //main_Quantization_and_coding
