// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_Autocorrelation_Pipeline_VITIS_LOOP_134_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        L_ACF_load_8,
        add_ln132,
        add_ln131,
        add_ln130,
        add_ln129,
        add_ln128,
        add_ln127,
        add_ln126,
        add_ln125,
        s_0_address0,
        s_0_ce0,
        s_0_q0,
        s_1_address0,
        s_1_ce0,
        s_1_q0,
        s_2_address0,
        s_2_ce0,
        s_2_q0,
        s_3_address0,
        s_3_ce0,
        s_3_q0,
        s_4_address0,
        s_4_ce0,
        s_4_q0,
        s_5_address0,
        s_5_ce0,
        s_5_q0,
        s_6_address0,
        s_6_ce0,
        s_6_q0,
        s_7_address0,
        s_7_ce0,
        s_7_q0,
        s_8_address0,
        s_8_ce0,
        s_8_q0,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] L_ACF_load_8;
input  [63:0] add_ln132;
input  [63:0] add_ln131;
input  [63:0] add_ln130;
input  [63:0] add_ln129;
input  [63:0] add_ln128;
input  [63:0] add_ln127;
input  [63:0] add_ln126;
input  [63:0] add_ln125;
output  [4:0] s_0_address0;
output   s_0_ce0;
input  [15:0] s_0_q0;
output  [4:0] s_1_address0;
output   s_1_ce0;
input  [15:0] s_1_q0;
output  [4:0] s_2_address0;
output   s_2_ce0;
input  [15:0] s_2_q0;
output  [4:0] s_3_address0;
output   s_3_ce0;
input  [15:0] s_3_q0;
output  [4:0] s_4_address0;
output   s_4_ce0;
input  [15:0] s_4_q0;
output  [4:0] s_5_address0;
output   s_5_ce0;
input  [15:0] s_5_q0;
output  [4:0] s_6_address0;
output   s_6_ce0;
input  [15:0] s_6_q0;
output  [4:0] s_7_address0;
output   s_7_ce0;
input  [15:0] s_7_q0;
output  [4:0] s_8_address0;
output   s_8_ce0;
input  [15:0] s_8_q0;
output  [63:0] p_out;
output   p_out_ap_vld;
output  [63:0] p_out1;
output   p_out1_ap_vld;
output  [63:0] p_out2;
output   p_out2_ap_vld;
output  [63:0] p_out3;
output   p_out3_ap_vld;
output  [63:0] p_out4;
output   p_out4_ap_vld;
output  [63:0] p_out5;
output   p_out5_ap_vld;
output  [63:0] p_out6;
output   p_out6_ap_vld;
output  [63:0] p_out7;
output   p_out7_ap_vld;
output  [63:0] p_out8;
output   p_out8_ap_vld;

reg ap_idle;
reg[4:0] s_0_address0;
reg s_0_ce0;
reg[4:0] s_1_address0;
reg s_1_ce0;
reg[4:0] s_2_address0;
reg s_2_ce0;
reg[4:0] s_3_address0;
reg s_3_ce0;
reg[4:0] s_4_address0;
reg s_4_ce0;
reg[4:0] s_5_address0;
reg s_5_ce0;
reg[4:0] s_6_address0;
reg s_6_ce0;
reg[4:0] s_7_address0;
reg s_7_ce0;
reg[4:0] s_8_address0;
reg s_8_ce0;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln134_fu_1062_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln134_reg_2243;
wire   [3:0] trunc_ln51_fu_1091_p1;
reg   [3:0] trunc_ln51_reg_2247;
reg   [3:0] trunc_ln51_reg_2247_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln51_1_fu_1214_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln137_fu_1247_p1;
wire   [63:0] zext_ln141_fu_1280_p1;
wire   [63:0] zext_ln142_fu_1313_p1;
wire   [63:0] zext_ln143_fu_1346_p1;
wire   [63:0] zext_ln144_fu_1379_p1;
wire   [63:0] zext_ln145_fu_1412_p1;
wire   [63:0] zext_ln146_fu_1445_p1;
wire   [63:0] zext_ln51_fu_1139_p1;
reg   [7:0] phi_urem46_fu_132;
wire   [7:0] select_ln51_fu_1083_p3;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_phi_urem46_load;
reg   [16:0] phi_mul44_fu_136;
wire   [16:0] add_ln51_9_fu_1123_p2;
reg   [7:0] idx_fu_140;
wire   [7:0] add_ln51_fu_1114_p2;
reg   [7:0] i_fu_144;
wire   [7:0] i_9_fu_1095_p2;
reg   [7:0] ap_sig_allocacmp_i_8;
reg   [63:0] empty_fu_148;
wire   [63:0] add_ln139_fu_1552_p2;
reg   [63:0] empty_104_fu_152;
wire   [63:0] add_ln140_fu_1615_p2;
reg   [63:0] empty_105_fu_156;
wire   [63:0] add_ln141_fu_1678_p2;
reg   [63:0] empty_106_fu_160;
wire   [63:0] add_ln142_fu_1741_p2;
reg   [63:0] empty_107_fu_164;
wire   [63:0] add_ln143_fu_1804_p2;
reg   [63:0] empty_108_fu_168;
wire   [63:0] add_ln144_fu_1867_p2;
reg   [63:0] empty_109_fu_172;
wire   [63:0] add_ln145_fu_1930_p2;
reg   [63:0] empty_110_fu_176;
wire   [63:0] add_ln146_fu_1993_p2;
reg   [63:0] empty_111_fu_180;
wire   [63:0] add_ln147_fu_2056_p2;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] add_ln51_8_fu_1071_p2;
wire   [0:0] icmp_ln51_fu_1077_p2;
wire   [4:0] tmp_fu_1129_p4;
wire   [7:0] add_ln51_6_fu_1182_p2;
wire   [7:0] mul_ln51_fu_1198_p0;
wire   [9:0] mul_ln51_fu_1198_p1;
wire   [16:0] mul_ln51_fu_1198_p2;
wire   [4:0] tmp_28_fu_1204_p4;
wire   [7:0] add_ln51_7_fu_1188_p2;
wire   [7:0] mul_ln137_fu_1231_p0;
wire   [9:0] mul_ln137_fu_1231_p1;
wire   [16:0] mul_ln137_fu_1231_p2;
wire   [4:0] tmp_29_fu_1237_p4;
wire   [7:0] add_ln51_5_fu_1176_p2;
wire   [7:0] mul_ln141_1_fu_1264_p0;
wire   [9:0] mul_ln141_1_fu_1264_p1;
wire   [16:0] mul_ln141_1_fu_1264_p2;
wire   [4:0] tmp_30_fu_1270_p4;
wire   [7:0] add_ln51_4_fu_1170_p2;
wire   [7:0] mul_ln142_1_fu_1297_p0;
wire   [9:0] mul_ln142_1_fu_1297_p1;
wire   [16:0] mul_ln142_1_fu_1297_p2;
wire   [4:0] tmp_31_fu_1303_p4;
wire   [7:0] add_ln51_3_fu_1164_p2;
wire   [7:0] mul_ln143_1_fu_1330_p0;
wire   [9:0] mul_ln143_1_fu_1330_p1;
wire   [16:0] mul_ln143_1_fu_1330_p2;
wire   [4:0] tmp_32_fu_1336_p4;
wire   [7:0] add_ln51_2_fu_1158_p2;
wire   [7:0] mul_ln144_1_fu_1363_p0;
wire   [9:0] mul_ln144_1_fu_1363_p1;
wire   [16:0] mul_ln144_1_fu_1363_p2;
wire   [4:0] tmp_33_fu_1369_p4;
wire   [7:0] add_ln51_1_fu_1152_p2;
wire   [7:0] mul_ln145_1_fu_1396_p0;
wire   [9:0] mul_ln145_1_fu_1396_p1;
wire   [16:0] mul_ln145_1_fu_1396_p2;
wire   [4:0] tmp_34_fu_1402_p4;
wire   [7:0] mul_ln146_1_fu_1429_p0;
wire   [9:0] mul_ln146_1_fu_1429_p1;
wire   [16:0] mul_ln146_1_fu_1429_p2;
wire   [4:0] tmp_35_fu_1435_p4;
wire   [15:0] sl_fu_1495_p19;
wire   [15:0] sl_fu_1495_p21;
wire  signed [15:0] mul_ln139_fu_1542_p0;
wire  signed [31:0] sext_ln139_fu_1538_p1;
wire  signed [15:0] mul_ln139_fu_1542_p1;
wire   [31:0] mul_ln139_fu_1542_p2;
wire  signed [63:0] sext_ln139_1_fu_1548_p1;
wire   [15:0] tmp_4_fu_1558_p19;
wire  signed [15:0] tmp_4_fu_1558_p21;
wire  signed [15:0] mul_ln140_fu_1605_p1;
wire   [31:0] mul_ln140_fu_1605_p2;
wire  signed [63:0] sext_ln140_1_fu_1611_p1;
wire   [15:0] tmp_5_fu_1621_p19;
wire  signed [15:0] tmp_5_fu_1621_p21;
wire  signed [15:0] mul_ln141_fu_1668_p1;
wire   [31:0] mul_ln141_fu_1668_p2;
wire  signed [63:0] sext_ln141_1_fu_1674_p1;
wire   [15:0] tmp_6_fu_1684_p19;
wire  signed [15:0] tmp_6_fu_1684_p21;
wire  signed [15:0] mul_ln142_fu_1731_p1;
wire   [31:0] mul_ln142_fu_1731_p2;
wire  signed [63:0] sext_ln142_1_fu_1737_p1;
wire   [15:0] tmp_7_fu_1747_p19;
wire  signed [15:0] tmp_7_fu_1747_p21;
wire  signed [15:0] mul_ln143_fu_1794_p1;
wire   [31:0] mul_ln143_fu_1794_p2;
wire  signed [63:0] sext_ln143_1_fu_1800_p1;
wire   [15:0] tmp_8_fu_1810_p19;
wire  signed [15:0] tmp_8_fu_1810_p21;
wire  signed [15:0] mul_ln144_fu_1857_p1;
wire   [31:0] mul_ln144_fu_1857_p2;
wire  signed [63:0] sext_ln144_1_fu_1863_p1;
wire   [15:0] tmp_9_fu_1873_p19;
wire  signed [15:0] tmp_9_fu_1873_p21;
wire  signed [15:0] mul_ln145_fu_1920_p1;
wire   [31:0] mul_ln145_fu_1920_p2;
wire  signed [63:0] sext_ln145_1_fu_1926_p1;
wire   [15:0] tmp_s_fu_1936_p19;
wire  signed [15:0] tmp_s_fu_1936_p21;
wire  signed [15:0] mul_ln146_fu_1983_p1;
wire   [31:0] mul_ln146_fu_1983_p2;
wire  signed [63:0] sext_ln146_1_fu_1989_p1;
wire   [15:0] tmp_1_fu_1999_p19;
wire  signed [15:0] tmp_1_fu_1999_p21;
wire  signed [15:0] mul_ln147_fu_2046_p1;
wire   [31:0] mul_ln147_fu_2046_p2;
wire  signed [63:0] sext_ln147_1_fu_2052_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [16:0] mul_ln137_fu_1231_p00;
wire   [16:0] mul_ln141_1_fu_1264_p00;
wire   [16:0] mul_ln142_1_fu_1297_p00;
wire   [16:0] mul_ln143_1_fu_1330_p00;
wire   [16:0] mul_ln144_1_fu_1363_p00;
wire   [16:0] mul_ln145_1_fu_1396_p00;
wire   [16:0] mul_ln146_1_fu_1429_p00;
wire   [16:0] mul_ln51_fu_1198_p00;
reg    ap_condition_407;
wire   [3:0] sl_fu_1495_p1;
wire   [3:0] sl_fu_1495_p3;
wire   [3:0] sl_fu_1495_p5;
wire   [3:0] sl_fu_1495_p7;
wire   [3:0] sl_fu_1495_p9;
wire   [3:0] sl_fu_1495_p11;
wire   [3:0] sl_fu_1495_p13;
wire  signed [3:0] sl_fu_1495_p15;
wire   [3:0] sl_fu_1495_p17;
wire   [3:0] tmp_4_fu_1558_p1;
wire   [3:0] tmp_4_fu_1558_p3;
wire   [3:0] tmp_4_fu_1558_p5;
wire   [3:0] tmp_4_fu_1558_p7;
wire   [3:0] tmp_4_fu_1558_p9;
wire   [3:0] tmp_4_fu_1558_p11;
wire  signed [3:0] tmp_4_fu_1558_p13;
wire   [3:0] tmp_4_fu_1558_p15;
wire   [3:0] tmp_4_fu_1558_p17;
wire   [3:0] tmp_5_fu_1621_p1;
wire   [3:0] tmp_5_fu_1621_p3;
wire   [3:0] tmp_5_fu_1621_p5;
wire   [3:0] tmp_5_fu_1621_p7;
wire   [3:0] tmp_5_fu_1621_p9;
wire  signed [3:0] tmp_5_fu_1621_p11;
wire   [3:0] tmp_5_fu_1621_p13;
wire   [3:0] tmp_5_fu_1621_p15;
wire   [3:0] tmp_5_fu_1621_p17;
wire   [3:0] tmp_6_fu_1684_p1;
wire   [3:0] tmp_6_fu_1684_p3;
wire   [3:0] tmp_6_fu_1684_p5;
wire   [3:0] tmp_6_fu_1684_p7;
wire  signed [3:0] tmp_6_fu_1684_p9;
wire   [3:0] tmp_6_fu_1684_p11;
wire   [3:0] tmp_6_fu_1684_p13;
wire   [3:0] tmp_6_fu_1684_p15;
wire   [3:0] tmp_6_fu_1684_p17;
wire   [3:0] tmp_7_fu_1747_p1;
wire   [3:0] tmp_7_fu_1747_p3;
wire   [3:0] tmp_7_fu_1747_p5;
wire  signed [3:0] tmp_7_fu_1747_p7;
wire   [3:0] tmp_7_fu_1747_p9;
wire   [3:0] tmp_7_fu_1747_p11;
wire   [3:0] tmp_7_fu_1747_p13;
wire   [3:0] tmp_7_fu_1747_p15;
wire   [3:0] tmp_7_fu_1747_p17;
wire   [3:0] tmp_8_fu_1810_p1;
wire   [3:0] tmp_8_fu_1810_p3;
wire  signed [3:0] tmp_8_fu_1810_p5;
wire   [3:0] tmp_8_fu_1810_p7;
wire   [3:0] tmp_8_fu_1810_p9;
wire   [3:0] tmp_8_fu_1810_p11;
wire   [3:0] tmp_8_fu_1810_p13;
wire   [3:0] tmp_8_fu_1810_p15;
wire   [3:0] tmp_8_fu_1810_p17;
wire   [3:0] tmp_9_fu_1873_p1;
wire  signed [3:0] tmp_9_fu_1873_p3;
wire   [3:0] tmp_9_fu_1873_p5;
wire   [3:0] tmp_9_fu_1873_p7;
wire   [3:0] tmp_9_fu_1873_p9;
wire   [3:0] tmp_9_fu_1873_p11;
wire   [3:0] tmp_9_fu_1873_p13;
wire   [3:0] tmp_9_fu_1873_p15;
wire   [3:0] tmp_9_fu_1873_p17;
wire  signed [3:0] tmp_s_fu_1936_p1;
wire   [3:0] tmp_s_fu_1936_p3;
wire   [3:0] tmp_s_fu_1936_p5;
wire   [3:0] tmp_s_fu_1936_p7;
wire   [3:0] tmp_s_fu_1936_p9;
wire   [3:0] tmp_s_fu_1936_p11;
wire   [3:0] tmp_s_fu_1936_p13;
wire   [3:0] tmp_s_fu_1936_p15;
wire   [3:0] tmp_s_fu_1936_p17;
wire   [3:0] tmp_1_fu_1999_p1;
wire   [3:0] tmp_1_fu_1999_p3;
wire   [3:0] tmp_1_fu_1999_p5;
wire   [3:0] tmp_1_fu_1999_p7;
wire   [3:0] tmp_1_fu_1999_p9;
wire   [3:0] tmp_1_fu_1999_p11;
wire   [3:0] tmp_1_fu_1999_p13;
wire   [3:0] tmp_1_fu_1999_p15;
wire  signed [3:0] tmp_1_fu_1999_p17;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 phi_urem46_fu_132 = 8'd0;
#0 phi_mul44_fu_136 = 17'd0;
#0 idx_fu_140 = 8'd0;
#0 i_fu_144 = 8'd0;
#0 empty_fu_148 = 64'd0;
#0 empty_104_fu_152 = 64'd0;
#0 empty_105_fu_156 = 64'd0;
#0 empty_106_fu_160 = 64'd0;
#0 empty_107_fu_164 = 64'd0;
#0 empty_108_fu_168 = 64'd0;
#0 empty_109_fu_172 = 64'd0;
#0 empty_110_fu_176 = 64'd0;
#0 empty_111_fu_180 = 64'd0;
#0 ap_done_reg = 1'b0;
end

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U37(
    .din0(mul_ln51_fu_1198_p0),
    .din1(mul_ln51_fu_1198_p1),
    .dout(mul_ln51_fu_1198_p2)
);

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U38(
    .din0(mul_ln137_fu_1231_p0),
    .din1(mul_ln137_fu_1231_p1),
    .dout(mul_ln137_fu_1231_p2)
);

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U39(
    .din0(mul_ln141_1_fu_1264_p0),
    .din1(mul_ln141_1_fu_1264_p1),
    .dout(mul_ln141_1_fu_1264_p2)
);

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U40(
    .din0(mul_ln142_1_fu_1297_p0),
    .din1(mul_ln142_1_fu_1297_p1),
    .dout(mul_ln142_1_fu_1297_p2)
);

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U41(
    .din0(mul_ln143_1_fu_1330_p0),
    .din1(mul_ln143_1_fu_1330_p1),
    .dout(mul_ln143_1_fu_1330_p2)
);

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U42(
    .din0(mul_ln144_1_fu_1363_p0),
    .din1(mul_ln144_1_fu_1363_p1),
    .dout(mul_ln144_1_fu_1363_p2)
);

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U43(
    .din0(mul_ln145_1_fu_1396_p0),
    .din1(mul_ln145_1_fu_1396_p1),
    .dout(mul_ln145_1_fu_1396_p2)
);

main_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U44(
    .din0(mul_ln146_1_fu_1429_p0),
    .din1(mul_ln146_1_fu_1429_p1),
    .dout(mul_ln146_1_fu_1429_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h4 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h5 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h6 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h7 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h8 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h0 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U45(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(sl_fu_1495_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(sl_fu_1495_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U46(
    .din0(mul_ln139_fu_1542_p0),
    .din1(mul_ln139_fu_1542_p1),
    .dout(mul_ln139_fu_1542_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h3 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h4 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h5 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h6 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h7 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h8 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h0 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h1 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U47(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_4_fu_1558_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_4_fu_1558_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U48(
    .din0(tmp_4_fu_1558_p21),
    .din1(mul_ln140_fu_1605_p1),
    .dout(mul_ln140_fu_1605_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h3 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h4 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h5 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h6 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h7 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h8 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h0 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h1 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h2 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U49(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_5_fu_1621_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_5_fu_1621_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U50(
    .din0(tmp_5_fu_1621_p21),
    .din1(mul_ln141_fu_1668_p1),
    .dout(mul_ln141_fu_1668_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h5 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h6 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h7 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h8 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h0 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h1 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h2 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h3 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U51(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_6_fu_1684_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_6_fu_1684_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U52(
    .din0(tmp_6_fu_1684_p21),
    .din1(mul_ln142_fu_1731_p1),
    .dout(mul_ln142_fu_1731_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h5 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h6 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h7 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h8 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h0 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h1 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h2 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h3 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h4 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U53(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_7_fu_1747_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_7_fu_1747_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U54(
    .din0(tmp_7_fu_1747_p21),
    .din1(mul_ln143_fu_1794_p1),
    .dout(mul_ln143_fu_1794_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h6 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h7 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h8 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h0 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h1 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h2 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h3 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h4 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h5 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U55(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_8_fu_1810_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_8_fu_1810_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U56(
    .din0(tmp_8_fu_1810_p21),
    .din1(mul_ln144_fu_1857_p1),
    .dout(mul_ln144_fu_1857_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h7 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h8 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h0 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h1 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h2 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h3 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h4 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h5 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h6 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U57(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_9_fu_1873_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_9_fu_1873_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U58(
    .din0(tmp_9_fu_1873_p21),
    .din1(mul_ln145_fu_1920_p1),
    .dout(mul_ln145_fu_1920_p2)
);

main_sparsemux_19_4_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h8 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h2 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h3 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h4 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h5 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h6 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h7 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_x_U59(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_s_fu_1936_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_s_fu_1936_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U60(
    .din0(tmp_s_fu_1936_p21),
    .din1(mul_ln146_fu_1983_p1),
    .dout(mul_ln146_fu_1983_p2)
);

main_sparsemux_19_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_U61(
    .din0(s_0_q0),
    .din1(s_1_q0),
    .din2(s_2_q0),
    .din3(s_3_q0),
    .din4(s_4_q0),
    .din5(s_5_q0),
    .din6(s_6_q0),
    .din7(s_7_q0),
    .din8(s_8_q0),
    .def(tmp_1_fu_1999_p19),
    .sel(trunc_ln51_reg_2247_pp0_iter1_reg),
    .dout(tmp_1_fu_1999_p21)
);

main_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U62(
    .din0(tmp_1_fu_1999_p21),
    .din1(mul_ln147_fu_2046_p1),
    .dout(mul_ln147_fu_2046_p2)
);

main_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_104_fu_152 <= add_ln126;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_104_fu_152 <= add_ln140_fu_1615_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_105_fu_156 <= add_ln127;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_105_fu_156 <= add_ln141_fu_1678_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_106_fu_160 <= add_ln128;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_106_fu_160 <= add_ln142_fu_1741_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_107_fu_164 <= add_ln129;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_107_fu_164 <= add_ln143_fu_1804_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_108_fu_168 <= add_ln130;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_108_fu_168 <= add_ln144_fu_1867_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_109_fu_172 <= add_ln131;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_109_fu_172 <= add_ln145_fu_1930_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_110_fu_176 <= add_ln132;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_110_fu_176 <= add_ln146_fu_1993_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_111_fu_180 <= L_ACF_load_8;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_111_fu_180 <= add_ln147_fu_2056_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_fu_148 <= add_ln125;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_fu_148 <= add_ln139_fu_1552_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln134_fu_1062_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_144 <= i_9_fu_1095_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_144 <= 8'd8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_fu_140 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln134_reg_2243 == 1'd0))) begin
            idx_fu_140 <= add_ln51_fu_1114_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul44_fu_136 <= 17'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln134_reg_2243 == 1'd0))) begin
            phi_mul44_fu_136 <= add_ln51_9_fu_1123_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln134_fu_1062_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem46_fu_132 <= select_ln51_fu_1083_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem46_fu_132 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln134_reg_2243 <= icmp_ln134_fu_1062_p2;
        trunc_ln51_reg_2247 <= trunc_ln51_fu_1091_p1;
        trunc_ln51_reg_2247_pp0_iter1_reg <= trunc_ln51_reg_2247;
    end
end

always @ (*) begin
    if (((icmp_ln134_fu_1062_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_8 = 8'd8;
    end else begin
        ap_sig_allocacmp_i_8 = i_fu_144;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem46_load = 8'd0;
    end else begin
        ap_sig_allocacmp_phi_urem46_load = phi_urem46_fu_132;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_0_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_0_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_0_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_0_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_0_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_0_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_0_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_0_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_0_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_0_address0 = 'bx;
        end
    end else begin
        s_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_0_ce0 = 1'b1;
    end else begin
        s_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_1_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_1_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_1_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_1_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_1_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_1_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_1_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_1_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_1_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_1_address0 = 'bx;
        end
    end else begin
        s_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_1_ce0 = 1'b1;
    end else begin
        s_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_2_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_2_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_2_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_2_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_2_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_2_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_2_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_2_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_2_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_2_address0 = 'bx;
        end
    end else begin
        s_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_2_ce0 = 1'b1;
    end else begin
        s_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_3_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_3_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_3_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_3_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_3_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_3_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_3_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_3_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_3_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_3_address0 = 'bx;
        end
    end else begin
        s_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_3_ce0 = 1'b1;
    end else begin
        s_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_4_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_4_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_4_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_4_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_4_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_4_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_4_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_4_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_4_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_4_address0 = 'bx;
        end
    end else begin
        s_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_4_ce0 = 1'b1;
    end else begin
        s_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_5_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_5_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_5_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_5_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_5_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_5_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_5_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_5_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_5_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_5_address0 = 'bx;
        end
    end else begin
        s_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_5_ce0 = 1'b1;
    end else begin
        s_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_6_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_6_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_6_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_6_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_6_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_6_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_6_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_6_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_6_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_6_address0 = 'bx;
        end
    end else begin
        s_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_6_ce0 = 1'b1;
    end else begin
        s_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_7_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_7_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_7_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_7_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_7_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_7_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_7_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_7_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_7_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_7_address0 = 'bx;
        end
    end else begin
        s_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_7_ce0 = 1'b1;
    end else begin
        s_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_407)) begin
        if ((trunc_ln51_reg_2247 == 4'd8)) begin
            s_8_address0 = zext_ln51_fu_1139_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd7)) begin
            s_8_address0 = zext_ln146_fu_1445_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd6)) begin
            s_8_address0 = zext_ln145_fu_1412_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd5)) begin
            s_8_address0 = zext_ln144_fu_1379_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd4)) begin
            s_8_address0 = zext_ln143_fu_1346_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd3)) begin
            s_8_address0 = zext_ln142_fu_1313_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd2)) begin
            s_8_address0 = zext_ln141_fu_1280_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd1)) begin
            s_8_address0 = zext_ln51_1_fu_1214_p1;
        end else if ((trunc_ln51_reg_2247 == 4'd0)) begin
            s_8_address0 = zext_ln137_fu_1247_p1;
        end else begin
            s_8_address0 = 'bx;
        end
    end else begin
        s_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd1) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd0) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd8) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd7) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd6) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd5) & (icmp_ln134_reg_2243 
    == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd4) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd3) & (icmp_ln134_reg_2243 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln51_reg_2247 == 4'd2) & (icmp_ln134_reg_2243 == 1'd0)))) begin
        s_8_ce0 = 1'b1;
    end else begin
        s_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln139_fu_1552_p2 = ($signed(sext_ln139_1_fu_1548_p1) + $signed(empty_fu_148));

assign add_ln140_fu_1615_p2 = ($signed(sext_ln140_1_fu_1611_p1) + $signed(empty_104_fu_152));

assign add_ln141_fu_1678_p2 = ($signed(sext_ln141_1_fu_1674_p1) + $signed(empty_105_fu_156));

assign add_ln142_fu_1741_p2 = ($signed(sext_ln142_1_fu_1737_p1) + $signed(empty_106_fu_160));

assign add_ln143_fu_1804_p2 = ($signed(sext_ln143_1_fu_1800_p1) + $signed(empty_107_fu_164));

assign add_ln144_fu_1867_p2 = ($signed(sext_ln144_1_fu_1863_p1) + $signed(empty_108_fu_168));

assign add_ln145_fu_1930_p2 = ($signed(sext_ln145_1_fu_1926_p1) + $signed(empty_109_fu_172));

assign add_ln146_fu_1993_p2 = ($signed(sext_ln146_1_fu_1989_p1) + $signed(empty_110_fu_176));

assign add_ln147_fu_2056_p2 = ($signed(sext_ln147_1_fu_2052_p1) + $signed(empty_111_fu_180));

assign add_ln51_1_fu_1152_p2 = (idx_fu_140 + 8'd2);

assign add_ln51_2_fu_1158_p2 = (idx_fu_140 + 8'd3);

assign add_ln51_3_fu_1164_p2 = (idx_fu_140 + 8'd4);

assign add_ln51_4_fu_1170_p2 = (idx_fu_140 + 8'd5);

assign add_ln51_5_fu_1176_p2 = (idx_fu_140 + 8'd6);

assign add_ln51_6_fu_1182_p2 = (idx_fu_140 + 8'd7);

assign add_ln51_7_fu_1188_p2 = (idx_fu_140 + 8'd8);

assign add_ln51_8_fu_1071_p2 = (ap_sig_allocacmp_phi_urem46_load + 8'd1);

assign add_ln51_9_fu_1123_p2 = (phi_mul44_fu_136 + 17'd456);

assign add_ln51_fu_1114_p2 = (idx_fu_140 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_407 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln134_reg_2243 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_9_fu_1095_p2 = (ap_sig_allocacmp_i_8 + 8'd1);

assign icmp_ln134_fu_1062_p2 = ((ap_sig_allocacmp_i_8 == 8'd160) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_1077_p2 = ((add_ln51_8_fu_1071_p2 < 8'd9) ? 1'b1 : 1'b0);

assign mul_ln137_fu_1231_p0 = mul_ln137_fu_1231_p00;

assign mul_ln137_fu_1231_p00 = add_ln51_7_fu_1188_p2;

assign mul_ln137_fu_1231_p1 = 17'd456;

assign mul_ln139_fu_1542_p0 = sext_ln139_fu_1538_p1;

assign mul_ln139_fu_1542_p1 = sext_ln139_fu_1538_p1;

assign mul_ln140_fu_1605_p1 = sext_ln139_fu_1538_p1;

assign mul_ln141_1_fu_1264_p0 = mul_ln141_1_fu_1264_p00;

assign mul_ln141_1_fu_1264_p00 = add_ln51_5_fu_1176_p2;

assign mul_ln141_1_fu_1264_p1 = 17'd456;

assign mul_ln141_fu_1668_p1 = sext_ln139_fu_1538_p1;

assign mul_ln142_1_fu_1297_p0 = mul_ln142_1_fu_1297_p00;

assign mul_ln142_1_fu_1297_p00 = add_ln51_4_fu_1170_p2;

assign mul_ln142_1_fu_1297_p1 = 17'd456;

assign mul_ln142_fu_1731_p1 = sext_ln139_fu_1538_p1;

assign mul_ln143_1_fu_1330_p0 = mul_ln143_1_fu_1330_p00;

assign mul_ln143_1_fu_1330_p00 = add_ln51_3_fu_1164_p2;

assign mul_ln143_1_fu_1330_p1 = 17'd456;

assign mul_ln143_fu_1794_p1 = sext_ln139_fu_1538_p1;

assign mul_ln144_1_fu_1363_p0 = mul_ln144_1_fu_1363_p00;

assign mul_ln144_1_fu_1363_p00 = add_ln51_2_fu_1158_p2;

assign mul_ln144_1_fu_1363_p1 = 17'd456;

assign mul_ln144_fu_1857_p1 = sext_ln139_fu_1538_p1;

assign mul_ln145_1_fu_1396_p0 = mul_ln145_1_fu_1396_p00;

assign mul_ln145_1_fu_1396_p00 = add_ln51_1_fu_1152_p2;

assign mul_ln145_1_fu_1396_p1 = 17'd456;

assign mul_ln145_fu_1920_p1 = sext_ln139_fu_1538_p1;

assign mul_ln146_1_fu_1429_p0 = mul_ln146_1_fu_1429_p00;

assign mul_ln146_1_fu_1429_p00 = add_ln51_fu_1114_p2;

assign mul_ln146_1_fu_1429_p1 = 17'd456;

assign mul_ln146_fu_1983_p1 = sext_ln139_fu_1538_p1;

assign mul_ln147_fu_2046_p1 = sext_ln139_fu_1538_p1;

assign mul_ln51_fu_1198_p0 = mul_ln51_fu_1198_p00;

assign mul_ln51_fu_1198_p00 = add_ln51_6_fu_1182_p2;

assign mul_ln51_fu_1198_p1 = 17'd456;

assign p_out = empty_111_fu_180;

assign p_out1 = empty_110_fu_176;

assign p_out2 = empty_109_fu_172;

assign p_out3 = empty_108_fu_168;

assign p_out4 = empty_107_fu_164;

assign p_out5 = empty_106_fu_160;

assign p_out6 = empty_105_fu_156;

assign p_out7 = empty_104_fu_152;

assign p_out8 = empty_fu_148;

assign select_ln51_fu_1083_p3 = ((icmp_ln51_fu_1077_p2[0:0] == 1'b1) ? add_ln51_8_fu_1071_p2 : 8'd0);

assign sext_ln139_1_fu_1548_p1 = $signed(mul_ln139_fu_1542_p2);

assign sext_ln139_fu_1538_p1 = $signed(sl_fu_1495_p21);

assign sext_ln140_1_fu_1611_p1 = $signed(mul_ln140_fu_1605_p2);

assign sext_ln141_1_fu_1674_p1 = $signed(mul_ln141_fu_1668_p2);

assign sext_ln142_1_fu_1737_p1 = $signed(mul_ln142_fu_1731_p2);

assign sext_ln143_1_fu_1800_p1 = $signed(mul_ln143_fu_1794_p2);

assign sext_ln144_1_fu_1863_p1 = $signed(mul_ln144_fu_1857_p2);

assign sext_ln145_1_fu_1926_p1 = $signed(mul_ln145_fu_1920_p2);

assign sext_ln146_1_fu_1989_p1 = $signed(mul_ln146_fu_1983_p2);

assign sext_ln147_1_fu_2052_p1 = $signed(mul_ln147_fu_2046_p2);

assign sl_fu_1495_p19 = 'bx;

assign tmp_1_fu_1999_p19 = 'bx;

assign tmp_28_fu_1204_p4 = {{mul_ln51_fu_1198_p2[16:12]}};

assign tmp_29_fu_1237_p4 = {{mul_ln137_fu_1231_p2[16:12]}};

assign tmp_30_fu_1270_p4 = {{mul_ln141_1_fu_1264_p2[16:12]}};

assign tmp_31_fu_1303_p4 = {{mul_ln142_1_fu_1297_p2[16:12]}};

assign tmp_32_fu_1336_p4 = {{mul_ln143_1_fu_1330_p2[16:12]}};

assign tmp_33_fu_1369_p4 = {{mul_ln144_1_fu_1363_p2[16:12]}};

assign tmp_34_fu_1402_p4 = {{mul_ln145_1_fu_1396_p2[16:12]}};

assign tmp_35_fu_1435_p4 = {{mul_ln146_1_fu_1429_p2[16:12]}};

assign tmp_4_fu_1558_p19 = 'bx;

assign tmp_5_fu_1621_p19 = 'bx;

assign tmp_6_fu_1684_p19 = 'bx;

assign tmp_7_fu_1747_p19 = 'bx;

assign tmp_8_fu_1810_p19 = 'bx;

assign tmp_9_fu_1873_p19 = 'bx;

assign tmp_fu_1129_p4 = {{phi_mul44_fu_136[16:12]}};

assign tmp_s_fu_1936_p19 = 'bx;

assign trunc_ln51_fu_1091_p1 = ap_sig_allocacmp_phi_urem46_load[3:0];

assign zext_ln137_fu_1247_p1 = tmp_29_fu_1237_p4;

assign zext_ln141_fu_1280_p1 = tmp_30_fu_1270_p4;

assign zext_ln142_fu_1313_p1 = tmp_31_fu_1303_p4;

assign zext_ln143_fu_1346_p1 = tmp_32_fu_1336_p4;

assign zext_ln144_fu_1379_p1 = tmp_33_fu_1369_p4;

assign zext_ln145_fu_1412_p1 = tmp_34_fu_1402_p4;

assign zext_ln146_fu_1445_p1 = tmp_35_fu_1435_p4;

assign zext_ln51_1_fu_1214_p1 = tmp_28_fu_1204_p4;

assign zext_ln51_fu_1139_p1 = tmp_fu_1129_p4;

endmodule //main_Autocorrelation_Pipeline_VITIS_LOOP_134_4
