// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_blowfish_main_Pipeline_VITIS_LOOP_110_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ukey_address0,
        ukey_ce0,
        ukey_q0,
        ukey_address1,
        ukey_ce1,
        ukey_q1,
        ukey_address2,
        ukey_ce2,
        ukey_q2,
        ukey_address3,
        ukey_ce3,
        ukey_q3,
        key_P_address0,
        key_P_ce0,
        key_P_we0,
        key_P_d0,
        key_P_address1,
        key_P_ce1,
        key_P_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] ukey_address0;
output   ukey_ce0;
input  [0:0] ukey_q0;
output  [2:0] ukey_address1;
output   ukey_ce1;
input  [0:0] ukey_q1;
output  [2:0] ukey_address2;
output   ukey_ce2;
input  [0:0] ukey_q2;
output  [2:0] ukey_address3;
output   ukey_ce3;
input  [0:0] ukey_q3;
output  [4:0] key_P_address0;
output   key_P_ce0;
output   key_P_we0;
output  [63:0] key_P_d0;
output  [4:0] key_P_address1;
output   key_P_ce1;
input  [63:0] key_P_q1;

reg ap_idle;
reg ukey_ce0;
reg ukey_ce1;
reg ukey_ce2;
reg ukey_ce3;
reg key_P_ce0;
reg key_P_we0;
reg key_P_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln110_fu_127_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] key_P_addr_reg_369;
wire   [63:0] zext_ln110_fu_142_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln99_fu_182_p1;
wire   [63:0] zext_ln99_2_fu_217_p1;
wire   [63:0] zext_ln99_4_fu_252_p1;
wire   [63:0] zext_ln110_1_fu_147_p1;
reg   [2:0] d_fu_40;
wire   [2:0] d_8_fu_279_p3;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_d_load;
reg   [4:0] i_1_fu_44;
wire   [4:0] add_ln110_fu_133_p2;
reg   [4:0] ap_sig_allocacmp_i;
wire   [3:0] zext_ln110_2_fu_152_p1;
wire   [3:0] d_1_fu_156_p2;
wire   [0:0] tmp_fu_166_p3;
wire   [2:0] trunc_ln99_fu_162_p1;
wire   [2:0] d_2_fu_174_p3;
wire   [3:0] zext_ln99_1_fu_187_p1;
wire   [3:0] d_3_fu_191_p2;
wire   [0:0] tmp_1_fu_201_p3;
wire   [2:0] trunc_ln99_1_fu_197_p1;
wire   [2:0] d_4_fu_209_p3;
wire   [3:0] zext_ln99_3_fu_222_p1;
wire   [3:0] d_5_fu_226_p2;
wire   [0:0] tmp_2_fu_236_p3;
wire   [2:0] trunc_ln99_2_fu_232_p1;
wire   [2:0] d_6_fu_244_p3;
wire   [3:0] zext_ln99_5_fu_257_p1;
wire   [3:0] d_7_fu_261_p2;
wire   [0:0] tmp_3_fu_271_p3;
wire   [2:0] trunc_ln99_3_fu_267_p1;
wire   [7:0] zext_ln118_fu_297_p1;
wire   [7:0] zext_ln123_fu_301_p1;
wire   [7:0] zext_ln127_fu_305_p1;
wire   [24:0] ri_fu_309_p5;
wire   [63:0] zext_ln127_1_fu_321_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 d_fu_40 = 3'd0;
#0 i_1_fu_44 = 5'd0;
#0 ap_done_reg = 1'b0;
end

main_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln110_fu_127_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            d_fu_40 <= d_8_fu_279_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            d_fu_40 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln110_fu_127_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_44 <= add_ln110_fu_133_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_44 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        key_P_addr_reg_369 <= zext_ln110_1_fu_147_p1;
    end
end

always @ (*) begin
    if (((icmp_ln110_fu_127_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_d_load = 3'd0;
    end else begin
        ap_sig_allocacmp_d_load = d_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 5'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        key_P_ce0 = 1'b1;
    end else begin
        key_P_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        key_P_ce1 = 1'b1;
    end else begin
        key_P_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        key_P_we0 = 1'b1;
    end else begin
        key_P_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ukey_ce0 = 1'b1;
    end else begin
        ukey_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ukey_ce1 = 1'b1;
    end else begin
        ukey_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ukey_ce2 = 1'b1;
    end else begin
        ukey_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ukey_ce3 = 1'b1;
    end else begin
        ukey_ce3 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln110_fu_133_p2 = (ap_sig_allocacmp_i + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign d_1_fu_156_p2 = (zext_ln110_2_fu_152_p1 + 4'd1);

assign d_2_fu_174_p3 = ((tmp_fu_166_p3[0:0] == 1'b1) ? 3'd0 : trunc_ln99_fu_162_p1);

assign d_3_fu_191_p2 = (zext_ln99_1_fu_187_p1 + 4'd1);

assign d_4_fu_209_p3 = ((tmp_1_fu_201_p3[0:0] == 1'b1) ? 3'd0 : trunc_ln99_1_fu_197_p1);

assign d_5_fu_226_p2 = (zext_ln99_3_fu_222_p1 + 4'd1);

assign d_6_fu_244_p3 = ((tmp_2_fu_236_p3[0:0] == 1'b1) ? 3'd0 : trunc_ln99_2_fu_232_p1);

assign d_7_fu_261_p2 = (zext_ln99_5_fu_257_p1 + 4'd1);

assign d_8_fu_279_p3 = ((tmp_3_fu_271_p3[0:0] == 1'b1) ? 3'd0 : trunc_ln99_3_fu_267_p1);

assign icmp_ln110_fu_127_p2 = ((ap_sig_allocacmp_i == 5'd18) ? 1'b1 : 1'b0);

assign key_P_address0 = key_P_addr_reg_369;

assign key_P_address1 = zext_ln110_1_fu_147_p1;

assign key_P_d0 = (zext_ln127_1_fu_321_p1 ^ key_P_q1);

assign ri_fu_309_p5 = {{{{ukey_q3}, {zext_ln118_fu_297_p1}}, {zext_ln123_fu_301_p1}}, {zext_ln127_fu_305_p1}};

assign tmp_1_fu_201_p3 = d_3_fu_191_p2[32'd3];

assign tmp_2_fu_236_p3 = d_5_fu_226_p2[32'd3];

assign tmp_3_fu_271_p3 = d_7_fu_261_p2[32'd3];

assign tmp_fu_166_p3 = d_1_fu_156_p2[32'd3];

assign trunc_ln99_1_fu_197_p1 = d_3_fu_191_p2[2:0];

assign trunc_ln99_2_fu_232_p1 = d_5_fu_226_p2[2:0];

assign trunc_ln99_3_fu_267_p1 = d_7_fu_261_p2[2:0];

assign trunc_ln99_fu_162_p1 = d_1_fu_156_p2[2:0];

assign ukey_address0 = zext_ln99_4_fu_252_p1;

assign ukey_address1 = zext_ln99_2_fu_217_p1;

assign ukey_address2 = zext_ln99_fu_182_p1;

assign ukey_address3 = zext_ln110_fu_142_p1;

assign zext_ln110_1_fu_147_p1 = ap_sig_allocacmp_i;

assign zext_ln110_2_fu_152_p1 = ap_sig_allocacmp_d_load;

assign zext_ln110_fu_142_p1 = ap_sig_allocacmp_d_load;

assign zext_ln118_fu_297_p1 = ukey_q2;

assign zext_ln123_fu_301_p1 = ukey_q1;

assign zext_ln127_1_fu_321_p1 = ri_fu_309_p5;

assign zext_ln127_fu_305_p1 = ukey_q0;

assign zext_ln99_1_fu_187_p1 = d_2_fu_174_p3;

assign zext_ln99_2_fu_217_p1 = d_4_fu_209_p3;

assign zext_ln99_3_fu_222_p1 = d_4_fu_209_p3;

assign zext_ln99_4_fu_252_p1 = d_6_fu_244_p3;

assign zext_ln99_5_fu_257_p1 = d_6_fu_244_p3;

assign zext_ln99_fu_182_p1 = d_2_fu_174_p3;

endmodule //main_blowfish_main_Pipeline_VITIS_LOOP_110_1
