// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_blowfish_main (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_return
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] key_P_address0;
reg    key_P_ce0;
reg    key_P_we0;
reg   [63:0] key_P_d0;
wire   [63:0] key_P_q0;
reg   [4:0] key_P_address1;
reg    key_P_ce1;
reg    key_P_we1;
wire   [63:0] key_P_q1;
reg   [9:0] key_S_address0;
reg    key_S_ce0;
reg    key_S_we0;
reg   [31:0] key_S_d0;
wire   [31:0] key_S_q0;
reg   [9:0] key_S_address1;
reg    key_S_ce1;
reg    key_S_we1;
wire   [31:0] key_S_q1;
wire   [31:0] empty_fu_232_p1;
reg   [31:0] empty_reg_409;
wire    ap_CS_fsm_state9;
wire  signed [6:0] umax_fu_270_p3;
reg  signed [6:0] umax_reg_414;
wire  signed [6:0] l_1_fu_278_p2;
reg   [6:0] l_1_reg_421;
wire   [31:0] sub_ln845_fu_291_p2;
reg   [31:0] sub_ln845_reg_429;
wire    ap_CS_fsm_state10;
wire  signed [31:0] sext_ln845_fu_296_p1;
reg  signed [31:0] sext_ln845_reg_434;
wire   [0:0] icmp_ln101_fu_299_p2;
reg   [0:0] icmp_ln101_reg_439;
reg   [31:0] l_load_reg_446;
wire    ap_CS_fsm_state13;
reg   [2:0] ukey_address0;
reg    ukey_ce0;
reg    ukey_we0;
wire   [0:0] ukey_q0;
reg    ukey_ce1;
wire   [0:0] ukey_q1;
reg    ukey_ce2;
wire   [0:0] ukey_q2;
reg    ukey_ce3;
wire   [0:0] ukey_q3;
reg   [5:0] indata_address0;
reg    indata_ce0;
reg    indata_we0;
wire   [6:0] indata_q0;
reg   [5:0] outdata_address0;
reg    outdata_ce0;
reg    outdata_we0;
wire   [7:0] outdata_q0;
reg   [2:0] ivec_address0;
reg    ivec_ce0;
reg    ivec_we0;
reg   [7:0] ivec_d0;
wire   [7:0] ivec_q0;
reg    ivec_ce1;
reg    ivec_we1;
wire   [7:0] ivec_q1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_ready;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_we0;
wire   [0:0] grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_d0;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_we0;
wire   [7:0] grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_d0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_ready;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_we0;
wire   [63:0] grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_d0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_ready;
wire   [9:0] grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_we0;
wire   [31:0] grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_d0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_ready;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce0;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce1;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address2;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce2;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address3;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce3;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_we0;
wire   [63:0] grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_d0;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_ce1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_ready;
wire   [33:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_0_0_out;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_0_0_out_ap_vld;
wire   [33:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_1_0_out;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_1_0_out_ap_vld;
wire   [9:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_ce0;
wire   [9:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_ce1;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_we0;
wire   [63:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_d0;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_ce1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_we1;
wire   [63:0] grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_d1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_ready;
wire   [9:0] grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_we0;
wire   [31:0] grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_d0;
wire   [9:0] grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_ce1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_we1;
wire   [31:0] grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_d1;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_ce0;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_ce1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_ready;
wire   [5:0] grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_we0;
wire   [6:0] grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_d0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_ready;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_we0;
wire   [7:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_d0;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_ce1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_we1;
wire   [7:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_d1;
wire   [5:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_ce0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_we0;
wire   [7:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_d0;
wire   [5:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_indata_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_indata_ce0;
wire   [2:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_zext_ln83_out;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_zext_ln83_out_ap_vld;
wire   [9:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_ce0;
wire   [9:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_ce1;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_ce0;
wire   [4:0] grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_address1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_ce1;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_done;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_idle;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_ready;
wire   [5:0] grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_outdata_address0;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_outdata_ce0;
wire   [31:0] grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_check_1_out_o;
wire    grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_check_1_out_o_ap_vld;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start_reg;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start_reg;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start_reg;
wire   [0:0] icmp_ln840_fu_212_p2;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg   [2:0] zext_ln83_loc_fu_68;
reg    grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start_reg;
wire    ap_CS_fsm_state14;
reg   [31:0] check_fu_60;
reg   [31:0] k_fu_52;
reg   [31:0] l_fu_56;
wire   [31:0] select_ln840_fu_334_p3;
reg   [31:0] n_fu_64;
wire   [31:0] zext_ln83_reload_cast_fu_311_p1;
wire  signed [31:0] icmp_ln840_fu_212_p0;
wire  signed [31:0] trunc_ln842_fu_218_p0;
wire  signed [31:0] sext_ln842_fu_222_p0;
wire  signed [32:0] sext_ln842_fu_222_p1;
wire   [32:0] add_ln842_fu_226_p2;
wire  signed [31:0] empty_25_fu_236_p0;
wire   [0:0] empty_25_fu_236_p2;
wire   [12:0] trunc_ln842_fu_218_p1;
wire   [12:0] smax_fu_242_p3;
wire   [32:0] zext_ln842_fu_250_p1;
wire   [32:0] sub_ln842_fu_254_p2;
wire   [0:0] empty_27_fu_264_p2;
wire   [6:0] empty_26_fu_260_p1;
wire  signed [31:0] sext_ln842_1_fu_288_p1;
wire   [0:0] icmp_ln847_fu_324_p2;
wire   [31:0] add_ln840_fu_329_p2;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start_reg = 1'b0;
#0 grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start_reg = 1'b0;
#0 check_fu_60 = 32'd0;
#0 k_fu_52 = 32'd0;
#0 l_fu_56 = 32'd0;
#0 n_fu_64 = 32'd0;
end

main_blowfish_main_key_P_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 18 ),
    .AddressWidth( 5 ))
key_P_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(key_P_address0),
    .ce0(key_P_ce0),
    .we0(key_P_we0),
    .d0(key_P_d0),
    .q0(key_P_q0),
    .address1(key_P_address1),
    .ce1(key_P_ce1),
    .we1(key_P_we1),
    .d1(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_d1),
    .q1(key_P_q1)
);

main_blowfish_main_key_S_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
key_S_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(key_S_address0),
    .ce0(key_S_ce0),
    .we0(key_S_we0),
    .d0(key_S_d0),
    .q0(key_S_q0),
    .address1(key_S_address1),
    .ce1(key_S_ce1),
    .we1(key_S_we1),
    .d1(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_d1),
    .q1(key_S_q1)
);

main_blowfish_main_ukey_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
ukey_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ukey_address0),
    .ce0(ukey_ce0),
    .we0(ukey_we0),
    .d0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_d0),
    .q0(ukey_q0),
    .address1(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address1),
    .ce1(ukey_ce1),
    .q1(ukey_q1),
    .address2(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address2),
    .ce2(ukey_ce2),
    .q2(ukey_q2),
    .address3(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address3),
    .ce3(ukey_ce3),
    .q3(ukey_q3)
);

main_blowfish_main_indata_RAM_AUTO_1R1W #(
    .DataWidth( 7 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
indata_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(indata_address0),
    .ce0(indata_ce0),
    .we0(indata_we0),
    .d0(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_d0),
    .q0(indata_q0)
);

main_blowfish_main_outdata_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
outdata_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outdata_address0),
    .ce0(outdata_ce0),
    .we0(outdata_we0),
    .d0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_d0),
    .q0(outdata_q0)
);

main_blowfish_main_ivec_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
ivec_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ivec_address0),
    .ce0(ivec_ce0),
    .we0(ivec_we0),
    .d0(ivec_d0),
    .q0(ivec_q0),
    .address1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_address1),
    .ce1(ivec_ce1),
    .we1(ivec_we1),
    .d1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_d1),
    .q1(ivec_q1)
);

main_blowfish_main_Pipeline_VITIS_LOOP_833_1 grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_ready),
    .ukey_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_address0),
    .ukey_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_ce0),
    .ukey_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_we0),
    .ukey_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_d0),
    .ivec_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_address0),
    .ivec_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_ce0),
    .ivec_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_we0),
    .ivec_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_d0)
);

main_blowfish_main_Pipeline_VITIS_LOOP_86_1 grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_ready),
    .key_P_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_address0),
    .key_P_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_ce0),
    .key_P_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_we0),
    .key_P_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_d0)
);

main_blowfish_main_Pipeline_VITIS_LOOP_86_11 grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_ready),
    .key_S_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_address0),
    .key_S_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_ce0),
    .key_S_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_we0),
    .key_S_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_d0)
);

main_blowfish_main_Pipeline_VITIS_LOOP_110_1 grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_ready),
    .ukey_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address0),
    .ukey_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce0),
    .ukey_q0(ukey_q0),
    .ukey_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address1),
    .ukey_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce1),
    .ukey_q1(ukey_q1),
    .ukey_address2(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address2),
    .ukey_ce2(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce2),
    .ukey_q2(ukey_q2),
    .ukey_address3(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address3),
    .ukey_ce3(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce3),
    .ukey_q3(ukey_q3),
    .key_P_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_address0),
    .key_P_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_ce0),
    .key_P_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_we0),
    .key_P_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_d0),
    .key_P_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_address1),
    .key_P_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_ce1),
    .key_P_q1(key_P_q1)
);

main_blowfish_main_Pipeline_VITIS_LOOP_136_2 grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_ready),
    .in_0_0_out(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_0_0_out),
    .in_0_0_out_ap_vld(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_0_0_out_ap_vld),
    .in_1_0_out(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_1_0_out),
    .in_1_0_out_ap_vld(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_1_0_out_ap_vld),
    .key_S_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_address0),
    .key_S_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_ce0),
    .key_S_q0(key_S_q0),
    .key_S_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_address1),
    .key_S_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_ce1),
    .key_S_q1(key_S_q1),
    .key_P_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_address0),
    .key_P_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_ce0),
    .key_P_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_we0),
    .key_P_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_d0),
    .key_P_q0(key_P_q0),
    .key_P_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_address1),
    .key_P_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_ce1),
    .key_P_we1(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_we1),
    .key_P_d1(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_d1),
    .key_P_q1(key_P_q1)
);

main_blowfish_main_Pipeline_VITIS_LOOP_144_3 grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_ready),
    .in_0_0_reload(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_0_0_out),
    .in_1_0_reload(grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_in_1_0_out),
    .key_S_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_address0),
    .key_S_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_ce0),
    .key_S_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_we0),
    .key_S_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_d0),
    .key_S_q0(key_S_q0),
    .key_S_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_address1),
    .key_S_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_ce1),
    .key_S_we1(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_we1),
    .key_S_d1(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_d1),
    .key_S_q1(key_S_q1),
    .key_P_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_address0),
    .key_P_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_ce0),
    .key_P_q0(key_P_q0),
    .key_P_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_address1),
    .key_P_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_ce1),
    .key_P_q1(key_P_q1)
);

main_blowfish_main_Pipeline_VITIS_LOOP_842_3 grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_ready),
    .sext_ln842(k_fu_52),
    .sext_ln842_3(l_1_reg_421),
    .indata_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_address0),
    .indata_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_ce0),
    .indata_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_we0),
    .indata_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_d0)
);

main_blowfish_main_Pipeline_VITIS_LOOP_101_1 grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_ready),
    .sext_ln842_3(l_1_reg_421),
    .num_2(n_fu_64),
    .ivec_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_address0),
    .ivec_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_ce0),
    .ivec_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_we0),
    .ivec_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_d0),
    .ivec_q0(ivec_q0),
    .ivec_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_address1),
    .ivec_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_ce1),
    .ivec_we1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_we1),
    .ivec_d1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_d1),
    .ivec_q1(ivec_q1),
    .outdata_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_address0),
    .outdata_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_ce0),
    .outdata_we0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_we0),
    .outdata_d0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_d0),
    .indata_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_indata_address0),
    .indata_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_indata_ce0),
    .indata_q0(indata_q0),
    .zext_ln83_out(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_zext_ln83_out),
    .zext_ln83_out_ap_vld(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_zext_ln83_out_ap_vld),
    .key_S_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_address0),
    .key_S_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_ce0),
    .key_S_q0(key_S_q0),
    .key_S_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_address1),
    .key_S_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_ce1),
    .key_S_q1(key_S_q1),
    .key_P_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_address0),
    .key_P_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_ce0),
    .key_P_q0(key_P_q0),
    .key_P_address1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_address1),
    .key_P_ce1(grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_ce1),
    .key_P_q1(key_P_q1)
);

main_blowfish_main_Pipeline_VITIS_LOOP_847_4 grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start),
    .ap_done(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_done),
    .ap_idle(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_idle),
    .ap_ready(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_ready),
    .sext_ln847(l_load_reg_446),
    .l_1(l_1_reg_421),
    .outdata_address0(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_outdata_address0),
    .outdata_ce0(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_outdata_ce0),
    .outdata_q0(outdata_q0),
    .check_1_out_i(check_fu_60),
    .check_1_out_o(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_check_1_out_o),
    .check_1_out_o_ap_vld(grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_check_1_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln840_fu_212_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_ready == 1'b1)) begin
            grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        check_fu_60 <= 32'd0;
    end else if (((grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_check_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        check_fu_60 <= grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_check_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_fu_52 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        k_fu_52 <= sub_ln845_reg_429;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        l_fu_56 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        l_fu_56 <= select_ln840_fu_334_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                n_fu_64[0] <= 1'b0;
        n_fu_64[1] <= 1'b0;
        n_fu_64[2] <= 1'b0;
    end else if (((icmp_ln101_reg_439 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
                n_fu_64[2 : 0] <= zext_ln83_reload_cast_fu_311_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        empty_reg_409 <= empty_fu_232_p1;
        l_1_reg_421 <= l_1_fu_278_p2;
        umax_reg_414 <= umax_fu_270_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        icmp_ln101_reg_439 <= icmp_ln101_fu_299_p2;
        sext_ln845_reg_434 <= sext_ln845_fu_296_p1;
        sub_ln845_reg_429 <= sub_ln845_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        l_load_reg_446 <= l_fu_56;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_zext_ln83_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        zext_ln83_loc_fu_68 <= grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_zext_ln83_out;
    end
end

always @ (*) begin
    if ((grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln840_fu_212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln840_fu_212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        indata_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_indata_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        indata_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_address0;
    end else begin
        indata_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        indata_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_indata_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        indata_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_ce0;
    end else begin
        indata_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        indata_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_indata_we0;
    end else begin
        indata_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ivec_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ivec_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_address0;
    end else begin
        ivec_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ivec_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ivec_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_ce0;
    end else begin
        ivec_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ivec_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_ce1;
    end else begin
        ivec_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ivec_d0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ivec_d0 = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_d0;
    end else begin
        ivec_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ivec_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ivec_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ivec_we0;
    end else begin
        ivec_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ivec_we1 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ivec_we1;
    end else begin
        ivec_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_P_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_P_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_P_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_P_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_P_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_address0;
    end else begin
        key_P_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_P_address1 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_P_address1 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_P_address1 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_P_address1 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_address1;
    end else begin
        key_P_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_P_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_P_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_P_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_P_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_P_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_ce0;
    end else begin
        key_P_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_P_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_P_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_P_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_P_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_P_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_P_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_ce1;
    end else begin
        key_P_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        key_P_d0 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_P_d0 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_P_d0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_d0;
    end else begin
        key_P_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        key_P_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_P_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_key_P_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_P_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_key_P_we0;
    end else begin
        key_P_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        key_P_we1 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_P_we1;
    end else begin
        key_P_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_S_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_S_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_S_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_S_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_address0;
    end else begin
        key_S_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_S_address1 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_S_address1 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_S_address1 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_address1;
    end else begin
        key_S_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_S_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_S_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_S_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_S_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_ce0;
    end else begin
        key_S_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        key_S_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_key_S_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_S_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_S_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_key_S_ce1;
    end else begin
        key_S_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        key_S_d0 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_S_d0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_d0;
    end else begin
        key_S_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        key_S_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_S_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_key_S_we0;
    end else begin
        key_S_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        key_S_we1 = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_key_S_we1;
    end else begin
        key_S_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outdata_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_outdata_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outdata_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_address0;
    end else begin
        outdata_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outdata_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_outdata_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outdata_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_ce0;
    end else begin
        outdata_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        outdata_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_outdata_we0;
    end else begin
        outdata_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ukey_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ukey_address0 = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_address0;
    end else begin
        ukey_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ukey_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ukey_ce0 = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_ce0;
    end else begin
        ukey_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ukey_ce1 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce1;
    end else begin
        ukey_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ukey_ce2 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce2;
    end else begin
        ukey_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ukey_ce3 = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ukey_ce3;
    end else begin
        ukey_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ukey_we0 = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ukey_we0;
    end else begin
        ukey_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln840_fu_212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln101_fu_299_p2 == 1'd1) & (grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((icmp_ln101_fu_299_p2 == 1'd0) & (grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln840_fu_329_p2 = ($signed(l_fu_56) + $signed(sext_ln845_reg_434));

assign add_ln842_fu_226_p2 = ($signed(sext_ln842_fu_222_p1) + $signed(33'd8589934591));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_done == 1'b0) | (grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_done == 1'b0) | (grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_done == 1'b0));
end

assign ap_return = check_fu_60;

assign empty_25_fu_236_p0 = k_fu_52;

assign empty_25_fu_236_p2 = (($signed(empty_25_fu_236_p0) > $signed(32'd5200)) ? 1'b1 : 1'b0);

assign empty_26_fu_260_p1 = sub_ln842_fu_254_p2[6:0];

assign empty_27_fu_264_p2 = ((sub_ln842_fu_254_p2 > 33'd8589934551) ? 1'b1 : 1'b0);

assign empty_fu_232_p1 = add_ln842_fu_226_p2[31:0];

assign grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_101_1_fu_156_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_110_1_fu_120_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_136_2_fu_127_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_144_3_fu_137_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_833_1_fu_96_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_842_3_fu_147_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_847_4_fu_170_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_86_11_fu_112_ap_start_reg;

assign grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start = grp_blowfish_main_Pipeline_VITIS_LOOP_86_1_fu_104_ap_start_reg;

assign icmp_ln101_fu_299_p2 = ((umax_reg_414 == 7'd127) ? 1'b1 : 1'b0);

assign icmp_ln840_fu_212_p0 = k_fu_52;

assign icmp_ln840_fu_212_p2 = (($signed(icmp_ln840_fu_212_p0) < $signed(32'd5200)) ? 1'b1 : 1'b0);

assign icmp_ln847_fu_324_p2 = (($signed(umax_reg_414) < $signed(7'd127)) ? 1'b1 : 1'b0);

assign l_1_fu_278_p2 = (umax_fu_270_p3 ^ 7'd127);

assign select_ln840_fu_334_p3 = ((icmp_ln847_fu_324_p2[0:0] == 1'b1) ? add_ln840_fu_329_p2 : l_fu_56);

assign sext_ln842_1_fu_288_p1 = umax_reg_414;

assign sext_ln842_fu_222_p0 = k_fu_52;

assign sext_ln842_fu_222_p1 = sext_ln842_fu_222_p0;

assign sext_ln845_fu_296_p1 = $signed(l_1_reg_421);

assign smax_fu_242_p3 = ((empty_25_fu_236_p2[0:0] == 1'b1) ? trunc_ln842_fu_218_p1 : 13'd5200);

assign sub_ln842_fu_254_p2 = (add_ln842_fu_226_p2 - zext_ln842_fu_250_p1);

assign sub_ln845_fu_291_p2 = ($signed(empty_reg_409) - $signed(sext_ln842_1_fu_288_p1));

assign trunc_ln842_fu_218_p0 = k_fu_52;

assign trunc_ln842_fu_218_p1 = trunc_ln842_fu_218_p0[12:0];

assign umax_fu_270_p3 = ((empty_27_fu_264_p2[0:0] == 1'b1) ? empty_26_fu_260_p1 : 7'd87);

assign zext_ln83_reload_cast_fu_311_p1 = zext_ln83_loc_fu_68;

assign zext_ln842_fu_250_p1 = smax_fu_242_p3;

always @ (posedge ap_clk) begin
    n_fu_64[31:3] <= 29'b00000000000000000000000000000;
end

endmodule //main_blowfish_main
