// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="main_main,hls_ip_2023_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.225000,HLS_SYN_LAT=188,HLS_SYN_TPT=none,HLS_SYN_MEM=7,HLS_SYN_DSP=0,HLS_SYN_FF=3610,HLS_SYN_LUT=11241,HLS_VERSION=2023_2}" *)

module main (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
wire    ap_continue;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_ready;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln215_reg_239;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_done_reg;
reg    ap_block_pp0_stage3_subdone;
wire   [5:0] a_input_address0;
reg    a_input_ce0;
wire   [63:0] a_input_q0;
wire   [5:0] b_input_address0;
reg    b_input_ce0;
wire   [63:0] b_input_q0;
reg   [31:0] float_exception_flags;
wire   [5:0] z_output_address0;
reg    z_output_ce0;
wire   [63:0] z_output_q0;
reg   [31:0] ap_return;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln215_fu_149_p2;
reg   [0:0] icmp_ln215_reg_239_pp0_iter1_reg;
wire   [63:0] zext_ln215_fu_161_p1;
reg   [63:0] zext_ln215_reg_243;
reg   [63:0] x1_reg_258;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [63:0] x2_reg_264;
wire   [0:0] tmp_19_fu_172_p3;
reg   [0:0] tmp_19_reg_270;
wire   [0:0] xor_ln412_fu_188_p2;
reg   [0:0] xor_ln412_reg_276;
reg   [0:0] xor_ln412_reg_276_pp0_iter1_reg;
wire   [63:0] grp_addFloat64Sigs_fu_116_ap_return;
reg   [63:0] tmp_reg_280;
wire   [63:0] grp_subFloat64Sigs_fu_125_ap_return;
reg   [63:0] tmp_1_reg_290;
reg   [63:0] z_output_load_reg_295;
reg    ap_enable_reg_pp0_iter0_reg;
wire    grp_addFloat64Sigs_fu_116_ap_start;
wire    grp_addFloat64Sigs_fu_116_ap_done;
wire    grp_addFloat64Sigs_fu_116_ap_idle;
wire    grp_addFloat64Sigs_fu_116_ap_ready;
reg    grp_addFloat64Sigs_fu_116_ap_ce;
wire   [31:0] grp_addFloat64Sigs_fu_116_float_exception_flags_o;
wire    grp_addFloat64Sigs_fu_116_float_exception_flags_o_ap_vld;
reg    ap_predicate_op38_call_state3;
reg    ap_predicate_op42_call_state5;
wire    ap_block_pp0_stage2_11001_ignoreCallOp38;
reg    ap_block_pp0_stage3_11001_ignoreCallOp40;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call0;
reg    ap_block_pp0_stage0_11001_ignoreCallOp42;
wire    grp_subFloat64Sigs_fu_125_ap_start;
wire    grp_subFloat64Sigs_fu_125_ap_done;
wire    grp_subFloat64Sigs_fu_125_ap_idle;
wire    grp_subFloat64Sigs_fu_125_ap_ready;
reg    grp_subFloat64Sigs_fu_125_ap_ce;
wire   [31:0] grp_subFloat64Sigs_fu_125_float_exception_flags_o;
wire    grp_subFloat64Sigs_fu_125_float_exception_flags_o_ap_vld;
reg    ap_predicate_op39_call_state3;
reg    ap_predicate_op47_call_state6;
wire    ap_block_pp0_stage2_11001_ignoreCallOp39;
reg    ap_block_pp0_stage3_11001_ignoreCallOp41;
reg    ap_block_pp0_stage0_11001_ignoreCallOp43;
wire    ap_block_pp0_stage1_11001_ignoreCallOp47;
reg   [63:0] ap_phi_mux_result_phi_fu_110_p4;
wire   [63:0] ap_phi_reg_pp0_iter0_result_reg_107;
reg   [63:0] ap_phi_reg_pp0_iter1_result_reg_107;
reg    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage2_11001;
reg    grp_addFloat64Sigs_fu_116_ap_start_reg;
reg    ap_predicate_op38_call_state3_state2;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage0;
reg    grp_subFloat64Sigs_fu_125_ap_start_reg;
reg    ap_predicate_op39_call_state3_state2;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage3;
reg   [5:0] main_result_fu_60;
wire   [5:0] main_result_1_fu_206_p2;
reg   [5:0] ap_sig_allocacmp_main_result_load_1;
wire    ap_loop_init;
reg   [5:0] i_fu_64;
wire   [5:0] add_ln215_fu_155_p2;
reg   [5:0] ap_sig_allocacmp_i_1;
wire   [0:0] tmp_20_fu_180_p3;
wire   [0:0] icmp_ln221_fu_197_p2;
wire   [5:0] zext_ln221_fu_202_p1;
wire   [31:0] zext_ln215_1_fu_220_p1;
reg   [31:0] ap_return_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_453;
reg    ap_condition_458;
reg    ap_condition_349;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 float_exception_flags = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_addFloat64Sigs_fu_116_ap_start_reg = 1'b0;
#0 grp_subFloat64Sigs_fu_125_ap_start_reg = 1'b0;
#0 main_result_fu_60 = 6'd0;
#0 i_fu_64 = 6'd0;
#0 ap_return_preg = 32'd0;
end

main_a_input_ROM_AUTO_1R #(
    .DataWidth( 64 ),
    .AddressRange( 46 ),
    .AddressWidth( 6 ))
a_input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(a_input_address0),
    .ce0(a_input_ce0),
    .q0(a_input_q0)
);

main_b_input_ROM_AUTO_1R #(
    .DataWidth( 64 ),
    .AddressRange( 46 ),
    .AddressWidth( 6 ))
b_input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(b_input_address0),
    .ce0(b_input_ce0),
    .q0(b_input_q0)
);

main_z_output_ROM_AUTO_1R #(
    .DataWidth( 64 ),
    .AddressRange( 46 ),
    .AddressWidth( 6 ))
z_output_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(z_output_address0),
    .ce0(z_output_ce0),
    .q0(z_output_q0)
);

main_addFloat64Sigs grp_addFloat64Sigs_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_addFloat64Sigs_fu_116_ap_start),
    .ap_done(grp_addFloat64Sigs_fu_116_ap_done),
    .ap_idle(grp_addFloat64Sigs_fu_116_ap_idle),
    .ap_ready(grp_addFloat64Sigs_fu_116_ap_ready),
    .ap_ce(grp_addFloat64Sigs_fu_116_ap_ce),
    .a(x1_reg_258),
    .b(x2_reg_264),
    .zSign(tmp_19_reg_270),
    .float_exception_flags_i(float_exception_flags),
    .float_exception_flags_o(grp_addFloat64Sigs_fu_116_float_exception_flags_o),
    .float_exception_flags_o_ap_vld(grp_addFloat64Sigs_fu_116_float_exception_flags_o_ap_vld),
    .ap_return(grp_addFloat64Sigs_fu_116_ap_return)
);

main_subFloat64Sigs grp_subFloat64Sigs_fu_125(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_subFloat64Sigs_fu_125_ap_start),
    .ap_done(grp_subFloat64Sigs_fu_125_ap_done),
    .ap_idle(grp_subFloat64Sigs_fu_125_ap_idle),
    .ap_ready(grp_subFloat64Sigs_fu_125_ap_ready),
    .ap_ce(grp_subFloat64Sigs_fu_125_ap_ce),
    .a(x1_reg_258),
    .b(x2_reg_264),
    .zSign(tmp_19_reg_270),
    .float_exception_flags_i(float_exception_flags),
    .float_exception_flags_o(grp_subFloat64Sigs_fu_125_float_exception_flags_o),
    .float_exception_flags_o_ap_vld(grp_subFloat64Sigs_fu_125_float_exception_flags_o_ap_vld),
    .ap_return(grp_subFloat64Sigs_fu_125_ap_return)
);

main_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle),
    .ap_return(ap_return)
);

main_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
                ap_return_preg[0] <= 1'b0;
        ap_return_preg[1] <= 1'b0;
        ap_return_preg[2] <= 1'b0;
        ap_return_preg[3] <= 1'b0;
        ap_return_preg[4] <= 1'b0;
        ap_return_preg[5] <= 1'b0;
    end else begin
        if (((icmp_ln215_reg_239 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
                        ap_return_preg[5 : 0] <= zext_ln215_1_fu_220_p1[5 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_addFloat64Sigs_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op38_call_state3_state2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_addFloat64Sigs_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_addFloat64Sigs_fu_116_ap_ready == 1'b1)) begin
            grp_addFloat64Sigs_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_subFloat64Sigs_fu_125_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op39_call_state3_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_subFloat64Sigs_fu_125_ap_start_reg <= 1'b1;
        end else if ((grp_subFloat64Sigs_fu_125_ap_ready == 1'b1)) begin
            grp_subFloat64Sigs_fu_125_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (xor_ln412_reg_276 == 1'd0) & (icmp_ln215_reg_239_pp0_iter1_reg == 1'd0))) begin
        ap_phi_reg_pp0_iter1_result_reg_107 <= tmp_reg_280;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter1_result_reg_107 <= ap_phi_reg_pp0_iter0_result_reg_107;
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_458)) begin
            float_exception_flags <= grp_subFloat64Sigs_fu_125_float_exception_flags_o;
        end else if ((1'b1 == ap_condition_453)) begin
            float_exception_flags <= grp_addFloat64Sigs_fu_116_float_exception_flags_o;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_349)) begin
        if ((icmp_ln215_fu_149_p2 == 1'd0)) begin
            i_fu_64 <= add_ln215_fu_155_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        main_result_fu_60 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        main_result_fu_60 <= main_result_1_fu_206_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln215_reg_239 <= icmp_ln215_fu_149_p2;
        icmp_ln215_reg_239_pp0_iter1_reg <= icmp_ln215_reg_239;
        tmp_reg_280 <= grp_addFloat64Sigs_fu_116_ap_return;
        zext_ln215_reg_243[5 : 0] <= zext_ln215_fu_161_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_19_reg_270 <= a_input_q0[32'd63];
        tmp_1_reg_290 <= grp_subFloat64Sigs_fu_125_ap_return;
        x1_reg_258 <= a_input_q0;
        x2_reg_264 <= b_input_q0;
        xor_ln412_reg_276 <= xor_ln412_fu_188_p2;
        xor_ln412_reg_276_pp0_iter1_reg <= xor_ln412_reg_276;
        z_output_load_reg_295 <= z_output_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_input_ce0 = 1'b1;
    end else begin
        a_input_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln215_reg_239 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((xor_ln412_reg_276_pp0_iter1_reg == 1'd1) & (icmp_ln215_reg_239_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_result_phi_fu_110_p4 = tmp_1_reg_290;
    end else begin
        ap_phi_mux_result_phi_fu_110_p4 = ap_phi_reg_pp0_iter1_result_reg_107;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln215_reg_239 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_return = zext_ln215_1_fu_220_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_main_result_load_1 = main_result_1_fu_206_p2;
    end else begin
        ap_sig_allocacmp_main_result_load_1 = main_result_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_input_ce0 = 1'b1;
    end else begin
        b_input_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp42) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp40) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp38) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_addFloat64Sigs_fu_116_ap_ce = 1'b1;
    end else begin
        grp_addFloat64Sigs_fu_116_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp47) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp43) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp41) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp39) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_subFloat64Sigs_fu_125_ap_ce = 1'b1;
    end else begin
        grp_subFloat64Sigs_fu_125_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        z_output_ce0 = 1'b1;
    end else begin
        z_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_input_address0 = zext_ln215_fu_161_p1;

assign add_ln215_fu_155_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp42 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp43 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp47 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp38 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp39 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage3_11001_ignoreCallOp40 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage3_11001_ignoreCallOp41 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_349 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_453 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_call_state5 == 1'b1) & (grp_addFloat64Sigs_fu_116_float_exception_flags_o_ap_vld == 1'b1));
end

always @ (*) begin
    ap_condition_458 = ((1'b0 == ap_block_pp0_stage1) & (ap_predicate_op47_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_subFloat64Sigs_fu_125_float_exception_flags_o_ap_vld == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter0_result_reg_107 = 'bx;

always @ (*) begin
    ap_predicate_op38_call_state3 = ((icmp_ln215_reg_239 == 1'd0) & (xor_ln412_reg_276 == 1'd0));
end

always @ (*) begin
    ap_predicate_op38_call_state3_state2 = ((icmp_ln215_reg_239 == 1'd0) & (xor_ln412_fu_188_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op39_call_state3 = ((icmp_ln215_reg_239 == 1'd0) & (xor_ln412_reg_276 == 1'd1));
end

always @ (*) begin
    ap_predicate_op39_call_state3_state2 = ((icmp_ln215_reg_239 == 1'd0) & (xor_ln412_fu_188_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op42_call_state5 = ((icmp_ln215_reg_239 == 1'd0) & (xor_ln412_reg_276 == 1'd0));
end

always @ (*) begin
    ap_predicate_op47_call_state6 = ((xor_ln412_reg_276 == 1'd1) & (icmp_ln215_reg_239_pp0_iter1_reg == 1'd0));
end

assign b_input_address0 = zext_ln215_fu_161_p1;

assign grp_addFloat64Sigs_fu_116_ap_start = grp_addFloat64Sigs_fu_116_ap_start_reg;

assign grp_subFloat64Sigs_fu_125_ap_start = grp_subFloat64Sigs_fu_125_ap_start_reg;

assign icmp_ln215_fu_149_p2 = ((ap_sig_allocacmp_i_1 == 6'd46) ? 1'b1 : 1'b0);

assign icmp_ln221_fu_197_p2 = ((ap_phi_mux_result_phi_fu_110_p4 != z_output_load_reg_295) ? 1'b1 : 1'b0);

assign main_result_1_fu_206_p2 = (zext_ln221_fu_202_p1 + main_result_fu_60);

assign tmp_19_fu_172_p3 = a_input_q0[32'd63];

assign tmp_20_fu_180_p3 = b_input_q0[32'd63];

assign xor_ln412_fu_188_p2 = (tmp_20_fu_180_p3 ^ tmp_19_fu_172_p3);

assign z_output_address0 = zext_ln215_reg_243;

assign zext_ln215_1_fu_220_p1 = ap_sig_allocacmp_main_result_load_1;

assign zext_ln215_fu_161_p1 = ap_sig_allocacmp_i_1;

assign zext_ln221_fu_202_p1 = icmp_ln221_fu_197_p2;

always @ (posedge ap_clk) begin
    zext_ln215_reg_243[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    ap_return_preg[31:6] <= 26'b00000000000000000000000000;
end

endmodule //main
