// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="main_main,hls_ip_2023_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.923286,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=18,HLS_SYN_DSP=0,HLS_SYN_FF=2516,HLS_SYN_LUT=12970,HLS_VERSION=2023_2}" *)

module main (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [31:0] main_result;
reg   [6:0] word_0_address0;
reg    word_0_ce0;
reg    word_0_we0;
reg   [31:0] word_0_d0;
wire   [31:0] word_0_q0;
reg   [6:0] word_0_address1;
reg    word_0_ce1;
wire   [31:0] word_0_q1;
reg   [6:0] word_1_address0;
reg    word_1_ce0;
reg    word_1_we0;
reg   [31:0] word_1_d0;
wire   [31:0] word_1_q0;
reg   [6:0] word_1_address1;
reg    word_1_ce1;
wire   [31:0] word_1_q1;
reg   [6:0] word_2_address0;
reg    word_2_ce0;
reg    word_2_we0;
reg   [31:0] word_2_d0;
wire   [31:0] word_2_q0;
reg   [6:0] word_2_address1;
reg    word_2_ce1;
wire   [31:0] word_2_q1;
reg   [6:0] word_3_address0;
reg    word_3_ce0;
reg    word_3_we0;
reg   [31:0] word_3_d0;
wire   [31:0] word_3_q0;
reg   [6:0] word_3_address1;
reg    word_3_ce1;
wire   [31:0] word_3_q1;
reg   [0:0] round_val;
reg   [2:0] statemt_0_address0;
reg    statemt_0_ce0;
reg    statemt_0_we0;
reg   [31:0] statemt_0_d0;
wire   [31:0] statemt_0_q0;
reg   [2:0] statemt_0_address1;
reg    statemt_0_ce1;
reg    statemt_0_we1;
reg   [31:0] statemt_0_d1;
wire   [31:0] statemt_0_q1;
reg   [2:0] statemt_1_address0;
reg    statemt_1_ce0;
reg    statemt_1_we0;
reg   [31:0] statemt_1_d0;
wire   [31:0] statemt_1_q0;
reg   [2:0] statemt_1_address1;
reg    statemt_1_ce1;
reg    statemt_1_we1;
reg   [31:0] statemt_1_d1;
wire   [31:0] statemt_1_q1;
reg   [2:0] statemt_2_address0;
reg    statemt_2_ce0;
reg    statemt_2_we0;
reg   [31:0] statemt_2_d0;
wire   [31:0] statemt_2_q0;
reg   [2:0] statemt_2_address1;
reg    statemt_2_ce1;
reg    statemt_2_we1;
reg   [31:0] statemt_2_d1;
wire   [31:0] statemt_2_q1;
reg   [2:0] statemt_3_address0;
reg    statemt_3_ce0;
reg    statemt_3_we0;
reg   [31:0] statemt_3_d0;
wire   [31:0] statemt_3_q0;
reg   [2:0] statemt_3_address1;
reg    statemt_3_ce1;
reg    statemt_3_we1;
reg   [31:0] statemt_3_d1;
wire   [31:0] statemt_3_q1;
wire    grp_encrypt_fu_188_ap_start;
wire    grp_encrypt_fu_188_ap_done;
wire    grp_encrypt_fu_188_ap_idle;
wire    grp_encrypt_fu_188_ap_ready;
wire   [6:0] grp_encrypt_fu_188_word_0_address0;
wire    grp_encrypt_fu_188_word_0_ce0;
wire    grp_encrypt_fu_188_word_0_we0;
wire   [31:0] grp_encrypt_fu_188_word_0_d0;
wire   [6:0] grp_encrypt_fu_188_word_0_address1;
wire    grp_encrypt_fu_188_word_0_ce1;
wire   [6:0] grp_encrypt_fu_188_word_1_address0;
wire    grp_encrypt_fu_188_word_1_ce0;
wire    grp_encrypt_fu_188_word_1_we0;
wire   [31:0] grp_encrypt_fu_188_word_1_d0;
wire   [6:0] grp_encrypt_fu_188_word_1_address1;
wire    grp_encrypt_fu_188_word_1_ce1;
wire   [6:0] grp_encrypt_fu_188_word_2_address0;
wire    grp_encrypt_fu_188_word_2_ce0;
wire    grp_encrypt_fu_188_word_2_we0;
wire   [31:0] grp_encrypt_fu_188_word_2_d0;
wire   [6:0] grp_encrypt_fu_188_word_2_address1;
wire    grp_encrypt_fu_188_word_2_ce1;
wire   [6:0] grp_encrypt_fu_188_word_3_address0;
wire    grp_encrypt_fu_188_word_3_ce0;
wire    grp_encrypt_fu_188_word_3_we0;
wire   [31:0] grp_encrypt_fu_188_word_3_d0;
wire   [6:0] grp_encrypt_fu_188_word_3_address1;
wire    grp_encrypt_fu_188_word_3_ce1;
wire   [0:0] grp_encrypt_fu_188_round_val_o;
wire    grp_encrypt_fu_188_round_val_o_ap_vld;
wire   [2:0] grp_encrypt_fu_188_statemt_0_address0;
wire    grp_encrypt_fu_188_statemt_0_ce0;
wire    grp_encrypt_fu_188_statemt_0_we0;
wire   [31:0] grp_encrypt_fu_188_statemt_0_d0;
wire   [2:0] grp_encrypt_fu_188_statemt_0_address1;
wire    grp_encrypt_fu_188_statemt_0_ce1;
wire    grp_encrypt_fu_188_statemt_0_we1;
wire   [31:0] grp_encrypt_fu_188_statemt_0_d1;
wire   [2:0] grp_encrypt_fu_188_statemt_1_address0;
wire    grp_encrypt_fu_188_statemt_1_ce0;
wire    grp_encrypt_fu_188_statemt_1_we0;
wire   [31:0] grp_encrypt_fu_188_statemt_1_d0;
wire   [2:0] grp_encrypt_fu_188_statemt_1_address1;
wire    grp_encrypt_fu_188_statemt_1_ce1;
wire    grp_encrypt_fu_188_statemt_1_we1;
wire   [31:0] grp_encrypt_fu_188_statemt_1_d1;
wire   [2:0] grp_encrypt_fu_188_statemt_2_address0;
wire    grp_encrypt_fu_188_statemt_2_ce0;
wire    grp_encrypt_fu_188_statemt_2_we0;
wire   [31:0] grp_encrypt_fu_188_statemt_2_d0;
wire   [2:0] grp_encrypt_fu_188_statemt_2_address1;
wire    grp_encrypt_fu_188_statemt_2_ce1;
wire    grp_encrypt_fu_188_statemt_2_we1;
wire   [31:0] grp_encrypt_fu_188_statemt_2_d1;
wire   [2:0] grp_encrypt_fu_188_statemt_3_address0;
wire    grp_encrypt_fu_188_statemt_3_ce0;
wire    grp_encrypt_fu_188_statemt_3_we0;
wire   [31:0] grp_encrypt_fu_188_statemt_3_d0;
wire   [2:0] grp_encrypt_fu_188_statemt_3_address1;
wire    grp_encrypt_fu_188_statemt_3_ce1;
wire    grp_encrypt_fu_188_statemt_3_we1;
wire   [31:0] grp_encrypt_fu_188_statemt_3_d1;
wire   [31:0] grp_encrypt_fu_188_main_result_o;
wire    grp_encrypt_fu_188_main_result_o_ap_vld;
wire    grp_decrypt_fu_220_ap_start;
wire    grp_decrypt_fu_220_ap_done;
wire    grp_decrypt_fu_220_ap_idle;
wire    grp_decrypt_fu_220_ap_ready;
wire   [6:0] grp_decrypt_fu_220_word_0_address0;
wire    grp_decrypt_fu_220_word_0_ce0;
wire    grp_decrypt_fu_220_word_0_we0;
wire   [31:0] grp_decrypt_fu_220_word_0_d0;
wire   [6:0] grp_decrypt_fu_220_word_0_address1;
wire    grp_decrypt_fu_220_word_0_ce1;
wire   [6:0] grp_decrypt_fu_220_word_1_address0;
wire    grp_decrypt_fu_220_word_1_ce0;
wire    grp_decrypt_fu_220_word_1_we0;
wire   [31:0] grp_decrypt_fu_220_word_1_d0;
wire   [6:0] grp_decrypt_fu_220_word_1_address1;
wire    grp_decrypt_fu_220_word_1_ce1;
wire   [6:0] grp_decrypt_fu_220_word_2_address0;
wire    grp_decrypt_fu_220_word_2_ce0;
wire    grp_decrypt_fu_220_word_2_we0;
wire   [31:0] grp_decrypt_fu_220_word_2_d0;
wire   [6:0] grp_decrypt_fu_220_word_2_address1;
wire    grp_decrypt_fu_220_word_2_ce1;
wire   [6:0] grp_decrypt_fu_220_word_3_address0;
wire    grp_decrypt_fu_220_word_3_ce0;
wire    grp_decrypt_fu_220_word_3_we0;
wire   [31:0] grp_decrypt_fu_220_word_3_d0;
wire   [6:0] grp_decrypt_fu_220_word_3_address1;
wire    grp_decrypt_fu_220_word_3_ce1;
wire   [0:0] grp_decrypt_fu_220_round_val;
wire    grp_decrypt_fu_220_round_val_ap_vld;
wire   [2:0] grp_decrypt_fu_220_statemt_0_address0;
wire    grp_decrypt_fu_220_statemt_0_ce0;
wire    grp_decrypt_fu_220_statemt_0_we0;
wire   [31:0] grp_decrypt_fu_220_statemt_0_d0;
wire   [2:0] grp_decrypt_fu_220_statemt_0_address1;
wire    grp_decrypt_fu_220_statemt_0_ce1;
wire    grp_decrypt_fu_220_statemt_0_we1;
wire   [31:0] grp_decrypt_fu_220_statemt_0_d1;
wire   [2:0] grp_decrypt_fu_220_statemt_1_address0;
wire    grp_decrypt_fu_220_statemt_1_ce0;
wire    grp_decrypt_fu_220_statemt_1_we0;
wire   [31:0] grp_decrypt_fu_220_statemt_1_d0;
wire   [2:0] grp_decrypt_fu_220_statemt_1_address1;
wire    grp_decrypt_fu_220_statemt_1_ce1;
wire    grp_decrypt_fu_220_statemt_1_we1;
wire   [31:0] grp_decrypt_fu_220_statemt_1_d1;
wire   [2:0] grp_decrypt_fu_220_statemt_2_address0;
wire    grp_decrypt_fu_220_statemt_2_ce0;
wire    grp_decrypt_fu_220_statemt_2_we0;
wire   [31:0] grp_decrypt_fu_220_statemt_2_d0;
wire   [2:0] grp_decrypt_fu_220_statemt_2_address1;
wire    grp_decrypt_fu_220_statemt_2_ce1;
wire    grp_decrypt_fu_220_statemt_2_we1;
wire   [31:0] grp_decrypt_fu_220_statemt_2_d1;
wire   [2:0] grp_decrypt_fu_220_statemt_3_address0;
wire    grp_decrypt_fu_220_statemt_3_ce0;
wire    grp_decrypt_fu_220_statemt_3_we0;
wire   [31:0] grp_decrypt_fu_220_statemt_3_d0;
wire   [2:0] grp_decrypt_fu_220_statemt_3_address1;
wire    grp_decrypt_fu_220_statemt_3_ce1;
wire    grp_decrypt_fu_220_statemt_3_we1;
wire   [31:0] grp_decrypt_fu_220_statemt_3_d1;
wire   [31:0] grp_decrypt_fu_220_main_result_o;
wire    grp_decrypt_fu_220_main_result_o_ap_vld;
reg    grp_encrypt_fu_188_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_decrypt_fu_220_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state7;
reg    ap_block_state1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;
wire   [31:0] ap_return;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 main_result = 32'd0;
#0 round_val = 1'd0;
#0 grp_encrypt_fu_188_ap_start_reg = 1'b0;
#0 grp_decrypt_fu_220_ap_start_reg = 1'b0;
end

main_word_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
word_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(word_0_address0),
    .ce0(word_0_ce0),
    .we0(word_0_we0),
    .d0(word_0_d0),
    .q0(word_0_q0),
    .address1(word_0_address1),
    .ce1(word_0_ce1),
    .q1(word_0_q1)
);

main_word_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
word_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(word_1_address0),
    .ce0(word_1_ce0),
    .we0(word_1_we0),
    .d0(word_1_d0),
    .q0(word_1_q0),
    .address1(word_1_address1),
    .ce1(word_1_ce1),
    .q1(word_1_q1)
);

main_word_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
word_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(word_2_address0),
    .ce0(word_2_ce0),
    .we0(word_2_we0),
    .d0(word_2_d0),
    .q0(word_2_q0),
    .address1(word_2_address1),
    .ce1(word_2_ce1),
    .q1(word_2_q1)
);

main_word_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
word_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(word_3_address0),
    .ce0(word_3_ce0),
    .we0(word_3_we0),
    .d0(word_3_d0),
    .q0(word_3_q0),
    .address1(word_3_address1),
    .ce1(word_3_ce1),
    .q1(word_3_q1)
);

main_statemt_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
statemt_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(statemt_0_address0),
    .ce0(statemt_0_ce0),
    .we0(statemt_0_we0),
    .d0(statemt_0_d0),
    .q0(statemt_0_q0),
    .address1(statemt_0_address1),
    .ce1(statemt_0_ce1),
    .we1(statemt_0_we1),
    .d1(statemt_0_d1),
    .q1(statemt_0_q1)
);

main_statemt_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
statemt_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(statemt_1_address0),
    .ce0(statemt_1_ce0),
    .we0(statemt_1_we0),
    .d0(statemt_1_d0),
    .q0(statemt_1_q0),
    .address1(statemt_1_address1),
    .ce1(statemt_1_ce1),
    .we1(statemt_1_we1),
    .d1(statemt_1_d1),
    .q1(statemt_1_q1)
);

main_statemt_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
statemt_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(statemt_2_address0),
    .ce0(statemt_2_ce0),
    .we0(statemt_2_we0),
    .d0(statemt_2_d0),
    .q0(statemt_2_q0),
    .address1(statemt_2_address1),
    .ce1(statemt_2_ce1),
    .we1(statemt_2_we1),
    .d1(statemt_2_d1),
    .q1(statemt_2_q1)
);

main_statemt_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
statemt_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(statemt_3_address0),
    .ce0(statemt_3_ce0),
    .we0(statemt_3_we0),
    .d0(statemt_3_d0),
    .q0(statemt_3_q0),
    .address1(statemt_3_address1),
    .ce1(statemt_3_ce1),
    .we1(statemt_3_we1),
    .d1(statemt_3_d1),
    .q1(statemt_3_q1)
);

main_encrypt grp_encrypt_fu_188(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_encrypt_fu_188_ap_start),
    .ap_done(grp_encrypt_fu_188_ap_done),
    .ap_idle(grp_encrypt_fu_188_ap_idle),
    .ap_ready(grp_encrypt_fu_188_ap_ready),
    .word_0_address0(grp_encrypt_fu_188_word_0_address0),
    .word_0_ce0(grp_encrypt_fu_188_word_0_ce0),
    .word_0_we0(grp_encrypt_fu_188_word_0_we0),
    .word_0_d0(grp_encrypt_fu_188_word_0_d0),
    .word_0_q0(word_0_q0),
    .word_0_address1(grp_encrypt_fu_188_word_0_address1),
    .word_0_ce1(grp_encrypt_fu_188_word_0_ce1),
    .word_0_q1(word_0_q1),
    .word_1_address0(grp_encrypt_fu_188_word_1_address0),
    .word_1_ce0(grp_encrypt_fu_188_word_1_ce0),
    .word_1_we0(grp_encrypt_fu_188_word_1_we0),
    .word_1_d0(grp_encrypt_fu_188_word_1_d0),
    .word_1_q0(word_1_q0),
    .word_1_address1(grp_encrypt_fu_188_word_1_address1),
    .word_1_ce1(grp_encrypt_fu_188_word_1_ce1),
    .word_1_q1(word_1_q1),
    .word_2_address0(grp_encrypt_fu_188_word_2_address0),
    .word_2_ce0(grp_encrypt_fu_188_word_2_ce0),
    .word_2_we0(grp_encrypt_fu_188_word_2_we0),
    .word_2_d0(grp_encrypt_fu_188_word_2_d0),
    .word_2_q0(word_2_q0),
    .word_2_address1(grp_encrypt_fu_188_word_2_address1),
    .word_2_ce1(grp_encrypt_fu_188_word_2_ce1),
    .word_2_q1(word_2_q1),
    .word_3_address0(grp_encrypt_fu_188_word_3_address0),
    .word_3_ce0(grp_encrypt_fu_188_word_3_ce0),
    .word_3_we0(grp_encrypt_fu_188_word_3_we0),
    .word_3_d0(grp_encrypt_fu_188_word_3_d0),
    .word_3_q0(word_3_q0),
    .word_3_address1(grp_encrypt_fu_188_word_3_address1),
    .word_3_ce1(grp_encrypt_fu_188_word_3_ce1),
    .word_3_q1(word_3_q1),
    .round_val_i(round_val),
    .round_val_o(grp_encrypt_fu_188_round_val_o),
    .round_val_o_ap_vld(grp_encrypt_fu_188_round_val_o_ap_vld),
    .statemt_0_address0(grp_encrypt_fu_188_statemt_0_address0),
    .statemt_0_ce0(grp_encrypt_fu_188_statemt_0_ce0),
    .statemt_0_we0(grp_encrypt_fu_188_statemt_0_we0),
    .statemt_0_d0(grp_encrypt_fu_188_statemt_0_d0),
    .statemt_0_q0(statemt_0_q0),
    .statemt_0_address1(grp_encrypt_fu_188_statemt_0_address1),
    .statemt_0_ce1(grp_encrypt_fu_188_statemt_0_ce1),
    .statemt_0_we1(grp_encrypt_fu_188_statemt_0_we1),
    .statemt_0_d1(grp_encrypt_fu_188_statemt_0_d1),
    .statemt_0_q1(statemt_0_q1),
    .statemt_1_address0(grp_encrypt_fu_188_statemt_1_address0),
    .statemt_1_ce0(grp_encrypt_fu_188_statemt_1_ce0),
    .statemt_1_we0(grp_encrypt_fu_188_statemt_1_we0),
    .statemt_1_d0(grp_encrypt_fu_188_statemt_1_d0),
    .statemt_1_q0(statemt_1_q0),
    .statemt_1_address1(grp_encrypt_fu_188_statemt_1_address1),
    .statemt_1_ce1(grp_encrypt_fu_188_statemt_1_ce1),
    .statemt_1_we1(grp_encrypt_fu_188_statemt_1_we1),
    .statemt_1_d1(grp_encrypt_fu_188_statemt_1_d1),
    .statemt_1_q1(statemt_1_q1),
    .statemt_2_address0(grp_encrypt_fu_188_statemt_2_address0),
    .statemt_2_ce0(grp_encrypt_fu_188_statemt_2_ce0),
    .statemt_2_we0(grp_encrypt_fu_188_statemt_2_we0),
    .statemt_2_d0(grp_encrypt_fu_188_statemt_2_d0),
    .statemt_2_q0(statemt_2_q0),
    .statemt_2_address1(grp_encrypt_fu_188_statemt_2_address1),
    .statemt_2_ce1(grp_encrypt_fu_188_statemt_2_ce1),
    .statemt_2_we1(grp_encrypt_fu_188_statemt_2_we1),
    .statemt_2_d1(grp_encrypt_fu_188_statemt_2_d1),
    .statemt_2_q1(statemt_2_q1),
    .statemt_3_address0(grp_encrypt_fu_188_statemt_3_address0),
    .statemt_3_ce0(grp_encrypt_fu_188_statemt_3_ce0),
    .statemt_3_we0(grp_encrypt_fu_188_statemt_3_we0),
    .statemt_3_d0(grp_encrypt_fu_188_statemt_3_d0),
    .statemt_3_q0(statemt_3_q0),
    .statemt_3_address1(grp_encrypt_fu_188_statemt_3_address1),
    .statemt_3_ce1(grp_encrypt_fu_188_statemt_3_ce1),
    .statemt_3_we1(grp_encrypt_fu_188_statemt_3_we1),
    .statemt_3_d1(grp_encrypt_fu_188_statemt_3_d1),
    .statemt_3_q1(statemt_3_q1),
    .main_result_i(main_result),
    .main_result_o(grp_encrypt_fu_188_main_result_o),
    .main_result_o_ap_vld(grp_encrypt_fu_188_main_result_o_ap_vld)
);

main_decrypt grp_decrypt_fu_220(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_decrypt_fu_220_ap_start),
    .ap_done(grp_decrypt_fu_220_ap_done),
    .ap_idle(grp_decrypt_fu_220_ap_idle),
    .ap_ready(grp_decrypt_fu_220_ap_ready),
    .word_0_address0(grp_decrypt_fu_220_word_0_address0),
    .word_0_ce0(grp_decrypt_fu_220_word_0_ce0),
    .word_0_we0(grp_decrypt_fu_220_word_0_we0),
    .word_0_d0(grp_decrypt_fu_220_word_0_d0),
    .word_0_q0(word_0_q0),
    .word_0_address1(grp_decrypt_fu_220_word_0_address1),
    .word_0_ce1(grp_decrypt_fu_220_word_0_ce1),
    .word_0_q1(word_0_q1),
    .word_1_address0(grp_decrypt_fu_220_word_1_address0),
    .word_1_ce0(grp_decrypt_fu_220_word_1_ce0),
    .word_1_we0(grp_decrypt_fu_220_word_1_we0),
    .word_1_d0(grp_decrypt_fu_220_word_1_d0),
    .word_1_q0(word_1_q0),
    .word_1_address1(grp_decrypt_fu_220_word_1_address1),
    .word_1_ce1(grp_decrypt_fu_220_word_1_ce1),
    .word_1_q1(word_1_q1),
    .word_2_address0(grp_decrypt_fu_220_word_2_address0),
    .word_2_ce0(grp_decrypt_fu_220_word_2_ce0),
    .word_2_we0(grp_decrypt_fu_220_word_2_we0),
    .word_2_d0(grp_decrypt_fu_220_word_2_d0),
    .word_2_q0(word_2_q0),
    .word_2_address1(grp_decrypt_fu_220_word_2_address1),
    .word_2_ce1(grp_decrypt_fu_220_word_2_ce1),
    .word_2_q1(word_2_q1),
    .word_3_address0(grp_decrypt_fu_220_word_3_address0),
    .word_3_ce0(grp_decrypt_fu_220_word_3_ce0),
    .word_3_we0(grp_decrypt_fu_220_word_3_we0),
    .word_3_d0(grp_decrypt_fu_220_word_3_d0),
    .word_3_q0(word_3_q0),
    .word_3_address1(grp_decrypt_fu_220_word_3_address1),
    .word_3_ce1(grp_decrypt_fu_220_word_3_ce1),
    .word_3_q1(word_3_q1),
    .round_val(grp_decrypt_fu_220_round_val),
    .round_val_ap_vld(grp_decrypt_fu_220_round_val_ap_vld),
    .statemt_0_address0(grp_decrypt_fu_220_statemt_0_address0),
    .statemt_0_ce0(grp_decrypt_fu_220_statemt_0_ce0),
    .statemt_0_we0(grp_decrypt_fu_220_statemt_0_we0),
    .statemt_0_d0(grp_decrypt_fu_220_statemt_0_d0),
    .statemt_0_q0(statemt_0_q0),
    .statemt_0_address1(grp_decrypt_fu_220_statemt_0_address1),
    .statemt_0_ce1(grp_decrypt_fu_220_statemt_0_ce1),
    .statemt_0_we1(grp_decrypt_fu_220_statemt_0_we1),
    .statemt_0_d1(grp_decrypt_fu_220_statemt_0_d1),
    .statemt_0_q1(statemt_0_q1),
    .statemt_1_address0(grp_decrypt_fu_220_statemt_1_address0),
    .statemt_1_ce0(grp_decrypt_fu_220_statemt_1_ce0),
    .statemt_1_we0(grp_decrypt_fu_220_statemt_1_we0),
    .statemt_1_d0(grp_decrypt_fu_220_statemt_1_d0),
    .statemt_1_q0(statemt_1_q0),
    .statemt_1_address1(grp_decrypt_fu_220_statemt_1_address1),
    .statemt_1_ce1(grp_decrypt_fu_220_statemt_1_ce1),
    .statemt_1_we1(grp_decrypt_fu_220_statemt_1_we1),
    .statemt_1_d1(grp_decrypt_fu_220_statemt_1_d1),
    .statemt_1_q1(statemt_1_q1),
    .statemt_2_address0(grp_decrypt_fu_220_statemt_2_address0),
    .statemt_2_ce0(grp_decrypt_fu_220_statemt_2_ce0),
    .statemt_2_we0(grp_decrypt_fu_220_statemt_2_we0),
    .statemt_2_d0(grp_decrypt_fu_220_statemt_2_d0),
    .statemt_2_q0(statemt_2_q0),
    .statemt_2_address1(grp_decrypt_fu_220_statemt_2_address1),
    .statemt_2_ce1(grp_decrypt_fu_220_statemt_2_ce1),
    .statemt_2_we1(grp_decrypt_fu_220_statemt_2_we1),
    .statemt_2_d1(grp_decrypt_fu_220_statemt_2_d1),
    .statemt_2_q1(statemt_2_q1),
    .statemt_3_address0(grp_decrypt_fu_220_statemt_3_address0),
    .statemt_3_ce0(grp_decrypt_fu_220_statemt_3_ce0),
    .statemt_3_we0(grp_decrypt_fu_220_statemt_3_we0),
    .statemt_3_d0(grp_decrypt_fu_220_statemt_3_d0),
    .statemt_3_q0(statemt_3_q0),
    .statemt_3_address1(grp_decrypt_fu_220_statemt_3_address1),
    .statemt_3_ce1(grp_decrypt_fu_220_statemt_3_ce1),
    .statemt_3_we1(grp_decrypt_fu_220_statemt_3_we1),
    .statemt_3_d1(grp_decrypt_fu_220_statemt_3_d1),
    .statemt_3_q1(statemt_3_q1),
    .main_result_i(main_result),
    .main_result_o(grp_decrypt_fu_220_main_result_o),
    .main_result_o_ap_vld(grp_decrypt_fu_220_main_result_o_ap_vld)
);

main_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle),
    .ap_return(main_result)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_decrypt_fu_220_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_decrypt_fu_220_ap_start_reg <= 1'b1;
        end else if ((grp_decrypt_fu_220_ap_ready == 1'b1)) begin
            grp_decrypt_fu_220_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_encrypt_fu_188_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_encrypt_fu_188_ap_start_reg <= 1'b1;
        end else if ((grp_encrypt_fu_188_ap_ready == 1'b1)) begin
            grp_encrypt_fu_188_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        main_result <= 32'd0;
    end else if (((grp_decrypt_fu_220_main_result_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        main_result <= grp_decrypt_fu_220_main_result_o;
    end else if (((grp_encrypt_fu_188_main_result_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        main_result <= grp_encrypt_fu_188_main_result_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_decrypt_fu_220_round_val_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        round_val <= grp_decrypt_fu_220_round_val;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_encrypt_fu_188_round_val_o_ap_vld == 1'b1))) begin
        round_val <= grp_encrypt_fu_188_round_val_o;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_encrypt_fu_188_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_decrypt_fu_220_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_0_address0 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_0_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_address0 = grp_decrypt_fu_220_statemt_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_address0 = grp_encrypt_fu_188_statemt_0_address0;
    end else begin
        statemt_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_0_address1 = 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_0_address1 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_address1 = grp_decrypt_fu_220_statemt_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_address1 = grp_encrypt_fu_188_statemt_0_address1;
    end else begin
        statemt_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_ce0 = grp_decrypt_fu_220_statemt_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_ce0 = grp_encrypt_fu_188_statemt_0_ce0;
    end else begin
        statemt_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_0_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_ce1 = grp_decrypt_fu_220_statemt_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_ce1 = grp_encrypt_fu_188_statemt_0_ce1;
    end else begin
        statemt_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_0_d0 = 32'd224;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_0_d0 = 32'd136;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_d0 = grp_decrypt_fu_220_statemt_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_d0 = grp_encrypt_fu_188_statemt_0_d0;
    end else begin
        statemt_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_0_d1 = 32'd49;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_0_d1 = 32'd50;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_d1 = grp_decrypt_fu_220_statemt_0_d1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_d1 = grp_encrypt_fu_188_statemt_0_d1;
    end else begin
        statemt_0_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_we0 = grp_decrypt_fu_220_statemt_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_we0 = grp_encrypt_fu_188_statemt_0_we0;
    end else begin
        statemt_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_0_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_0_we1 = grp_decrypt_fu_220_statemt_0_we1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_0_we1 = grp_encrypt_fu_188_statemt_0_we1;
    end else begin
        statemt_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_1_address0 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_1_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_address0 = grp_decrypt_fu_220_statemt_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_address0 = grp_encrypt_fu_188_statemt_1_address0;
    end else begin
        statemt_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_1_address1 = 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_1_address1 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_address1 = grp_decrypt_fu_220_statemt_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_address1 = grp_encrypt_fu_188_statemt_1_address1;
    end else begin
        statemt_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_ce0 = grp_decrypt_fu_220_statemt_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_ce0 = grp_encrypt_fu_188_statemt_1_ce0;
    end else begin
        statemt_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_1_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_ce1 = grp_decrypt_fu_220_statemt_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_ce1 = grp_encrypt_fu_188_statemt_1_ce1;
    end else begin
        statemt_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_1_d0 = 32'd55;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_1_d0 = 32'd90;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_d0 = grp_decrypt_fu_220_statemt_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_d0 = grp_encrypt_fu_188_statemt_1_d0;
    end else begin
        statemt_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_1_d1 = 32'd49;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_1_d1 = 32'd67;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_d1 = grp_decrypt_fu_220_statemt_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_d1 = grp_encrypt_fu_188_statemt_1_d1;
    end else begin
        statemt_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_we0 = grp_decrypt_fu_220_statemt_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_we0 = grp_encrypt_fu_188_statemt_1_we0;
    end else begin
        statemt_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_1_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_1_we1 = grp_decrypt_fu_220_statemt_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_1_we1 = grp_encrypt_fu_188_statemt_1_we1;
    end else begin
        statemt_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_2_address0 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_2_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_address0 = grp_decrypt_fu_220_statemt_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_address0 = grp_encrypt_fu_188_statemt_2_address0;
    end else begin
        statemt_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_2_address1 = 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_2_address1 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_address1 = grp_decrypt_fu_220_statemt_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_address1 = grp_encrypt_fu_188_statemt_2_address1;
    end else begin
        statemt_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_ce0 = grp_decrypt_fu_220_statemt_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_ce0 = grp_encrypt_fu_188_statemt_2_ce0;
    end else begin
        statemt_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_2_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_ce1 = grp_decrypt_fu_220_statemt_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_ce1 = grp_encrypt_fu_188_statemt_2_ce1;
    end else begin
        statemt_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_2_d0 = 32'd7;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_2_d0 = 32'd48;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_d0 = grp_decrypt_fu_220_statemt_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_d0 = grp_encrypt_fu_188_statemt_2_d0;
    end else begin
        statemt_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_2_d1 = 32'd152;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_2_d1 = 32'd246;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_d1 = grp_decrypt_fu_220_statemt_2_d1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_d1 = grp_encrypt_fu_188_statemt_2_d1;
    end else begin
        statemt_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_we0 = grp_decrypt_fu_220_statemt_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_we0 = grp_encrypt_fu_188_statemt_2_we0;
    end else begin
        statemt_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_2_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_2_we1 = grp_decrypt_fu_220_statemt_2_we1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_2_we1 = grp_encrypt_fu_188_statemt_2_we1;
    end else begin
        statemt_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_3_address0 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_3_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_address0 = grp_decrypt_fu_220_statemt_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_address0 = grp_encrypt_fu_188_statemt_3_address0;
    end else begin
        statemt_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_3_address1 = 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_3_address1 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_address1 = grp_decrypt_fu_220_statemt_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_address1 = grp_encrypt_fu_188_statemt_3_address1;
    end else begin
        statemt_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_ce0 = grp_decrypt_fu_220_statemt_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_ce0 = grp_encrypt_fu_188_statemt_3_ce0;
    end else begin
        statemt_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_3_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_ce1 = grp_decrypt_fu_220_statemt_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_ce1 = grp_encrypt_fu_188_statemt_3_ce1;
    end else begin
        statemt_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_3_d0 = 32'd52;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_3_d0 = 32'd141;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_d0 = grp_decrypt_fu_220_statemt_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_d0 = grp_encrypt_fu_188_statemt_3_d0;
    end else begin
        statemt_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        statemt_3_d1 = 32'd162;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        statemt_3_d1 = 32'd168;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_d1 = grp_decrypt_fu_220_statemt_3_d1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_d1 = grp_encrypt_fu_188_statemt_3_d1;
    end else begin
        statemt_3_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_we0 = grp_decrypt_fu_220_statemt_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_we0 = grp_encrypt_fu_188_statemt_3_we0;
    end else begin
        statemt_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        statemt_3_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        statemt_3_we1 = grp_decrypt_fu_220_statemt_3_we1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        statemt_3_we1 = grp_encrypt_fu_188_statemt_3_we1;
    end else begin
        statemt_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_0_address0 = grp_decrypt_fu_220_word_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_address0 = grp_encrypt_fu_188_word_0_address0;
    end else begin
        word_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_0_address1 = grp_decrypt_fu_220_word_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_address1 = grp_encrypt_fu_188_word_0_address1;
    end else begin
        word_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_0_ce0 = grp_decrypt_fu_220_word_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_ce0 = grp_encrypt_fu_188_word_0_ce0;
    end else begin
        word_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_0_ce1 = grp_decrypt_fu_220_word_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_ce1 = grp_encrypt_fu_188_word_0_ce1;
    end else begin
        word_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_0_d0 = grp_decrypt_fu_220_word_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_d0 = grp_encrypt_fu_188_word_0_d0;
    end else begin
        word_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_0_we0 = grp_decrypt_fu_220_word_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_we0 = grp_encrypt_fu_188_word_0_we0;
    end else begin
        word_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_1_address0 = grp_decrypt_fu_220_word_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_address0 = grp_encrypt_fu_188_word_1_address0;
    end else begin
        word_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_1_address1 = grp_decrypt_fu_220_word_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_address1 = grp_encrypt_fu_188_word_1_address1;
    end else begin
        word_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_1_ce0 = grp_decrypt_fu_220_word_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_ce0 = grp_encrypt_fu_188_word_1_ce0;
    end else begin
        word_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_1_ce1 = grp_decrypt_fu_220_word_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_ce1 = grp_encrypt_fu_188_word_1_ce1;
    end else begin
        word_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_1_d0 = grp_decrypt_fu_220_word_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_d0 = grp_encrypt_fu_188_word_1_d0;
    end else begin
        word_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_1_we0 = grp_decrypt_fu_220_word_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_we0 = grp_encrypt_fu_188_word_1_we0;
    end else begin
        word_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_2_address0 = grp_decrypt_fu_220_word_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_2_address0 = grp_encrypt_fu_188_word_2_address0;
    end else begin
        word_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_2_address1 = grp_decrypt_fu_220_word_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_2_address1 = grp_encrypt_fu_188_word_2_address1;
    end else begin
        word_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_2_ce0 = grp_decrypt_fu_220_word_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_2_ce0 = grp_encrypt_fu_188_word_2_ce0;
    end else begin
        word_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_2_ce1 = grp_decrypt_fu_220_word_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_2_ce1 = grp_encrypt_fu_188_word_2_ce1;
    end else begin
        word_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_2_d0 = grp_decrypt_fu_220_word_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_2_d0 = grp_encrypt_fu_188_word_2_d0;
    end else begin
        word_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_2_we0 = grp_decrypt_fu_220_word_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_2_we0 = grp_encrypt_fu_188_word_2_we0;
    end else begin
        word_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_3_address0 = grp_decrypt_fu_220_word_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_3_address0 = grp_encrypt_fu_188_word_3_address0;
    end else begin
        word_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_3_address1 = grp_decrypt_fu_220_word_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_3_address1 = grp_encrypt_fu_188_word_3_address1;
    end else begin
        word_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_3_ce0 = grp_decrypt_fu_220_word_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_3_ce0 = grp_encrypt_fu_188_word_3_ce0;
    end else begin
        word_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_3_ce1 = grp_decrypt_fu_220_word_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_3_ce1 = grp_encrypt_fu_188_word_3_ce1;
    end else begin
        word_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_3_d0 = grp_decrypt_fu_220_word_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_3_d0 = grp_encrypt_fu_188_word_3_d0;
    end else begin
        word_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        word_3_we0 = grp_decrypt_fu_220_word_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_3_we0 = grp_encrypt_fu_188_word_3_we0;
    end else begin
        word_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_encrypt_fu_188_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_decrypt_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_decrypt_fu_220_ap_start = grp_decrypt_fu_220_ap_start_reg;

assign grp_encrypt_fu_188_ap_start = grp_encrypt_fu_188_ap_start_reg;

endmodule //main
