// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_AddRoundKey_InversMixColumn_Pipeline_VITIS_LOOP_500_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ret_address0,
        ret_ce0,
        ret_q0,
        ret_address1,
        ret_ce1,
        ret_q1,
        ret_1_address0,
        ret_1_ce0,
        ret_1_q0,
        ret_1_address1,
        ret_1_ce1,
        ret_1_q1,
        statemt_0_address0,
        statemt_0_ce0,
        statemt_0_we0,
        statemt_0_d0,
        statemt_1_address0,
        statemt_1_ce0,
        statemt_1_we0,
        statemt_1_d0,
        statemt_2_address0,
        statemt_2_ce0,
        statemt_2_we0,
        statemt_2_d0,
        statemt_3_address0,
        statemt_3_ce0,
        statemt_3_we0,
        statemt_3_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] ret_address0;
output   ret_ce0;
input  [31:0] ret_q0;
output  [3:0] ret_address1;
output   ret_ce1;
input  [31:0] ret_q1;
output  [3:0] ret_1_address0;
output   ret_1_ce0;
input  [31:0] ret_1_q0;
output  [3:0] ret_1_address1;
output   ret_1_ce1;
input  [31:0] ret_1_q1;
output  [2:0] statemt_0_address0;
output   statemt_0_ce0;
output   statemt_0_we0;
output  [31:0] statemt_0_d0;
output  [2:0] statemt_1_address0;
output   statemt_1_ce0;
output   statemt_1_we0;
output  [31:0] statemt_1_d0;
output  [2:0] statemt_2_address0;
output   statemt_2_ce0;
output   statemt_2_we0;
output  [31:0] statemt_2_d0;
output  [2:0] statemt_3_address0;
output   statemt_3_ce0;
output   statemt_3_we0;
output  [31:0] statemt_3_d0;

reg ap_idle;
reg ret_ce0;
reg ret_ce1;
reg ret_1_ce0;
reg ret_1_ce1;
reg statemt_0_ce0;
reg statemt_0_we0;
reg statemt_1_ce0;
reg statemt_1_we0;
reg statemt_2_ce0;
reg statemt_2_we0;
reg statemt_3_ce0;
reg statemt_3_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln500_fu_156_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_6_reg_211;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln502_fu_174_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln504_fu_186_p1;
wire   [63:0] zext_ln500_fu_197_p1;
reg   [2:0] i_fu_38;
wire   [2:0] add_ln500_fu_162_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_6;
wire   [2:0] shl_ln502_fu_168_p2;
wire   [2:0] or_ln504_fu_180_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_38 = 3'd0;
#0 ap_done_reg = 1'b0;
end

main_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln500_fu_156_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_38 <= add_ln500_fu_162_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_38 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_6_reg_211 <= ap_sig_allocacmp_i_6;
    end
end

always @ (*) begin
    if (((icmp_ln500_fu_156_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_6 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_6 = i_fu_38;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_1_ce0 = 1'b1;
    end else begin
        ret_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_1_ce1 = 1'b1;
    end else begin
        ret_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_ce0 = 1'b1;
    end else begin
        ret_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_ce1 = 1'b1;
    end else begin
        ret_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_0_ce0 = 1'b1;
    end else begin
        statemt_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_0_we0 = 1'b1;
    end else begin
        statemt_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_1_ce0 = 1'b1;
    end else begin
        statemt_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_1_we0 = 1'b1;
    end else begin
        statemt_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_2_ce0 = 1'b1;
    end else begin
        statemt_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_2_we0 = 1'b1;
    end else begin
        statemt_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_3_ce0 = 1'b1;
    end else begin
        statemt_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_3_we0 = 1'b1;
    end else begin
        statemt_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln500_fu_162_p2 = (ap_sig_allocacmp_i_6 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln500_fu_156_p2 = ((ap_sig_allocacmp_i_6 == 3'd4) ? 1'b1 : 1'b0);

assign or_ln504_fu_180_p2 = (shl_ln502_fu_168_p2 | 3'd1);

assign ret_1_address0 = zext_ln504_fu_186_p1;

assign ret_1_address1 = zext_ln502_fu_174_p1;

assign ret_address0 = zext_ln504_fu_186_p1;

assign ret_address1 = zext_ln502_fu_174_p1;

assign shl_ln502_fu_168_p2 = ap_sig_allocacmp_i_6 << 3'd1;

assign statemt_0_address0 = zext_ln500_fu_197_p1;

assign statemt_0_d0 = ret_q1;

assign statemt_1_address0 = zext_ln500_fu_197_p1;

assign statemt_1_d0 = ret_1_q1;

assign statemt_2_address0 = zext_ln500_fu_197_p1;

assign statemt_2_d0 = ret_q0;

assign statemt_3_address0 = zext_ln500_fu_197_p1;

assign statemt_3_d0 = ret_1_q0;

assign zext_ln500_fu_197_p1 = i_6_reg_211;

assign zext_ln502_fu_174_p1 = shl_ln502_fu_168_p2;

assign zext_ln504_fu_186_p1 = or_ln504_fu_180_p2;

endmodule //main_AddRoundKey_InversMixColumn_Pipeline_VITIS_LOOP_500_4
