// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_MixColumn_AddRoundKey_Pipeline_VITIS_LOOP_372_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ret_3_address0,
        ret_3_ce0,
        ret_3_we0,
        ret_3_d0,
        ret_2_address0,
        ret_2_ce0,
        ret_2_we0,
        ret_2_d0,
        ret_1_address0,
        ret_1_ce0,
        ret_1_we0,
        ret_1_d0,
        ret_address0,
        ret_ce0,
        ret_we0,
        ret_d0,
        mul,
        statemt_0_address0,
        statemt_0_ce0,
        statemt_0_q0,
        statemt_1_address0,
        statemt_1_ce0,
        statemt_1_q0,
        statemt_2_address0,
        statemt_2_ce0,
        statemt_2_q0,
        statemt_3_address0,
        statemt_3_ce0,
        statemt_3_q0,
        word_0_address0,
        word_0_ce0,
        word_0_q0,
        word_1_address0,
        word_1_ce0,
        word_1_q0,
        word_2_address0,
        word_2_ce0,
        word_2_q0,
        word_3_address0,
        word_3_ce0,
        word_3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] ret_3_address0;
output   ret_3_ce0;
output   ret_3_we0;
output  [31:0] ret_3_d0;
output  [2:0] ret_2_address0;
output   ret_2_ce0;
output   ret_2_we0;
output  [31:0] ret_2_d0;
output  [2:0] ret_1_address0;
output   ret_1_ce0;
output   ret_1_we0;
output  [31:0] ret_1_d0;
output  [2:0] ret_address0;
output   ret_ce0;
output   ret_we0;
output  [31:0] ret_d0;
input  [6:0] mul;
output  [2:0] statemt_0_address0;
output   statemt_0_ce0;
input  [31:0] statemt_0_q0;
output  [2:0] statemt_1_address0;
output   statemt_1_ce0;
input  [31:0] statemt_1_q0;
output  [2:0] statemt_2_address0;
output   statemt_2_ce0;
input  [31:0] statemt_2_q0;
output  [2:0] statemt_3_address0;
output   statemt_3_ce0;
input  [31:0] statemt_3_q0;
output  [6:0] word_0_address0;
output   word_0_ce0;
input  [31:0] word_0_q0;
output  [6:0] word_1_address0;
output   word_1_ce0;
input  [31:0] word_1_q0;
output  [6:0] word_2_address0;
output   word_2_ce0;
input  [31:0] word_2_q0;
output  [6:0] word_3_address0;
output   word_3_ce0;
input  [31:0] word_3_q0;

reg ap_idle;
reg ret_3_ce0;
reg ret_3_we0;
reg ret_2_ce0;
reg ret_2_we0;
reg ret_1_ce0;
reg ret_1_we0;
reg ret_ce0;
reg ret_we0;
reg statemt_0_ce0;
reg statemt_1_ce0;
reg statemt_2_ce0;
reg statemt_3_ce0;
reg word_0_ce0;
reg word_1_ce0;
reg word_2_ce0;
reg word_3_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln372_fu_246_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln372_fu_258_p1;
reg   [63:0] zext_ln372_reg_751;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln384_fu_276_p1;
reg   [2:0] j_fu_72;
wire   [2:0] add_ln372_fu_252_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_6;
wire   [6:0] zext_ln372_1_fu_266_p1;
wire   [6:0] add_ln384_fu_270_p2;
wire   [23:0] tmp_s_fu_295_p4;
wire   [31:0] and_ln_fu_305_p3;
wire   [31:0] shl_ln374_fu_289_p2;
wire   [0:0] icmp_ln375_fu_313_p2;
wire   [31:0] xor_ln376_fu_319_p2;
wire   [31:0] shl_ln378_fu_333_p2;
wire   [31:0] x_1_fu_339_p2;
wire   [23:0] tmp_18_fu_345_p4;
wire   [31:0] and_ln1_fu_355_p3;
wire   [0:0] icmp_ln379_fu_363_p2;
wire   [31:0] xor_ln380_fu_369_p2;
wire   [31:0] select_ln375_fu_325_p3;
wire   [31:0] x_2_fu_375_p3;
wire   [31:0] xor_ln383_1_fu_389_p2;
wire   [31:0] xor_ln383_3_fu_395_p2;
wire   [31:0] xor_ln383_fu_383_p2;
wire   [23:0] tmp_19_fu_408_p4;
wire   [31:0] and_ln2_fu_418_p3;
wire   [0:0] icmp_ln387_fu_426_p2;
wire   [31:0] xor_ln388_fu_432_p2;
wire   [31:0] shl_ln390_fu_446_p2;
wire   [31:0] x_4_fu_452_p2;
wire   [23:0] tmp_20_fu_458_p4;
wire   [31:0] and_ln3_fu_468_p3;
wire   [0:0] icmp_ln391_fu_476_p2;
wire   [31:0] xor_ln392_fu_482_p2;
wire   [31:0] select_ln387_fu_438_p3;
wire   [31:0] x_5_fu_488_p3;
wire   [31:0] xor_ln395_1_fu_502_p2;
wire   [31:0] xor_ln395_3_fu_508_p2;
wire   [31:0] xor_ln395_fu_496_p2;
wire   [23:0] tmp_21_fu_521_p4;
wire   [31:0] and_ln4_fu_531_p3;
wire   [0:0] icmp_ln399_fu_539_p2;
wire   [31:0] xor_ln400_fu_545_p2;
wire   [31:0] shl_ln402_fu_559_p2;
wire   [31:0] x_7_fu_565_p2;
wire   [23:0] tmp_22_fu_571_p4;
wire   [31:0] and_ln5_fu_581_p3;
wire   [0:0] icmp_ln403_fu_589_p2;
wire   [31:0] xor_ln404_fu_595_p2;
wire   [31:0] select_ln399_fu_551_p3;
wire   [31:0] x_8_fu_601_p3;
wire   [31:0] xor_ln407_1_fu_615_p2;
wire   [31:0] xor_ln407_3_fu_621_p2;
wire   [31:0] xor_ln407_fu_609_p2;
wire   [23:0] tmp_23_fu_634_p4;
wire   [31:0] and_ln6_fu_644_p3;
wire   [0:0] icmp_ln411_fu_652_p2;
wire   [31:0] xor_ln412_fu_658_p2;
wire   [31:0] x_10_fu_672_p2;
wire   [23:0] tmp_24_fu_678_p4;
wire   [31:0] and_ln7_fu_688_p3;
wire   [0:0] icmp_ln415_fu_696_p2;
wire   [31:0] xor_ln416_fu_702_p2;
wire   [31:0] x_11_fu_708_p3;
wire   [31:0] select_ln411_fu_664_p3;
wire   [31:0] xor_ln419_1_fu_722_p2;
wire   [31:0] xor_ln419_3_fu_728_p2;
wire   [31:0] xor_ln419_fu_716_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_72 = 3'd0;
#0 ap_done_reg = 1'b0;
end

main_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln372_fu_246_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_72 <= add_ln372_fu_252_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln372_reg_751[2 : 0] <= zext_ln372_fu_258_p1[2 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln372_fu_246_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_6 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_6 = j_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_1_ce0 = 1'b1;
    end else begin
        ret_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_1_we0 = 1'b1;
    end else begin
        ret_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_2_ce0 = 1'b1;
    end else begin
        ret_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_2_we0 = 1'b1;
    end else begin
        ret_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_3_ce0 = 1'b1;
    end else begin
        ret_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_3_we0 = 1'b1;
    end else begin
        ret_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_ce0 = 1'b1;
    end else begin
        ret_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_we0 = 1'b1;
    end else begin
        ret_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_0_ce0 = 1'b1;
    end else begin
        statemt_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_1_ce0 = 1'b1;
    end else begin
        statemt_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_2_ce0 = 1'b1;
    end else begin
        statemt_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        statemt_3_ce0 = 1'b1;
    end else begin
        statemt_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_0_ce0 = 1'b1;
    end else begin
        word_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_1_ce0 = 1'b1;
    end else begin
        word_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_2_ce0 = 1'b1;
    end else begin
        word_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_3_ce0 = 1'b1;
    end else begin
        word_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln372_fu_252_p2 = (ap_sig_allocacmp_j_6 + 3'd1);

assign add_ln384_fu_270_p2 = (zext_ln372_1_fu_266_p1 + mul);

assign and_ln1_fu_355_p3 = {{tmp_18_fu_345_p4}, {8'd0}};

assign and_ln2_fu_418_p3 = {{tmp_19_fu_408_p4}, {8'd0}};

assign and_ln3_fu_468_p3 = {{tmp_20_fu_458_p4}, {8'd0}};

assign and_ln4_fu_531_p3 = {{tmp_21_fu_521_p4}, {8'd0}};

assign and_ln5_fu_581_p3 = {{tmp_22_fu_571_p4}, {8'd0}};

assign and_ln6_fu_644_p3 = {{tmp_23_fu_634_p4}, {8'd0}};

assign and_ln7_fu_688_p3 = {{tmp_24_fu_678_p4}, {8'd0}};

assign and_ln_fu_305_p3 = {{tmp_s_fu_295_p4}, {8'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln372_fu_246_p2 = ((ap_sig_allocacmp_j_6 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln375_fu_313_p2 = ((and_ln_fu_305_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln379_fu_363_p2 = ((and_ln1_fu_355_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln387_fu_426_p2 = ((and_ln2_fu_418_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln391_fu_476_p2 = ((and_ln3_fu_468_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln399_fu_539_p2 = ((and_ln4_fu_531_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln403_fu_589_p2 = ((and_ln5_fu_581_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln411_fu_652_p2 = ((and_ln6_fu_644_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln415_fu_696_p2 = ((and_ln7_fu_688_p3 == 32'd256) ? 1'b1 : 1'b0);

assign ret_1_address0 = zext_ln372_reg_751;

assign ret_1_d0 = (xor_ln395_fu_496_p2 ^ xor_ln395_3_fu_508_p2);

assign ret_2_address0 = zext_ln372_reg_751;

assign ret_2_d0 = (xor_ln407_fu_609_p2 ^ xor_ln407_3_fu_621_p2);

assign ret_3_address0 = zext_ln372_reg_751;

assign ret_3_d0 = (xor_ln419_fu_716_p2 ^ xor_ln419_3_fu_728_p2);

assign ret_address0 = zext_ln372_reg_751;

assign ret_d0 = (xor_ln383_fu_383_p2 ^ xor_ln383_3_fu_395_p2);

assign select_ln375_fu_325_p3 = ((icmp_ln375_fu_313_p2[0:0] == 1'b1) ? xor_ln376_fu_319_p2 : shl_ln374_fu_289_p2);

assign select_ln387_fu_438_p3 = ((icmp_ln387_fu_426_p2[0:0] == 1'b1) ? xor_ln388_fu_432_p2 : shl_ln378_fu_333_p2);

assign select_ln399_fu_551_p3 = ((icmp_ln399_fu_539_p2[0:0] == 1'b1) ? xor_ln400_fu_545_p2 : shl_ln390_fu_446_p2);

assign select_ln411_fu_664_p3 = ((icmp_ln411_fu_652_p2[0:0] == 1'b1) ? xor_ln412_fu_658_p2 : shl_ln402_fu_559_p2);

assign shl_ln374_fu_289_p2 = statemt_0_q0 << 32'd1;

assign shl_ln378_fu_333_p2 = statemt_1_q0 << 32'd1;

assign shl_ln390_fu_446_p2 = statemt_2_q0 << 32'd1;

assign shl_ln402_fu_559_p2 = statemt_3_q0 << 32'd1;

assign statemt_0_address0 = zext_ln372_fu_258_p1;

assign statemt_1_address0 = zext_ln372_fu_258_p1;

assign statemt_2_address0 = zext_ln372_fu_258_p1;

assign statemt_3_address0 = zext_ln372_fu_258_p1;

assign tmp_18_fu_345_p4 = {{x_1_fu_339_p2[31:8]}};

assign tmp_19_fu_408_p4 = {{statemt_1_q0[30:7]}};

assign tmp_20_fu_458_p4 = {{x_4_fu_452_p2[31:8]}};

assign tmp_21_fu_521_p4 = {{statemt_2_q0[30:7]}};

assign tmp_22_fu_571_p4 = {{x_7_fu_565_p2[31:8]}};

assign tmp_23_fu_634_p4 = {{statemt_3_q0[30:7]}};

assign tmp_24_fu_678_p4 = {{x_10_fu_672_p2[31:8]}};

assign tmp_s_fu_295_p4 = {{statemt_0_q0[30:7]}};

assign word_0_address0 = zext_ln384_fu_276_p1;

assign word_1_address0 = zext_ln384_fu_276_p1;

assign word_2_address0 = zext_ln384_fu_276_p1;

assign word_3_address0 = zext_ln384_fu_276_p1;

assign x_10_fu_672_p2 = (statemt_0_q0 ^ shl_ln374_fu_289_p2);

assign x_11_fu_708_p3 = ((icmp_ln415_fu_696_p2[0:0] == 1'b1) ? xor_ln416_fu_702_p2 : x_10_fu_672_p2);

assign x_1_fu_339_p2 = (statemt_1_q0 ^ shl_ln378_fu_333_p2);

assign x_2_fu_375_p3 = ((icmp_ln379_fu_363_p2[0:0] == 1'b1) ? xor_ln380_fu_369_p2 : x_1_fu_339_p2);

assign x_4_fu_452_p2 = (statemt_2_q0 ^ shl_ln390_fu_446_p2);

assign x_5_fu_488_p3 = ((icmp_ln391_fu_476_p2[0:0] == 1'b1) ? xor_ln392_fu_482_p2 : x_4_fu_452_p2);

assign x_7_fu_565_p2 = (statemt_3_q0 ^ shl_ln402_fu_559_p2);

assign x_8_fu_601_p3 = ((icmp_ln403_fu_589_p2[0:0] == 1'b1) ? xor_ln404_fu_595_p2 : x_7_fu_565_p2);

assign xor_ln376_fu_319_p2 = (shl_ln374_fu_289_p2 ^ 32'd283);

assign xor_ln380_fu_369_p2 = (x_1_fu_339_p2 ^ 32'd283);

assign xor_ln383_1_fu_389_p2 = (x_2_fu_375_p3 ^ select_ln375_fu_325_p3);

assign xor_ln383_3_fu_395_p2 = (xor_ln383_1_fu_389_p2 ^ word_0_q0);

assign xor_ln383_fu_383_p2 = (statemt_3_q0 ^ statemt_2_q0);

assign xor_ln388_fu_432_p2 = (shl_ln378_fu_333_p2 ^ 32'd283);

assign xor_ln392_fu_482_p2 = (x_4_fu_452_p2 ^ 32'd283);

assign xor_ln395_1_fu_502_p2 = (x_5_fu_488_p3 ^ select_ln387_fu_438_p3);

assign xor_ln395_3_fu_508_p2 = (xor_ln395_1_fu_502_p2 ^ word_1_q0);

assign xor_ln395_fu_496_p2 = (statemt_3_q0 ^ statemt_0_q0);

assign xor_ln400_fu_545_p2 = (shl_ln390_fu_446_p2 ^ 32'd283);

assign xor_ln404_fu_595_p2 = (x_7_fu_565_p2 ^ 32'd283);

assign xor_ln407_1_fu_615_p2 = (x_8_fu_601_p3 ^ select_ln399_fu_551_p3);

assign xor_ln407_3_fu_621_p2 = (xor_ln407_1_fu_615_p2 ^ word_2_q0);

assign xor_ln407_fu_609_p2 = (statemt_1_q0 ^ statemt_0_q0);

assign xor_ln412_fu_658_p2 = (shl_ln402_fu_559_p2 ^ 32'd283);

assign xor_ln416_fu_702_p2 = (x_10_fu_672_p2 ^ 32'd283);

assign xor_ln419_1_fu_722_p2 = (x_11_fu_708_p3 ^ select_ln411_fu_664_p3);

assign xor_ln419_3_fu_728_p2 = (xor_ln419_1_fu_722_p2 ^ word_3_q0);

assign xor_ln419_fu_716_p2 = (statemt_2_q0 ^ statemt_1_q0);

assign zext_ln372_1_fu_266_p1 = ap_sig_allocacmp_j_6;

assign zext_ln372_fu_258_p1 = ap_sig_allocacmp_j_6;

assign zext_ln384_fu_276_p1 = add_ln384_fu_270_p2;

always @ (posedge ap_clk) begin
    zext_ln372_reg_751[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //main_MixColumn_AddRoundKey_Pipeline_VITIS_LOOP_372_1
