// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_encrypt_Pipeline_VITIS_LOOP_138_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        word_1_address0,
        word_1_ce0,
        word_1_we0,
        word_1_d0,
        word_1_q0,
        word_1_address1,
        word_1_ce1,
        word_1_q1,
        word_2_address0,
        word_2_ce0,
        word_2_we0,
        word_2_d0,
        word_2_q0,
        word_2_address1,
        word_2_ce1,
        word_2_q1,
        word_3_address0,
        word_3_ce0,
        word_3_we0,
        word_3_d0,
        word_3_q0,
        word_3_address1,
        word_3_ce1,
        word_3_q1,
        word_0_address0,
        word_0_ce0,
        word_0_we0,
        word_0_d0,
        word_0_q0,
        word_0_address1,
        word_0_ce1,
        word_0_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] word_1_address0;
output   word_1_ce0;
output   word_1_we0;
output  [31:0] word_1_d0;
input  [31:0] word_1_q0;
output  [6:0] word_1_address1;
output   word_1_ce1;
input  [31:0] word_1_q1;
output  [6:0] word_2_address0;
output   word_2_ce0;
output   word_2_we0;
output  [31:0] word_2_d0;
input  [31:0] word_2_q0;
output  [6:0] word_2_address1;
output   word_2_ce1;
input  [31:0] word_2_q1;
output  [6:0] word_3_address0;
output   word_3_ce0;
output   word_3_we0;
output  [31:0] word_3_d0;
input  [31:0] word_3_q0;
output  [6:0] word_3_address1;
output   word_3_ce1;
input  [31:0] word_3_q1;
output  [6:0] word_0_address0;
output   word_0_ce0;
output   word_0_we0;
output  [31:0] word_0_d0;
input  [31:0] word_0_q0;
output  [6:0] word_0_address1;
output   word_0_ce1;
input  [31:0] word_0_q1;

reg ap_idle;
reg[6:0] word_1_address0;
reg word_1_ce0;
reg word_1_we0;
reg word_1_ce1;
reg[6:0] word_2_address0;
reg word_2_ce0;
reg word_2_we0;
reg word_2_ce1;
reg[6:0] word_3_address0;
reg word_3_ce0;
reg word_3_we0;
reg word_3_ce1;
reg[6:0] word_0_address0;
reg word_0_ce0;
reg word_0_we0;
reg word_0_ce1;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln138_reg_1173;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [7:0] Sbox_address0;
reg    Sbox_ce0;
wire   [7:0] Sbox_q0;
reg   [7:0] Sbox_address1;
reg    Sbox_ce1;
wire   [7:0] Sbox_q1;
wire   [4:0] Rcon0_address0;
reg    Rcon0_ce0;
wire   [7:0] Rcon0_q0;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] j_reg_1167;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln138_fu_348_p2;
wire   [0:0] addr_cmp50_fu_371_p2;
reg   [0:0] addr_cmp50_reg_1197;
wire   [0:0] addr_cmp44_fu_380_p2;
reg   [0:0] addr_cmp44_reg_1202;
wire   [0:0] addr_cmp_fu_389_p2;
reg   [0:0] addr_cmp_reg_1207;
wire   [0:0] addr_cmp56_fu_398_p2;
reg   [0:0] addr_cmp56_reg_1212;
wire   [63:0] zext_ln160_fu_431_p1;
reg   [63:0] zext_ln160_reg_1222;
wire   [31:0] reuse_select51_fu_452_p3;
reg   [31:0] reuse_select51_reg_1242;
wire    ap_block_pp0_stage2_11001;
wire   [31:0] reuse_select45_fu_466_p3;
reg   [31:0] reuse_select45_reg_1247;
reg   [31:0] word_3_load_1_reg_1252;
reg   [31:0] word_0_load_1_reg_1257;
reg   [7:0] Rcon0_load_reg_1267;
reg   [31:0] word_0_load_reg_1277;
reg   [31:0] word_1_load_reg_1282;
reg   [31:0] word_2_load_reg_1287;
wire   [63:0] zext_ln138_fu_715_p1;
reg   [63:0] zext_ln138_reg_1292;
wire   [0:0] icmp_ln142_fu_723_p2;
reg   [0:0] icmp_ln142_reg_1298;
wire   [31:0] reuse_select_fu_732_p3;
reg   [31:0] reuse_select_reg_1304;
reg   [7:0] temp_3_reg_1319;
wire   [31:0] xor_ln160_2_fu_1073_p2;
reg   [31:0] xor_ln160_2_reg_1329;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln144_1_fu_360_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln144_fu_420_p1;
wire   [63:0] zext_ln248_2_fu_591_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln248_5_fu_710_p1;
wire   [63:0] zext_ln248_8_fu_882_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln248_11_fu_1001_p1;
reg   [63:0] reuse_addr_reg53_fu_78;
wire    ap_loop_init;
reg   [31:0] reuse_reg52_fu_82;
wire   [31:0] xor_ln160_fu_1021_p2;
reg   [63:0] reuse_addr_reg47_fu_86;
reg   [31:0] reuse_reg46_fu_90;
wire   [31:0] xor_ln160_1_fu_1027_p2;
reg   [63:0] reuse_addr_reg41_fu_94;
reg   [31:0] reuse_reg40_fu_98;
reg   [63:0] reuse_addr_reg_fu_102;
reg   [31:0] reuse_reg_fu_106;
wire   [31:0] xor_ln160_3_fu_1092_p2;
reg   [5:0] j_1_fu_110;
wire   [5:0] add_ln138_fu_438_p2;
wire   [5:0] add_ln144_fu_354_p2;
wire   [3:0] trunc_ln6_fu_404_p4;
wire   [3:0] add_ln144_1_fu_414_p2;
wire   [5:0] empty_30_fu_425_p2;
wire   [7:0] trunc_ln145_fu_459_p1;
wire   [7:0] sub_ln248_fu_485_p2;
wire   [3:0] trunc_ln248_4_fu_491_p4;
wire   [0:0] tmp_fu_477_p3;
wire   [3:0] sub_ln248_1_fu_501_p2;
wire   [3:0] tmp_3_fu_507_p4;
wire   [3:0] select_ln248_fu_517_p3;
wire   [3:0] trunc_ln248_fu_533_p1;
wire   [4:0] p_and_f1_fu_537_p3;
wire   [3:0] sub_ln248_8_fu_549_p2;
wire   [4:0] p_and_t1_fu_555_p3;
wire   [5:0] zext_ln248_1_fu_563_p1;
wire   [5:0] sub_ln248_9_fu_567_p2;
wire   [5:0] zext_ln248_fu_545_p1;
wire   [5:0] select_ln248_1_fu_573_p3;
wire   [7:0] tmp_4_fu_525_p3;
wire  signed [7:0] sext_ln248_fu_581_p1;
wire   [7:0] add_ln248_fu_585_p2;
wire   [7:0] trunc_ln146_fu_473_p1;
wire   [7:0] sub_ln248_2_fu_604_p2;
wire   [3:0] trunc_ln248_6_fu_610_p4;
wire   [0:0] tmp_1_fu_596_p3;
wire   [3:0] sub_ln248_3_fu_620_p2;
wire   [3:0] tmp_7_fu_626_p4;
wire   [3:0] select_ln248_2_fu_636_p3;
wire   [3:0] trunc_ln248_1_fu_652_p1;
wire   [4:0] p_and_f2_fu_656_p3;
wire   [3:0] sub_ln248_10_fu_668_p2;
wire   [4:0] p_and_t2_fu_674_p3;
wire   [5:0] zext_ln248_4_fu_682_p1;
wire   [5:0] sub_ln248_11_fu_686_p2;
wire   [5:0] zext_ln248_3_fu_664_p1;
wire   [5:0] select_ln248_3_fu_692_p3;
wire   [7:0] tmp_8_fu_644_p3;
wire  signed [7:0] sext_ln248_1_fu_700_p1;
wire   [7:0] add_ln248_1_fu_704_p2;
wire   [1:0] empty_fu_720_p1;
wire   [31:0] reuse_select57_fu_745_p3;
wire   [7:0] temp_fu_755_p2;
wire   [7:0] trunc_ln147_fu_738_p1;
wire   [7:0] sub_ln248_4_fu_776_p2;
wire   [3:0] trunc_ln248_8_fu_782_p4;
wire   [0:0] tmp_2_fu_768_p3;
wire   [3:0] sub_ln248_5_fu_792_p2;
wire   [3:0] tmp_s_fu_798_p4;
wire   [3:0] select_ln248_4_fu_808_p3;
wire   [3:0] trunc_ln248_2_fu_824_p1;
wire   [4:0] p_and_f4_fu_828_p3;
wire   [3:0] sub_ln248_12_fu_840_p2;
wire   [4:0] p_and_t6_fu_846_p3;
wire   [5:0] zext_ln248_7_fu_854_p1;
wire   [5:0] sub_ln248_13_fu_858_p2;
wire   [5:0] zext_ln248_6_fu_836_p1;
wire   [5:0] select_ln248_5_fu_864_p3;
wire   [7:0] tmp_5_fu_816_p3;
wire  signed [7:0] sext_ln248_2_fu_872_p1;
wire   [7:0] add_ln248_2_fu_876_p2;
wire   [7:0] trunc_ln246_fu_751_p1;
wire   [7:0] sub_ln248_6_fu_895_p2;
wire   [3:0] trunc_ln248_s_fu_901_p4;
wire   [0:0] tmp_6_fu_887_p3;
wire   [3:0] sub_ln248_7_fu_911_p2;
wire   [3:0] tmp_9_fu_917_p4;
wire   [3:0] select_ln248_6_fu_927_p3;
wire   [3:0] trunc_ln248_3_fu_943_p1;
wire   [4:0] p_and_f_fu_947_p3;
wire   [3:0] sub_ln248_14_fu_959_p2;
wire   [4:0] p_and_t_fu_965_p3;
wire   [5:0] zext_ln248_10_fu_973_p1;
wire   [5:0] sub_ln248_15_fu_977_p2;
wire   [5:0] zext_ln248_9_fu_955_p1;
wire   [5:0] select_ln248_7_fu_983_p3;
wire   [7:0] tmp_10_fu_935_p3;
wire  signed [7:0] sext_ln248_3_fu_991_p1;
wire   [7:0] add_ln248_3_fu_995_p2;
wire   [31:0] zext_ln80_1_fu_764_p1;
wire   [31:0] zext_ln80_fu_760_p1;
wire   [31:0] temp_4_fu_1013_p3;
wire   [31:0] temp_5_fu_1006_p3;
wire   [31:0] zext_ln80_2_fu_1063_p1;
wire   [31:0] temp_6_fu_1067_p3;
wire   [31:0] zext_ln80_3_fu_1083_p1;
wire   [31:0] temp_7_fu_1086_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 reuse_addr_reg53_fu_78 = 64'd0;
#0 reuse_reg52_fu_82 = 32'd0;
#0 reuse_addr_reg47_fu_86 = 64'd0;
#0 reuse_reg46_fu_90 = 32'd0;
#0 reuse_addr_reg41_fu_94 = 64'd0;
#0 reuse_reg40_fu_98 = 32'd0;
#0 reuse_addr_reg_fu_102 = 64'd0;
#0 reuse_reg_fu_106 = 32'd0;
#0 j_1_fu_110 = 6'd0;
#0 ap_done_reg = 1'b0;
end

main_encrypt_Pipeline_VITIS_LOOP_138_3_Sbox_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
Sbox_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Sbox_address0),
    .ce0(Sbox_ce0),
    .q0(Sbox_q0),
    .address1(Sbox_address1),
    .ce1(Sbox_ce1),
    .q1(Sbox_q1)
);

main_encrypt_Pipeline_VITIS_LOOP_138_3_Rcon0_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
Rcon0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Rcon0_address0),
    .ce0(Rcon0_ce0),
    .q0(Rcon0_q0)
);

main_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_1_fu_110 <= 6'd4;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln138_fu_348_p2 == 1'd0))) begin
        j_1_fu_110 <= add_ln138_fu_438_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg41_fu_94 <= 64'd18446744073709551615;
        end else if (((icmp_ln138_reg_1173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg41_fu_94 <= zext_ln138_fu_715_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg47_fu_86 <= 64'd18446744073709551615;
        end else if (((icmp_ln138_reg_1173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg47_fu_86 <= zext_ln138_fu_715_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg53_fu_78 <= 64'd18446744073709551615;
        end else if (((icmp_ln138_reg_1173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg53_fu_78 <= zext_ln138_fu_715_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg_fu_102 <= 64'd18446744073709551615;
        end else if (((icmp_ln138_reg_1173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg_fu_102 <= zext_ln138_fu_715_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reuse_reg40_fu_98 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reuse_reg40_fu_98 <= xor_ln160_2_fu_1073_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_reg46_fu_90 <= 32'd0;
        end else if (((icmp_ln138_reg_1173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_reg46_fu_90 <= xor_ln160_1_fu_1027_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_reg52_fu_82 <= 32'd0;
        end else if (((icmp_ln138_reg_1173 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_reg52_fu_82 <= xor_ln160_fu_1021_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reuse_reg_fu_106 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reuse_reg_fu_106 <= xor_ln160_3_fu_1092_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Rcon0_load_reg_1267 <= Rcon0_q0;
        reuse_select45_reg_1247 <= reuse_select45_fu_466_p3;
        reuse_select51_reg_1242 <= reuse_select51_fu_452_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        addr_cmp44_reg_1202 <= addr_cmp44_fu_380_p2;
        addr_cmp50_reg_1197 <= addr_cmp50_fu_371_p2;
        addr_cmp56_reg_1212 <= addr_cmp56_fu_398_p2;
        addr_cmp_reg_1207 <= addr_cmp_fu_389_p2;
        icmp_ln138_reg_1173 <= icmp_ln138_fu_348_p2;
        j_reg_1167 <= j_1_fu_110;
        xor_ln160_2_reg_1329 <= xor_ln160_2_fu_1073_p2;
        zext_ln160_reg_1222[5 : 0] <= zext_ln160_fu_431_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln142_reg_1298 <= icmp_ln142_fu_723_p2;
        reuse_select_reg_1304 <= reuse_select_fu_732_p3;
        zext_ln138_reg_1292[5 : 0] <= zext_ln138_fu_715_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        temp_3_reg_1319 <= Sbox_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        word_0_load_1_reg_1257 <= word_0_q1;
        word_0_load_reg_1277 <= word_0_q0;
        word_1_load_reg_1282 <= word_1_q0;
        word_2_load_reg_1287 <= word_2_q0;
        word_3_load_1_reg_1252 <= word_3_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Rcon0_ce0 = 1'b1;
    end else begin
        Rcon0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Sbox_address0 = zext_ln248_11_fu_1001_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Sbox_address0 = zext_ln248_5_fu_710_p1;
    end else begin
        Sbox_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Sbox_address1 = zext_ln248_8_fu_882_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Sbox_address1 = zext_ln248_2_fu_591_p1;
    end else begin
        Sbox_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Sbox_ce0 = 1'b1;
    end else begin
        Sbox_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Sbox_ce1 = 1'b1;
    end else begin
        Sbox_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln138_reg_1173 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_0_address0 = zext_ln138_fu_715_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        word_0_address0 = zext_ln160_fu_431_p1;
    end else begin
        word_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        word_0_ce0 = 1'b1;
    end else begin
        word_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        word_0_ce1 = 1'b1;
    end else begin
        word_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln138_reg_1173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_0_we0 = 1'b1;
    end else begin
        word_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_1_address0 = zext_ln138_fu_715_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        word_1_address0 = zext_ln160_fu_431_p1;
    end else begin
        word_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        word_1_ce0 = 1'b1;
    end else begin
        word_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        word_1_ce1 = 1'b1;
    end else begin
        word_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln138_reg_1173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_1_we0 = 1'b1;
    end else begin
        word_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        word_2_address0 = zext_ln138_reg_1292;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        word_2_address0 = zext_ln160_fu_431_p1;
    end else begin
        word_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        word_2_ce0 = 1'b1;
    end else begin
        word_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        word_2_ce1 = 1'b1;
    end else begin
        word_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        word_2_we0 = 1'b1;
    end else begin
        word_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            word_3_address0 = zext_ln138_reg_1292;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            word_3_address0 = zext_ln160_reg_1222;
        end else begin
            word_3_address0 = 'bx;
        end
    end else begin
        word_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        word_3_ce0 = 1'b1;
    end else begin
        word_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        word_3_ce1 = 1'b1;
    end else begin
        word_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        word_3_we0 = 1'b1;
    end else begin
        word_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Rcon0_address0 = zext_ln144_fu_420_p1;

assign add_ln138_fu_438_p2 = (j_1_fu_110 + 6'd1);

assign add_ln144_1_fu_414_p2 = ($signed(trunc_ln6_fu_404_p4) + $signed(4'd15));

assign add_ln144_fu_354_p2 = ($signed(j_1_fu_110) + $signed(6'd63));

assign add_ln248_1_fu_704_p2 = ($signed(tmp_8_fu_644_p3) + $signed(sext_ln248_1_fu_700_p1));

assign add_ln248_2_fu_876_p2 = ($signed(tmp_5_fu_816_p3) + $signed(sext_ln248_2_fu_872_p1));

assign add_ln248_3_fu_995_p2 = ($signed(tmp_10_fu_935_p3) + $signed(sext_ln248_3_fu_991_p1));

assign add_ln248_fu_585_p2 = ($signed(tmp_4_fu_525_p3) + $signed(sext_ln248_fu_581_p1));

assign addr_cmp44_fu_380_p2 = ((reuse_addr_reg41_fu_94 == zext_ln144_1_fu_360_p1) ? 1'b1 : 1'b0);

assign addr_cmp50_fu_371_p2 = ((reuse_addr_reg47_fu_86 == zext_ln144_1_fu_360_p1) ? 1'b1 : 1'b0);

assign addr_cmp56_fu_398_p2 = ((reuse_addr_reg53_fu_78 == zext_ln144_1_fu_360_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_389_p2 = ((reuse_addr_reg_fu_102 == zext_ln144_1_fu_360_p1) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign empty_30_fu_425_p2 = ($signed(j_1_fu_110) + $signed(6'd60));

assign empty_fu_720_p1 = j_reg_1167[1:0];

assign icmp_ln138_fu_348_p2 = ((j_1_fu_110 == 6'd44) ? 1'b1 : 1'b0);

assign icmp_ln142_fu_723_p2 = ((empty_fu_720_p1 == 2'd0) ? 1'b1 : 1'b0);

assign p_and_f1_fu_537_p3 = {{1'd0}, {trunc_ln248_fu_533_p1}};

assign p_and_f2_fu_656_p3 = {{1'd0}, {trunc_ln248_1_fu_652_p1}};

assign p_and_f4_fu_828_p3 = {{1'd0}, {trunc_ln248_2_fu_824_p1}};

assign p_and_f_fu_947_p3 = {{1'd0}, {trunc_ln248_3_fu_943_p1}};

assign p_and_t1_fu_555_p3 = {{1'd0}, {sub_ln248_8_fu_549_p2}};

assign p_and_t2_fu_674_p3 = {{1'd0}, {sub_ln248_10_fu_668_p2}};

assign p_and_t6_fu_846_p3 = {{1'd0}, {sub_ln248_12_fu_840_p2}};

assign p_and_t_fu_965_p3 = {{1'd0}, {sub_ln248_14_fu_959_p2}};

assign reuse_select45_fu_466_p3 = ((addr_cmp44_reg_1202[0:0] == 1'b1) ? reuse_reg40_fu_98 : word_2_q1);

assign reuse_select51_fu_452_p3 = ((addr_cmp50_reg_1197[0:0] == 1'b1) ? reuse_reg46_fu_90 : word_1_q1);

assign reuse_select57_fu_745_p3 = ((addr_cmp56_reg_1212[0:0] == 1'b1) ? reuse_reg52_fu_82 : word_0_load_1_reg_1257);

assign reuse_select_fu_732_p3 = ((addr_cmp_reg_1207[0:0] == 1'b1) ? reuse_reg_fu_106 : word_3_load_1_reg_1252);

assign select_ln248_1_fu_573_p3 = ((tmp_fu_477_p3[0:0] == 1'b1) ? sub_ln248_9_fu_567_p2 : zext_ln248_fu_545_p1);

assign select_ln248_2_fu_636_p3 = ((tmp_1_fu_596_p3[0:0] == 1'b1) ? sub_ln248_3_fu_620_p2 : tmp_7_fu_626_p4);

assign select_ln248_3_fu_692_p3 = ((tmp_1_fu_596_p3[0:0] == 1'b1) ? sub_ln248_11_fu_686_p2 : zext_ln248_3_fu_664_p1);

assign select_ln248_4_fu_808_p3 = ((tmp_2_fu_768_p3[0:0] == 1'b1) ? sub_ln248_5_fu_792_p2 : tmp_s_fu_798_p4);

assign select_ln248_5_fu_864_p3 = ((tmp_2_fu_768_p3[0:0] == 1'b1) ? sub_ln248_13_fu_858_p2 : zext_ln248_6_fu_836_p1);

assign select_ln248_6_fu_927_p3 = ((tmp_6_fu_887_p3[0:0] == 1'b1) ? sub_ln248_7_fu_911_p2 : tmp_9_fu_917_p4);

assign select_ln248_7_fu_983_p3 = ((tmp_6_fu_887_p3[0:0] == 1'b1) ? sub_ln248_15_fu_977_p2 : zext_ln248_9_fu_955_p1);

assign select_ln248_fu_517_p3 = ((tmp_fu_477_p3[0:0] == 1'b1) ? sub_ln248_1_fu_501_p2 : tmp_3_fu_507_p4);

assign sext_ln248_1_fu_700_p1 = $signed(select_ln248_3_fu_692_p3);

assign sext_ln248_2_fu_872_p1 = $signed(select_ln248_5_fu_864_p3);

assign sext_ln248_3_fu_991_p1 = $signed(select_ln248_7_fu_983_p3);

assign sext_ln248_fu_581_p1 = $signed(select_ln248_1_fu_573_p3);

assign sub_ln248_10_fu_668_p2 = (4'd0 - trunc_ln248_1_fu_652_p1);

assign sub_ln248_11_fu_686_p2 = (6'd0 - zext_ln248_4_fu_682_p1);

assign sub_ln248_12_fu_840_p2 = (4'd0 - trunc_ln248_2_fu_824_p1);

assign sub_ln248_13_fu_858_p2 = (6'd0 - zext_ln248_7_fu_854_p1);

assign sub_ln248_14_fu_959_p2 = (4'd0 - trunc_ln248_3_fu_943_p1);

assign sub_ln248_15_fu_977_p2 = (6'd0 - zext_ln248_10_fu_973_p1);

assign sub_ln248_1_fu_501_p2 = (4'd0 - trunc_ln248_4_fu_491_p4);

assign sub_ln248_2_fu_604_p2 = (8'd0 - trunc_ln146_fu_473_p1);

assign sub_ln248_3_fu_620_p2 = (4'd0 - trunc_ln248_6_fu_610_p4);

assign sub_ln248_4_fu_776_p2 = (8'd0 - trunc_ln147_fu_738_p1);

assign sub_ln248_5_fu_792_p2 = (4'd0 - trunc_ln248_8_fu_782_p4);

assign sub_ln248_6_fu_895_p2 = (8'd0 - trunc_ln246_fu_751_p1);

assign sub_ln248_7_fu_911_p2 = (4'd0 - trunc_ln248_s_fu_901_p4);

assign sub_ln248_8_fu_549_p2 = (4'd0 - trunc_ln248_fu_533_p1);

assign sub_ln248_9_fu_567_p2 = (6'd0 - zext_ln248_1_fu_563_p1);

assign sub_ln248_fu_485_p2 = (8'd0 - trunc_ln145_fu_459_p1);

assign temp_4_fu_1013_p3 = ((icmp_ln142_fu_723_p2[0:0] == 1'b1) ? zext_ln80_fu_760_p1 : reuse_select57_fu_745_p3);

assign temp_5_fu_1006_p3 = ((icmp_ln142_fu_723_p2[0:0] == 1'b1) ? zext_ln80_1_fu_764_p1 : reuse_select51_reg_1242);

assign temp_6_fu_1067_p3 = ((icmp_ln142_reg_1298[0:0] == 1'b1) ? zext_ln80_2_fu_1063_p1 : reuse_select45_reg_1247);

assign temp_7_fu_1086_p3 = ((icmp_ln142_reg_1298[0:0] == 1'b1) ? zext_ln80_3_fu_1083_p1 : reuse_select_reg_1304);

assign temp_fu_755_p2 = (Sbox_q1 ^ Rcon0_load_reg_1267);

assign tmp_10_fu_935_p3 = {{select_ln248_6_fu_927_p3}, {4'd0}};

assign tmp_1_fu_596_p3 = reuse_select45_fu_466_p3[32'd31];

assign tmp_2_fu_768_p3 = reuse_select_fu_732_p3[32'd31];

assign tmp_3_fu_507_p4 = {{reuse_select51_fu_452_p3[7:4]}};

assign tmp_4_fu_525_p3 = {{select_ln248_fu_517_p3}, {4'd0}};

assign tmp_5_fu_816_p3 = {{select_ln248_4_fu_808_p3}, {4'd0}};

assign tmp_6_fu_887_p3 = reuse_select57_fu_745_p3[32'd31];

assign tmp_7_fu_626_p4 = {{reuse_select45_fu_466_p3[7:4]}};

assign tmp_8_fu_644_p3 = {{select_ln248_2_fu_636_p3}, {4'd0}};

assign tmp_9_fu_917_p4 = {{reuse_select57_fu_745_p3[7:4]}};

assign tmp_fu_477_p3 = reuse_select51_fu_452_p3[32'd31];

assign tmp_s_fu_798_p4 = {{reuse_select_fu_732_p3[7:4]}};

assign trunc_ln145_fu_459_p1 = reuse_select51_fu_452_p3[7:0];

assign trunc_ln146_fu_473_p1 = reuse_select45_fu_466_p3[7:0];

assign trunc_ln147_fu_738_p1 = reuse_select_fu_732_p3[7:0];

assign trunc_ln246_fu_751_p1 = reuse_select57_fu_745_p3[7:0];

assign trunc_ln248_1_fu_652_p1 = reuse_select45_fu_466_p3[3:0];

assign trunc_ln248_2_fu_824_p1 = reuse_select_fu_732_p3[3:0];

assign trunc_ln248_3_fu_943_p1 = reuse_select57_fu_745_p3[3:0];

assign trunc_ln248_4_fu_491_p4 = {{sub_ln248_fu_485_p2[7:4]}};

assign trunc_ln248_6_fu_610_p4 = {{sub_ln248_2_fu_604_p2[7:4]}};

assign trunc_ln248_8_fu_782_p4 = {{sub_ln248_4_fu_776_p2[7:4]}};

assign trunc_ln248_fu_533_p1 = reuse_select51_fu_452_p3[3:0];

assign trunc_ln248_s_fu_901_p4 = {{sub_ln248_6_fu_895_p2[7:4]}};

assign trunc_ln6_fu_404_p4 = {{j_1_fu_110[5:2]}};

assign word_0_address1 = zext_ln144_1_fu_360_p1;

assign word_0_d0 = (word_0_load_reg_1277 ^ temp_4_fu_1013_p3);

assign word_1_address1 = zext_ln144_1_fu_360_p1;

assign word_1_d0 = (word_1_load_reg_1282 ^ temp_5_fu_1006_p3);

assign word_2_address1 = zext_ln144_1_fu_360_p1;

assign word_2_d0 = xor_ln160_2_reg_1329;

assign word_3_address1 = zext_ln144_1_fu_360_p1;

assign word_3_d0 = (word_3_q0 ^ temp_7_fu_1086_p3);

assign xor_ln160_1_fu_1027_p2 = (word_1_load_reg_1282 ^ temp_5_fu_1006_p3);

assign xor_ln160_2_fu_1073_p2 = (word_2_load_reg_1287 ^ temp_6_fu_1067_p3);

assign xor_ln160_3_fu_1092_p2 = (word_3_q0 ^ temp_7_fu_1086_p3);

assign xor_ln160_fu_1021_p2 = (word_0_load_reg_1277 ^ temp_4_fu_1013_p3);

assign zext_ln138_fu_715_p1 = j_reg_1167;

assign zext_ln144_1_fu_360_p1 = add_ln144_fu_354_p2;

assign zext_ln144_fu_420_p1 = add_ln144_1_fu_414_p2;

assign zext_ln160_fu_431_p1 = empty_30_fu_425_p2;

assign zext_ln248_10_fu_973_p1 = p_and_t_fu_965_p3;

assign zext_ln248_11_fu_1001_p1 = add_ln248_3_fu_995_p2;

assign zext_ln248_1_fu_563_p1 = p_and_t1_fu_555_p3;

assign zext_ln248_2_fu_591_p1 = add_ln248_fu_585_p2;

assign zext_ln248_3_fu_664_p1 = p_and_f2_fu_656_p3;

assign zext_ln248_4_fu_682_p1 = p_and_t2_fu_674_p3;

assign zext_ln248_5_fu_710_p1 = add_ln248_1_fu_704_p2;

assign zext_ln248_6_fu_836_p1 = p_and_f4_fu_828_p3;

assign zext_ln248_7_fu_854_p1 = p_and_t6_fu_846_p3;

assign zext_ln248_8_fu_882_p1 = add_ln248_2_fu_876_p2;

assign zext_ln248_9_fu_955_p1 = p_and_f_fu_947_p3;

assign zext_ln248_fu_545_p1 = p_and_f1_fu_537_p3;

assign zext_ln80_1_fu_764_p1 = Sbox_q0;

assign zext_ln80_2_fu_1063_p1 = Sbox_q1;

assign zext_ln80_3_fu_1083_p1 = temp_3_reg_1319;

assign zext_ln80_fu_760_p1 = temp_fu_755_p2;

always @ (posedge ap_clk) begin
    zext_ln160_reg_1222[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln138_reg_1292[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //main_encrypt_Pipeline_VITIS_LOOP_138_3
